use alef_core::backend::{Backend, BuildConfig, BuildDependency, Capabilities, GeneratedFile};
use alef_core::config::{AlefConfig, Language, resolve_output_dir};
use alef_core::ir::{ApiSurface, EnumDef, FunctionDef, ParamDef, PrimitiveType, TypeDef, TypeRef};
use std::collections::BTreeSet;
use std::path::PathBuf;

pub struct GleamBackend;

impl Backend for GleamBackend {
    fn name(&self) -> &str {
        "gleam"
    }

    fn language(&self) -> Language {
        Language::Gleam
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: false,
            supports_classes: false,
            supports_enums: true,
            supports_option: true,
            supports_result: true,
            supports_callbacks: false,
            supports_streaming: false,
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let module_name = gleam_module_name(&config.crate_config.name);
        let nif_module = nif_module_name(&config.crate_config.name);

        let mut imports: BTreeSet<&'static str> = BTreeSet::new();
        let mut body = String::new();

        for ty in &api.types {
            emit_type(ty, &mut body, &mut imports);
            body.push('\n');
        }

        for en in &api.enums {
            emit_enum(en, &mut body, &mut imports);
            body.push('\n');
        }

        for f in &api.functions {
            emit_function(f, &nif_module, &mut body, &mut imports);
            body.push('\n');
        }

        let mut content = String::new();
        content.push_str("// Generated by alef. Do not edit by hand.\n\n");
        for import in &imports {
            content.push_str(import);
            content.push('\n');
        }
        if !imports.is_empty() {
            content.push('\n');
        }
        content.push_str(&body);

        let dir = resolve_output_dir(None, &config.crate_config.name, "packages/gleam/src");
        let path = PathBuf::from(dir).join(format!("{module_name}.gleam"));

        Ok(vec![GeneratedFile {
            path,
            content,
            generated_header: false,
        }])
    }

    fn build_config(&self) -> Option<BuildConfig> {
        Some(BuildConfig {
            tool: "gleam",
            crate_suffix: "",
            build_dep: BuildDependency::Rustler,
            post_build: vec![],
        })
    }
}

fn emit_type(ty: &TypeDef, out: &mut String, imports: &mut BTreeSet<&'static str>) {
    if !ty.doc.is_empty() {
        for line in ty.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    if ty.fields.is_empty() {
        // Opaque or unit-like — emit a phantom external type
        out.push_str(&format!("pub type {} {{\n  {}\n}}\n", ty.name, ty.name));
        return;
    }
    out.push_str(&format!("pub type {} {{\n  {}(\n", ty.name, ty.name));
    for (idx, field) in ty.fields.iter().enumerate() {
        let ty_str = gleam_type(&field.ty, field.optional, imports);
        let comma = if idx + 1 == ty.fields.len() { "" } else { "," };
        out.push_str(&format!("    {}: {}{}\n", field.name, ty_str, comma));
    }
    out.push_str("  )\n}\n");
}

fn emit_enum(en: &EnumDef, out: &mut String, imports: &mut BTreeSet<&'static str>) {
    if !en.doc.is_empty() {
        for line in en.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!("pub type {} {{\n", en.name));
    for variant in &en.variants {
        if variant.fields.is_empty() {
            out.push_str(&format!("  {}\n", variant.name));
        } else {
            out.push_str(&format!("  {}(\n", variant.name));
            for (idx, field) in variant.fields.iter().enumerate() {
                let ty_str = gleam_type(&field.ty, field.optional, imports);
                let comma = if idx + 1 == variant.fields.len() { "" } else { "," };
                let name = if field.name.is_empty() {
                    format!("field_{idx}")
                } else {
                    field.name.clone()
                };
                out.push_str(&format!("    {name}: {ty_str}{comma}\n"));
            }
            out.push_str("  )\n");
        }
    }
    out.push_str("}\n");
}

fn emit_function(f: &FunctionDef, nif_module: &str, out: &mut String, imports: &mut BTreeSet<&'static str>) {
    if !f.doc.is_empty() {
        for line in f.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!("@external(erlang, \"{nif_module}\", \"{}\")\n", f.name));
    out.push_str(&format!("pub fn {}(", f.name));
    let params: Vec<String> = f.params.iter().map(|p| format_param(p, imports)).collect();
    out.push_str(&params.join(", "));
    out.push(')');

    let return_ty = gleam_type(&f.return_type, false, imports);
    let return_str = if let Some(err_ty) = &f.error_type {
        format!("Result({return_ty}, {err_ty})")
    } else {
        return_ty
    };
    out.push_str(&format!(" -> {return_str}\n"));
}

fn format_param(p: &ParamDef, imports: &mut BTreeSet<&'static str>) -> String {
    let ty_str = gleam_type(&p.ty, p.optional, imports);
    format!("{}: {}", p.name, ty_str)
}

fn gleam_type(ty: &TypeRef, optional: bool, imports: &mut BTreeSet<&'static str>) -> String {
    let inner = render_type_ref(ty, imports);
    if optional {
        imports.insert("import gleam/option.{type Option}");
        format!("Option({inner})")
    } else {
        inner
    }
}

fn render_type_ref(ty: &TypeRef, imports: &mut BTreeSet<&'static str>) -> String {
    match ty {
        TypeRef::Primitive(p) => primitive(p).to_string(),
        TypeRef::String | TypeRef::Char | TypeRef::Path | TypeRef::Json => "String".to_string(),
        TypeRef::Bytes => "BitArray".to_string(),
        TypeRef::Optional(inner) => {
            imports.insert("import gleam/option.{type Option}");
            format!("Option({})", render_type_ref(inner, imports))
        }
        TypeRef::Vec(inner) => format!("List({})", render_type_ref(inner, imports)),
        TypeRef::Map(k, v) => {
            imports.insert("import gleam/dict.{type Dict}");
            format!(
                "Dict({}, {})",
                render_type_ref(k, imports),
                render_type_ref(v, imports)
            )
        }
        TypeRef::Named(name) => name.clone(),
        TypeRef::Unit => "Nil".to_string(),
        TypeRef::Duration => "Int".to_string(),
    }
}

fn primitive(p: &PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::Bool => "Bool",
        PrimitiveType::F32 | PrimitiveType::F64 => "Float",
        _ => "Int",
    }
}

fn gleam_module_name(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}

fn nif_module_name(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}
