use alef_codegen::type_mapper::TypeMapper;
use alef_core::backend::{Backend, BuildConfig, BuildDependency, Capabilities, GeneratedFile};
use alef_core::config::{AlefConfig, Language, TraitBridgeConfig, resolve_output_dir};
use alef_core::ir::{ApiSurface, EnumDef, ErrorDef, FieldDef, FunctionDef, ParamDef, TypeDef, TypeRef};
use std::collections::BTreeSet;
use std::path::PathBuf;

use crate::type_map::GleamMapper;

pub struct GleamBackend;

impl Backend for GleamBackend {
    fn name(&self) -> &str {
        "gleam"
    }

    fn language(&self) -> Language {
        Language::Gleam
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: false,
            supports_classes: false,
            supports_enums: true,
            supports_option: true,
            supports_result: true,
            supports_callbacks: false,
            supports_streaming: false,
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let module_name = gleam_module_name(&config.crate_config.name);
        let nif_module = config.gleam_nif_module();

        let exclude_functions: std::collections::HashSet<&str> = config
            .gleam
            .as_ref()
            .map(|c| c.exclude_functions.iter().map(String::as_str).collect())
            .unwrap_or_default();
        let exclude_types: std::collections::HashSet<&str> = config
            .gleam
            .as_ref()
            .map(|c| c.exclude_types.iter().map(String::as_str).collect())
            .unwrap_or_default();

        let mut imports: BTreeSet<&'static str> = BTreeSet::new();
        let mut body = String::new();

        for ty in api.types.iter().filter(|t| !exclude_types.contains(t.name.as_str())) {
            emit_type(ty, &mut body, &mut imports);
            body.push('\n');
        }

        // Gleam requires constructor names to be unique module-wide. Build a set of
        // all variant names that appear more than once across enums + error types,
        // and prefix those (and only those) with their parent type name.
        let mut variant_counts: std::collections::HashMap<String, usize> =
            std::collections::HashMap::new();
        for en in &api.enums {
            for v in &en.variants {
                *variant_counts.entry(v.name.clone()).or_insert(0) += 1;
            }
        }
        for err in &api.errors {
            for v in &err.variants {
                *variant_counts.entry(v.name.clone()).or_insert(0) += 1;
            }
        }
        // Also flag variants whose name collides with an existing top-level type.
        for ty in &api.types {
            *variant_counts.entry(ty.name.clone()).or_insert(0) += 1;
        }
        let collisions: std::collections::HashSet<String> = variant_counts
            .into_iter()
            .filter_map(|(n, c)| if c > 1 { Some(n) } else { None })
            .collect();

        for en in api.enums.iter().filter(|e| !exclude_types.contains(e.name.as_str())) {
            emit_enum(en, &collisions, &mut body, &mut imports);
            body.push('\n');
        }

        for err in &api.errors {
            emit_error_type(err, &collisions, &mut body, &mut imports);
            body.push('\n');
        }

        let declared_errors: Vec<String> = api.errors.iter().map(|e| e.name.clone()).collect();
        for f in api.functions.iter().filter(|f| !exclude_functions.contains(f.name.as_str())) {
            emit_function(f, &nif_module, &declared_errors, &mut body, &mut imports);
            body.push('\n');
        }

        // Emit trait bridge shims for each configured bridge not excluded from Gleam.
        let active_bridges: Vec<&TraitBridgeConfig> = config
            .trait_bridges
            .iter()
            .filter(|b| !b.exclude_languages.iter().any(|l| l == "gleam"))
            .collect();

        let mut support_nifs_emitted = false;
        for bridge_cfg in &active_bridges {
            let trait_type = api.types.iter().find(|t| t.is_trait && t.name == bridge_cfg.trait_name);
            emit_trait_bridge_shims(bridge_cfg, trait_type, &nif_module, &mut body, &mut imports);
            body.push('\n');

            if !support_nifs_emitted {
                emit_trait_support_nifs(&nif_module, &mut body);
                support_nifs_emitted = true;
            }
        }

        let mut content = String::new();
        content.push_str("// Generated by alef. Do not edit by hand.\n\n");
        for import in &imports {
            content.push_str(import);
            content.push('\n');
        }
        if !imports.is_empty() {
            content.push('\n');
        }
        content.push_str(&body);

        let dir = resolve_output_dir(None, &config.crate_config.name, "packages/gleam/src");
        let path = PathBuf::from(dir).join(format!("{module_name}.gleam"));

        Ok(vec![GeneratedFile {
            path,
            content,
            generated_header: false,
        }])
    }

    fn build_config(&self) -> Option<BuildConfig> {
        Some(BuildConfig {
            tool: "gleam",
            crate_suffix: "",
            build_dep: BuildDependency::Rustler,
            post_build: vec![],
        })
    }
}

fn emit_type(ty: &TypeDef, out: &mut String, imports: &mut BTreeSet<&'static str>) {
    if !ty.doc.is_empty() {
        for line in ty.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    if ty.fields.is_empty() {
        // Opaque or unit-like — emit a phantom external type
        out.push_str(&format!("pub type {} {{\n  {}\n}}\n", ty.name, ty.name));
        return;
    }
    out.push_str(&format!("pub type {} {{\n  {}(\n", ty.name, ty.name));
    for (idx, field) in ty.fields.iter().enumerate() {
        let ty_str = gleam_type(&field.ty, field.optional, imports);
        let comma = if idx + 1 == ty.fields.len() { "" } else { "," };
        out.push_str(&format!("    {}: {}{}\n", field.name, ty_str, comma));
    }
    out.push_str("  )\n}\n");
}

/// Returns true if a field name represents a positional (tuple) field such as `_0`, `_1`, etc.
/// Gleam constructor arguments do not support labels starting with `_` or numeric labels,
/// so tuple fields must be emitted without a label.
fn is_positional_field(name: &str) -> bool {
    name.starts_with('_') && name[1..].parse::<usize>().is_ok()
}

fn emit_variant_fields(
    fields: &[FieldDef],
    out: &mut String,
    imports: &mut BTreeSet<&'static str>,
) {
    for (idx, field) in fields.iter().enumerate() {
        let ty_str = gleam_type(&field.ty, field.optional, imports);
        let comma = if idx + 1 == fields.len() { "" } else { "," };
        if is_positional_field(&field.name) || field.name.is_empty() {
            // Tuple/positional field: emit as unlabeled argument (e.g. `String`)
            out.push_str(&format!("    {ty_str}{comma}\n"));
        } else {
            out.push_str(&format!("    {}: {ty_str}{comma}\n", field.name));
        }
    }
}

/// Resolve a variant name within its parent type. If the variant name is also
/// used by another type's variant in the same module (Gleam requires unique
/// constructor names module-wide), prefix it with the parent type name.
fn variant_constructor_name(
    parent_type: &str,
    variant_name: &str,
    collisions: &std::collections::HashSet<String>,
) -> String {
    if collisions.contains(variant_name) {
        format!("{parent_type}{variant_name}")
    } else {
        variant_name.to_string()
    }
}

fn emit_enum(en: &EnumDef, collisions: &std::collections::HashSet<String>, out: &mut String, imports: &mut BTreeSet<&'static str>) {
    if !en.doc.is_empty() {
        for line in en.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!("pub type {} {{\n", en.name));
    for variant in &en.variants {
        let ctor = variant_constructor_name(&en.name, &variant.name, collisions);
        if variant.fields.is_empty() {
            out.push_str(&format!("  {ctor}\n"));
        } else {
            out.push_str(&format!("  {ctor}(\n"));
            emit_variant_fields(&variant.fields, out, imports);
            out.push_str("  )\n");
        }
    }
    out.push_str("}\n");
}

fn emit_error_type(err: &ErrorDef, collisions: &std::collections::HashSet<String>, out: &mut String, imports: &mut BTreeSet<&'static str>) {
    if !err.doc.is_empty() {
        for line in err.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!("pub type {} {{\n", err.name));
    for variant in &err.variants {
        let ctor = variant_constructor_name(&err.name, &variant.name, collisions);
        if variant.fields.is_empty() {
            out.push_str(&format!("  {ctor}\n"));
        } else {
            out.push_str(&format!("  {ctor}(\n"));
            emit_variant_fields(&variant.fields, out, imports);
            out.push_str("  )\n");
        }
    }
    out.push_str("}\n");
}

fn emit_function(
    f: &FunctionDef,
    nif_module: &str,
    declared_errors: &[String],
    out: &mut String,
    imports: &mut BTreeSet<&'static str>,
) {
    if !f.doc.is_empty() {
        for line in f.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    use heck::ToSnakeCase;
    out.push_str(&format!("@external(erlang, \"{nif_module}\", \"{}\")\n", f.name));
    out.push_str(&format!("pub fn {}(", f.name.to_snake_case()));
    let params: Vec<String> = f.params.iter().map(|p| format_param(p, imports)).collect();
    out.push_str(&params.join(", "));
    out.push(')');

    let return_ty = gleam_type(&f.return_type, false, imports);
    let return_str = if let Some(err_ty) = &f.error_type {
        let resolved = resolve_gleam_error_type(err_ty, declared_errors);
        format!("Result({return_ty}, {resolved})")
    } else {
        return_ty
    };
    out.push_str(&format!(" -> {return_str}\n"));
}

/// Map a Rust error type string (e.g. `"anyhow::Error"`, `"KreuzbergError"`)
/// to a Gleam type identifier. Gleam type names cannot contain `::`. If the
/// path's last segment matches a declared error type, use it; otherwise fall
/// back to the first declared error type, or `String` if none are declared.
fn resolve_gleam_error_type(error_type: &str, declared: &[String]) -> String {
    let last = error_type.rsplit("::").next().unwrap_or(error_type);
    if declared.iter().any(|d| d == last) {
        return last.to_string();
    }
    declared.first().cloned().unwrap_or_else(|| "String".to_string())
}

fn format_param(p: &ParamDef, imports: &mut BTreeSet<&'static str>) -> String {
    let ty_str = gleam_type(&p.ty, p.optional, imports);
    format!("{}: {}", p.name, ty_str)
}

fn gleam_type(ty: &TypeRef, optional: bool, imports: &mut BTreeSet<&'static str>) -> String {
    let mapper = GleamMapper;
    let inner = render_type_ref_with_imports(ty, imports, &mapper);
    if optional {
        imports.insert("import gleam/option.{type Option}");
        format!("Option({inner})")
    } else {
        inner
    }
}

fn render_type_ref_with_imports(ty: &TypeRef, imports: &mut BTreeSet<&'static str>, mapper: &GleamMapper) -> String {
    match ty {
        TypeRef::Optional(inner) => {
            imports.insert("import gleam/option.{type Option}");
            format!("Option({})", render_type_ref_with_imports(inner, imports, mapper))
        }
        TypeRef::Vec(inner) => {
            format!("List({})", render_type_ref_with_imports(inner, imports, mapper))
        }
        TypeRef::Map(k, v) => {
            imports.insert("import gleam/dict.{type Dict}");
            format!(
                "Dict({}, {})",
                render_type_ref_with_imports(k, imports, mapper),
                render_type_ref_with_imports(v, imports, mapper)
            )
        }
        _ => mapper.map_type(ty),
    }
}

fn gleam_module_name(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}

/// Emit Gleam shim functions for a single trait bridge.
///
/// Emits:
/// - A documentation comment explaining the trait bridge and scope cap.
/// - A `register_<trait_snake>` pub fn calling the Rustler NIF registration function
///   (when `register_fn` is configured).
///
/// Scope cap: real callback round-trips require the Gleam/Elixir module to implement
/// a GenServer `handle_info/2` that responds to `{:trait_call, method, args_json, reply_id}`
/// messages and calls `complete_trait_call/2` or `fail_trait_call/2` when done.
/// Gleam emits these function shims; users wire their callback module via the existing
/// Elixir/Rustler GenServer registration pattern.
fn emit_trait_bridge_shims(
    bridge_cfg: &TraitBridgeConfig,
    trait_type: Option<&TypeDef>,
    nif_module: &str,
    out: &mut String,
    imports: &mut BTreeSet<&'static str>,
) {
    use heck::ToSnakeCase;

    let trait_name = &bridge_cfg.trait_name;
    let trait_snake = trait_name.to_snake_case();

    // Documentation comment
    out.push_str(&format!("/// Trait bridge shims for `{trait_name}`.\n"));
    out.push_str("///\n");
    if let Some(ty) = trait_type {
        if !ty.doc.is_empty() {
            for line in ty.doc.lines() {
                out.push_str("/// ");
                out.push_str(line);
                out.push('\n');
            }
            out.push_str("///\n");
        }
    }
    out.push_str(
        "/// # Scope cap\n\
         ///\n\
         /// Real callback round-trips require the caller to register a GenServer PID\n\
         /// that implements `handle_info/2` to handle\n\
         /// `{:trait_call, method, args_json, reply_id}` messages and then calls\n\
         /// `complete_trait_call` or `fail_trait_call` with the reply.\n\
         /// Gleam emits the registration and reply shims here; wiring the callback\n\
         /// module is done via the Elixir/Rustler side (existing GenServer pattern).\n",
    );

    // Registration function — only when register_fn is configured.
    // The PID is passed as Dynamic because Gleam's type system does not have a native
    // Pid type; Dynamic lets callers pass the Erlang PID term directly.
    if let Some(register_fn) = bridge_cfg.register_fn.as_deref() {
        imports.insert("import gleam/dynamic.{type Dynamic}");
        out.push_str(&format!(
            "@external(erlang, \"{nif_module}\", \"{register_fn}\")\n"
        ));
        out.push_str(&format!(
            "pub fn register_{trait_snake}(pid: Dynamic, plugin_name: String) -> Nil\n"
        ));
    }
}

/// Emit the shared `complete_trait_call` and `fail_trait_call` support NIF shims.
///
/// These are emitted once per module regardless of how many bridges are active,
/// because the Rustler side registers them as module-level NIFs used by all bridges.
fn emit_trait_support_nifs(nif_module: &str, out: &mut String) {
    out.push_str("/// Complete a pending trait call with a successful JSON result.\n");
    out.push_str("/// Call this from your GenServer after processing a trait_call message.\n");
    out.push_str(&format!(
        "@external(erlang, \"{nif_module}\", \"complete_trait_call\")\n"
    ));
    out.push_str("pub fn complete_trait_call(reply_id: Int, result_json: String) -> Nil\n");
    out.push('\n');

    out.push_str("/// Fail a pending trait call with an error message.\n");
    out.push_str("/// Call this from your GenServer when processing a trait_call message fails.\n");
    out.push_str(&format!(
        "@external(erlang, \"{nif_module}\", \"fail_trait_call\")\n"
    ));
    out.push_str("pub fn fail_trait_call(reply_id: Int, error_message: String) -> Nil\n");
    out.push('\n');
}
