// Generated by alef. Do not edit by hand — this file is the codegen for codegen.
use alef_codegen::generators::type_paths::build_type_path_lookup;
use alef_core::backend::GeneratedFile;
use alef_core::config::{AlefConfig, resolve_output_dir};
use alef_core::ir::{ApiSurface, EnumDef, FunctionDef, MethodDef, PrimitiveType, TypeDef, TypeRef};
use alef_core::template_versions::cargo as tv;
use heck::ToSnakeCase;
use std::path::PathBuf;

/// Emit the Rust-side flutter_rust_bridge bridge crate for the given API surface.
///
/// Returns four files that together form the `packages/dart/rust/` crate:
/// - `packages/dart/rust/Cargo.toml`
/// - `packages/dart/rust/src/lib.rs`
/// - `packages/dart/rust/build.rs`
/// - `packages/dart/rust/flutter_rust_bridge.yaml`
pub fn emit(api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
    let rust_dir = resolve_output_dir(None, &config.crate_config.name, "packages/dart/rust");
    let module_name = dart_module_name(&config.crate_config.name);
    let source_crate_name = config.crate_config.name.replace('-', "_");

    let exclude_functions: std::collections::HashSet<String> = config
        .dart
        .as_ref()
        .map(|c| c.exclude_functions.iter().cloned().collect())
        .unwrap_or_default();
    let exclude_types: std::collections::HashSet<String> = config
        .dart
        .as_ref()
        .map(|c| c.exclude_types.iter().cloned().collect())
        .unwrap_or_default();

    Ok(vec![
        emit_cargo_toml(&rust_dir, api, config, &source_crate_name),
        emit_lib_rs(&rust_dir, api, config, &source_crate_name, &exclude_functions, &exclude_types),
        emit_build_rs(&rust_dir),
        emit_frb_yaml(&rust_dir, &module_name),
    ])
}

fn emit_cargo_toml(rust_dir: &str, api: &ApiSurface, config: &AlefConfig, source_crate_name: &str) -> GeneratedFile {
    let crate_name = config.crate_config.name.as_str();
    let version = &api_version(config);
    let frb_version = tv::FLUTTER_RUST_BRIDGE;
    let core_crate_dir = config.core_crate_dir();
    let same_as_workspace = core_crate_dir == *crate_name && config.crate_config.workspace_root.is_none();
    let core_path = if same_as_workspace {
        "../../..".to_string()
    } else {
        format!("../../../crates/{core_crate_dir}")
    };

    let features = config.features_for_language(alef_core::config::extras::Language::Dart);
    let features_block = if features.is_empty() {
        String::new()
    } else {
        let list = features
            .iter()
            .map(|f| format!("\"{f}\""))
            .collect::<Vec<_>>()
            .join(", ");
        format!(", features = [{list}]")
    };

    // Trait bridge impl methods use tokio::runtime::Handle::current().block_on(...),
    // anyhow for error conversion, and async-trait for async trait impls.
    // Add these dependencies only when trait bridges are configured and emitted.
    let has_trait_bridges = config.trait_bridges.iter().any(|b| {
        !b.exclude_languages.iter().any(|l| l == "dart")
            && api.types.iter().any(|t| t.name == b.trait_name && t.is_trait)
    });
    let extra_deps = if has_trait_bridges {
        "tokio = { version = \"1\", features = [\"rt\"] }\nanyhow = \"1\"\nasync-trait = \"0.1\"\n"
    } else {
        ""
    };

    let content = format!(
        r#"[package]
name = "{crate_name}-dart"
version = "{version}"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
{source_crate_name} = {{ path = "{core_path}"{features_block} }}
flutter_rust_bridge = "{frb_version}"
serde_json = "1"
{extra_deps}
[lints.rust]
# flutter_rust_bridge uses #[cfg(frb_expand)] internally during macro expansion.
# Declare it as a known cfg so rustc does not emit unexpected_cfgs warnings.
unexpected_cfgs = {{ level = "warn", check-cfg = ['cfg(frb_expand)'] }}"#
    );

    GeneratedFile {
        path: PathBuf::from(rust_dir).join("Cargo.toml"),
        content,
        generated_header: false,
    }
}

fn build_type_path_lookup_for_source(api: &ApiSurface, source_crate_name: &str) -> std::collections::HashMap<String, String> {
    let _ = source_crate_name;
    build_type_path_lookup(api)
}

fn emit_lib_rs(
    rust_dir: &str,
    api: &ApiSurface,
    config: &AlefConfig,
    source_crate_name: &str,
    exclude_functions: &std::collections::HashSet<String>,
    exclude_types: &std::collections::HashSet<String>,
) -> GeneratedFile {
    let mut content = String::new();
    // batch_extract_bytes* functions use unimplemented!() for the items argument,
    // making the `config` parameter appear unreachable to rustc. Suppress the
    // resulting unused-variable and unreachable-code noise crate-wide; all other
    // functions use every parameter they declare and have reachable code paths.
    content.push_str("// Generated by alef. Do not edit by hand.\n");
    content.push_str("#![allow(unused_variables, unreachable_code)]\n");
    content.push_str("use flutter_rust_bridge::frb;\n");

    for ty in api.types.iter().filter(|t| !exclude_types.contains(&t.name) && !t.is_trait) {
        content.push('\n');
        emit_mirror_struct(&mut content, ty);
    }

    for en in api.enums.iter().filter(|e| !exclude_types.contains(&e.name)) {
        content.push('\n');
        emit_mirror_enum(&mut content, en);
    }

    let type_paths = build_type_path_lookup_for_source(api, source_crate_name);
    for f in api.functions.iter().filter(|f| !exclude_functions.contains(&f.name)) {
        content.push('\n');
        emit_bridge_fn(&mut content, f, source_crate_name, &type_paths);
    }

    // Emit FRB trait bridge wrappers for each configured [[trait_bridges]] entry.
    // The Dart-side wiring (implementing the abstract class in Dart) is post-FRB-codegen-runtime
    // work — only the Rust side is generated here. The generated Rust code uses
    // DartFnFuture<T> callbacks from flutter_rust_bridge for async-to-sync bridging.
    let dart_backend_name = "dart";
    for bridge_cfg in &config.trait_bridges {
        if bridge_cfg.exclude_languages.iter().any(|l| l == dart_backend_name) {
            continue;
        }
        if let Some(trait_def) = api.types.iter().find(|t| t.name == bridge_cfg.trait_name && t.is_trait) {
            content.push('\n');
            emit_trait_bridge(&mut content, trait_def, api, source_crate_name, &type_paths);
        }
    }

    GeneratedFile {
        path: PathBuf::from(rust_dir).join("src/lib.rs"),
        content,
        generated_header: false,
    }
}

fn emit_build_rs(rust_dir: &str) -> GeneratedFile {
    let content = "fn main() {\n    // FRB codegen runs as a separate command (`flutter_rust_bridge_codegen generate`).\n    // This build.rs is a placeholder for any pre-build steps.\n}\n".to_string();
    GeneratedFile {
        path: PathBuf::from(rust_dir).join("build.rs"),
        content,
        generated_header: false,
    }
}

fn emit_frb_yaml(rust_dir: &str, module_name: &str) -> GeneratedFile {
    // FRB v2 schema: `rust_root` points at the Rust crate dir (not a single file)
    // and `dart_output` is the directory where Dart bindings are written. The v1
    // `rust_input` / `rust_output` keys were removed in v2.
    let content = format!(
        "rust_root: .\ndart_output: ../lib/src/{module_name}_bridge_generated\n"
    );
    GeneratedFile {
        path: PathBuf::from(rust_dir).join("flutter_rust_bridge.yaml"),
        content,
        generated_header: false,
    }
}

fn emit_mirror_struct(out: &mut String, ty: &TypeDef) {
    // FRB v2 mirror convention: the mirror struct keeps the same name as the
    // original; the `mirror` attribute argument tells FRB which type this
    // declaration shadows for codegen purposes.
    out.push_str(&format!("#[frb(mirror({name}))]\n", name = ty.name));
    out.push_str(&format!("pub struct {} {{\n", ty.name));
    for field in &ty.fields {
        let rust_ty = frb_rust_type(&field.ty, field.optional);
        out.push_str(&format!("    pub {}: {rust_ty},\n", field.name));
    }
    out.push_str("}\n");
}

fn emit_mirror_enum(out: &mut String, en: &EnumDef) {
    let all_unit = en.variants.iter().all(|v| v.fields.is_empty());
    out.push_str(&format!("#[frb(mirror({name}))]\n", name = en.name));
    if all_unit {
        out.push_str(&format!("pub enum {} {{\n", en.name));
        for variant in &en.variants {
            out.push_str(&format!("    {},\n", variant.name));
        }
        out.push_str("}\n");
    } else {
        out.push_str(&format!("pub enum {} {{\n", en.name));
        for variant in &en.variants {
            if variant.fields.is_empty() {
                out.push_str(&format!("    {},\n", variant.name));
            } else {
                out.push_str(&format!("    {} {{\n", variant.name));
                for (idx, f) in variant.fields.iter().enumerate() {
                    let fname = if f.name.is_empty() {
                        format!("field{idx}")
                    } else {
                        f.name.clone()
                    };
                    let rust_ty = frb_rust_type(&f.ty, false);
                    out.push_str(&format!("        {fname}: {rust_ty},\n"));
                }
                out.push_str("    },\n");
            }
        }
        out.push_str("}\n");
    }
}

fn emit_bridge_fn(
    out: &mut String,
    f: &FunctionDef,
    source_crate_name: &str,
    type_paths: &std::collections::HashMap<String, String>,
) {
    // FRB v2: ordinary public functions need no annotation. A bare `#[frb]`
    // with no arguments is rejected by the macro. Don't emit it.
    let fn_name = &f.name;
    let async_kw = if f.is_async { "async " } else { "" };

    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| {
            // Use the source-crate type for Named types so the bridge fn passes
            // them straight through to the underlying Rust API. The `#[frb(mirror(T))]`
            // attribute on the mirror struct tells FRB that the local declaration
            // is layout-identical to the source type — FRB substitutes them on the
            // Dart side but the generated Rust code must still pass the original.
            let rust_ty = frb_rust_type_with_source(&p.ty, p.optional, source_crate_name, type_paths);
            format!("{}: {rust_ty}", p.name)
        })
        .collect();

    // For each parameter, build the call-site expression. The IR records whether
    // the underlying Rust function takes the value by reference (`is_ref`) and
    // the original concrete type (`original_type`). FRB widens primitives to
    // i64/f64 and Strings to `String`, but the source function may want `u16`,
    // `usize`, `&Path`, etc. — emit a cast (`as Foo`) or conversion call.
    let call_args: Vec<String> = f
        .params
        .iter()
        .map(|p| dart_call_arg(p))
        .collect();

    let has_error = f.error_type.is_some();
    let return_ty = if has_error {
        format!("Result<{}, String>", frb_rust_type_with_source(&f.return_type, false, source_crate_name, type_paths))
    } else {
        frb_rust_type_with_source(&f.return_type, false, source_crate_name, type_paths)
    };

    out.push_str(&format!(
        "pub {async_kw}fn {fn_name}({}) -> {return_ty} {{\n",
        params.join(", ")
    ));

    // Resolve the call target via the IR's full rust_path, falling back to the
    // backend's bare fn name if rust_path is empty. This matches alef-backend-ffi
    // and ensures functions defined in submodules (e.g. `my_lib::utils::helper`)
    // generate correct shim calls.
    let resolved_path = if f.rust_path.is_empty() {
        format!("{source_crate_name}::{fn_name}")
    } else {
        f.rust_path.replace('-', "_")
    };
    let call = format!("{resolved_path}({})", call_args.join(", "));

    // Handle return-type mismatches: FRB widens primitives but the source fn
    // may return e.g. `u64` or `&str`. Bridge with explicit conversions.
    let result_cast = match &f.return_type {
        TypeRef::Primitive(_) => {
            let target = frb_rust_type_inner(&f.return_type);
            format!(" as {target}")
        }
        // String/Path/Char returns may be `&str`/`&Path`/`&Path` from the source;
        // call .to_string() to ensure an owned String is returned.
        TypeRef::String | TypeRef::Path | TypeRef::Char => ".to_string()".to_string(),
        // Optional<String> with returns_ref=true is alef's fallback for
        // `Option<&'static T>` where T is a non-String type (like EmbeddingPreset).
        // Use Debug format so the Dart side gets a printable representation —
        // `serde_json::to_string` would require T: Serialize which isn't always true.
        TypeRef::Optional(inner)
            if matches!(inner.as_ref(), TypeRef::String | TypeRef::Path | TypeRef::Char) && f.returns_ref =>
        {
            ".map(|v| format!(\"{:?}\", v))".to_string()
        }
        TypeRef::Vec(inner) => match inner.as_ref() {
            TypeRef::Primitive(prim) => {
                let target = primitive_name(prim);
                if target == "f64" || target == "i64" || target == "bool" {
                    String::new()
                } else {
                    format!(".into_iter().map(|x| x as {}).collect::<Vec<_>>()", frb_rust_type_inner(inner))
                }
            }
            // Vec<&str> -> Vec<String>
            TypeRef::String | TypeRef::Path | TypeRef::Char => {
                ".into_iter().map(|s| s.to_string()).collect::<Vec<_>>()".to_string()
            }
            _ => String::new(),
        },
        TypeRef::Optional(inner) => match inner.as_ref() {
            TypeRef::String | TypeRef::Path | TypeRef::Char => ".map(|s| s.to_string())".to_string(),
            _ => String::new(),
        },
        _ => String::new(),
    };

    let body = if has_error {
        if f.is_async {
            format!("    {call}.await.map(|v| v{result_cast}).map_err(|e| e.to_string())\n")
        } else {
            format!("    {call}.map(|v| v{result_cast}).map_err(|e| e.to_string())\n")
        }
    } else if f.is_async {
        if result_cast.is_empty() {
            format!("    {call}.await\n")
        } else {
            format!("    {call}.await{result_cast}\n")
        }
    } else if result_cast.is_empty() {
        format!("    {call}\n")
    } else {
        format!("    {call}{result_cast}\n")
    };

    out.push_str(&body);
    out.push_str("}\n");
}

/// Emit a FRB trait bridge for one configured trait.
///
/// Produces the following items in the lib.rs:
///
/// 1. `#[frb(opaque)] pub struct {Trait}DartImpl` — holds one `Box<dyn Fn(...)
///    -> DartFnFuture<ret> + Send + Sync>` closure per own method. If the trait
///    has a `Plugin` super-trait, also holds `plugin_name: String` and
///    `plugin_version: String` fields.
/// 2. `impl SuperTrait for {Trait}DartImpl` — for each super-trait in `super_traits`,
///    emits a stub impl. The well-known `Plugin` super-trait is handled directly;
///    other super-traits emit a `// TODO` comment stub.
/// 3. `impl {Trait} for {Trait}DartImpl` — delegates each method to its closure.
/// 4. `pub fn create_{trait_snake}_dart_impl(...)` — factory function.
///
/// Dart-side wiring (`class MyOcrBackend implements OcrBackend { ... }`) is
/// post-FRB-codegen-runtime work and is NOT generated here.
fn emit_trait_bridge(
    out: &mut String,
    trait_def: &TypeDef,
    api: &ApiSurface,
    source_crate_name: &str,
    type_paths: &std::collections::HashMap<String, String>,
) {
    let trait_name = &trait_def.name;
    let trait_snake = trait_name.to_snake_case();
    let struct_name = format!("{trait_name}DartImpl");
    let trait_path = if trait_def.rust_path.is_empty() {
        format!("{source_crate_name}::{trait_name}")
    } else {
        trait_def.rust_path.replace('-', "_")
    };

    // Filter to only own methods (no super-trait inherited ones).
    let own_methods: Vec<&MethodDef> = trait_def
        .methods
        .iter()
        .filter(|m| m.trait_source.is_none())
        .collect();

    // Check if Plugin is a direct super-trait.
    let has_plugin_super = trait_def.super_traits.iter().any(|s| s == "Plugin" || s.ends_with("::Plugin"));

    // --- 1. Opaque struct with one closure field per method ---
    out.push_str("/// FRB opaque handle holding Dart callbacks for each trait method.\n");
    out.push_str("/// Dart-side: register callbacks via `create_{snake}_dart_impl(...)` factory.\n");
    out.push_str("#[frb(opaque)]\n");
    out.push_str(&format!("pub struct {struct_name} {{\n"));
    // Plugin fields for name/version (required by Plugin super-trait).
    if has_plugin_super {
        out.push_str("    /// Plugin name used by the Plugin super-trait impl.\n");
        out.push_str("    plugin_name: String,\n");
        out.push_str("    /// Plugin version used by the Plugin super-trait impl.\n");
        out.push_str("    plugin_version: String,\n");
    }
    for method in &own_methods {
        let field_name = &method.name;
        let callback_ty = dart_fn_future_callback_type(method, source_crate_name, type_paths);
        out.push_str(&format!("    {field_name}: {callback_ty},\n"));
    }
    out.push_str("}\n");
    out.push('\n');

    // --- 2. impl Plugin for Struct (super-trait) ---
    if has_plugin_super {
        // Find Plugin trait def to get its rust_path.
        let plugin_path = api
            .types
            .iter()
            .find(|t| t.is_trait && (t.name == "Plugin" || t.name.ends_with("::Plugin")))
            .map(|t| t.rust_path.replace('-', "_"))
            .unwrap_or_else(|| format!("{source_crate_name}::plugins::Plugin"));

        out.push_str(&format!("impl {plugin_path} for {struct_name} {{\n"));
        out.push_str("    fn name(&self) -> &str {\n");
        out.push_str("        &self.plugin_name\n");
        out.push_str("    }\n");
        out.push('\n');
        out.push_str("    fn version(&self) -> String {\n");
        out.push_str("        self.plugin_version.clone()\n");
        out.push_str("    }\n");
        out.push('\n');
        out.push_str(&format!(
            "    fn initialize(&self) -> {source_crate_name}::Result<()> {{\n"
        ));
        out.push_str("        Ok(())\n");
        out.push_str("    }\n");
        out.push('\n');
        out.push_str(&format!(
            "    fn shutdown(&self) -> {source_crate_name}::Result<()> {{\n"
        ));
        out.push_str("        Ok(())\n");
        out.push_str("    }\n");
        out.push_str("}\n");
        out.push('\n');
    }

    // --- 3. impl Trait for Struct ---
    // async_trait macro is required for async methods in trait impls.
    let has_async = own_methods.iter().any(|m| m.is_async);
    if has_async {
        out.push_str("#[async_trait::async_trait]\n");
    }
    out.push_str(&format!("impl {trait_path} for {struct_name} {{\n"));
    for method in &own_methods {
        emit_trait_bridge_method(out, method, source_crate_name, type_paths);
        out.push('\n');
    }
    out.push_str("}\n");
    out.push('\n');

    // --- 4. Factory function ---
    out.push_str(&format!("/// Create a `{struct_name}` from Dart callback closures.\n"));
    out.push_str("/// Each method parameter is a `DartFnFuture`-returning closure.\n");
    if has_plugin_super {
        out.push_str("/// `plugin_name` and `plugin_version` are required for the Plugin super-trait.\n");
    }
    out.push_str(&format!("pub fn create_{trait_snake}_dart_impl(\n"));
    if has_plugin_super {
        out.push_str("    plugin_name: String,\n");
        out.push_str("    plugin_version: String,\n");
    }
    for method in &own_methods {
        let param_name = &method.name;
        let callback_ty = dart_fn_future_callback_type(method, source_crate_name, type_paths);
        out.push_str(&format!("    {param_name}: {callback_ty},\n"));
    }
    out.push_str(&format!(") -> {struct_name} {{\n"));
    out.push_str(&format!("    {struct_name} {{\n"));
    if has_plugin_super {
        out.push_str("        plugin_name,\n");
        out.push_str("        plugin_version,\n");
    }
    for method in &own_methods {
        out.push_str(&format!("        {},\n", method.name));
    }
    out.push_str("    }\n");
    out.push_str("}\n");
}

/// Build the callback closure type stored in the bridge struct field.
///
/// Closures always accept **owned** FRB-friendly types (the Dart FFI layer passes
/// owned values). Reference parameters in the original trait are converted to owned
/// before the closure is invoked. Returns a `DartFnFuture<T>` wrapping the
/// FRB-friendly return type.
///
/// Example: `Box<dyn Fn(Vec<u8>, OcrConfig) -> DartFnFuture<ExtractionResult> + Send + Sync>`
fn dart_fn_future_callback_type(
    method: &MethodDef,
    source_crate_name: &str,
    type_paths: &std::collections::HashMap<String, String>,
) -> String {
    // Closures take owned FRB-friendly types — strip any reference wrappers.
    let params: Vec<String> = method
        .params
        .iter()
        .map(|p| frb_rust_type_with_source(&p.ty, p.optional, source_crate_name, type_paths))
        .collect();

    let ret = frb_rust_type_with_source(&method.return_type, false, source_crate_name, type_paths);
    let dart_fn_ret = format!("flutter_rust_bridge::DartFnFuture<{ret}>");

    let params_str = params.join(", ");
    format!("Box<dyn Fn({params_str}) -> {dart_fn_ret} + Send + Sync>")
}

/// Emit one method implementation on the bridge struct.
///
/// The method signature must match the **original** trait signature (ref-aware,
/// original primitive widths). The closures stored in the struct hold
/// FRB-friendly widened types (e.g. `i64` for `u64`, `f64` for `f32`). The
/// impl body converts between the two representations.
///
/// For methods with an `error_type`, the return type is
/// `{source_crate}::Result<T>` — the Dart callback never fails, so the body
/// wraps the awaited value in `Ok(...)`.
fn emit_trait_bridge_method(
    out: &mut String,
    method: &MethodDef,
    source_crate_name: &str,
    type_paths: &std::collections::HashMap<String, String>,
) {
    let method_name = &method.name;

    // Build the method signature matching the actual trait.
    // - Reference params use `&` / `&mut` prefix.
    // - Primitive params use their original width (not FRB-widened).
    let params_sig: Vec<String> = std::iter::once("&self".to_string())
        .chain(method.params.iter().map(|p| {
            let orig_ty = trait_impl_param_type(p, source_crate_name, type_paths);
            format!("{}: {orig_ty}", p.name)
        }))
        .collect();

    // Return type: use original primitive/named type; wrap in source-crate Result when error_type set.
    let ret = trait_impl_return_type(&method.return_type, source_crate_name, type_paths);
    let return_sig = if method.error_type.is_some() {
        if matches!(method.return_type, TypeRef::Unit) {
            format!("{source_crate_name}::Result<()>")
        } else {
            format!("{source_crate_name}::Result<{ret}>")
        }
    } else {
        ret.clone()
    };

    let async_kw = if method.is_async { "async " } else { "" };
    let sig_line = format!("    {async_kw}fn {method_name}({}) -> {return_sig} {{", params_sig.join(", "));
    out.push_str(&sig_line);
    out.push('\n');

    // Emit owned-conversion let-bindings for each parameter before calling the closure.
    // References become owned; primitives may be widened; mut refs are copied for the callback.
    for p in &method.params {
        let conv = trait_impl_param_conversion(p);
        if !conv.is_empty() {
            out.push_str(&format!("        {conv}\n"));
        }
    }

    // Build call-site arg list (use the local owned var names).
    let call_args: Vec<String> = method.params.iter().map(|p| {
        // If a conversion was emitted, the local var has the same name.
        p.name.clone()
    }).collect();
    let call_expr = format!("(self.{method_name})({})", call_args.join(", "));

    // Emit the body, adapting the return value from FRB-widened to original type.
    let ret_conv = trait_impl_return_conversion(&method.return_type);

    if method.error_type.is_some() {
        // DartFnFuture never fails: wrap the awaited value in Ok(...).
        if method.is_async {
            if ret_conv.is_empty() {
                out.push_str(&format!("        Ok({call_expr}.await)\n"));
            } else {
                out.push_str(&format!("        Ok({call_expr}.await{ret_conv})\n"));
            }
        } else {
            out.push_str("        let __result = tokio::runtime::Handle::current()\n");
            out.push_str(&format!("            .block_on(async {{ {call_expr}.await }});\n"));
            if ret_conv.is_empty() {
                out.push_str("        Ok(__result)\n");
            } else {
                out.push_str(&format!("        Ok(__result{ret_conv})\n"));
            }
        }
    } else if method.is_async {
        if ret_conv.is_empty() {
            out.push_str(&format!("        {call_expr}.await\n"));
        } else {
            out.push_str(&format!("        ({call_expr}.await){ret_conv}\n"));
        }
    } else {
        out.push_str("        let __result = tokio::runtime::Handle::current()\n");
        out.push_str(&format!("            .block_on(async {{ {call_expr}.await }});\n"));
        if ret_conv.is_empty() {
            out.push_str("        __result\n");
        } else {
            out.push_str(&format!("        __result{ret_conv}\n"));
        }
    }
    out.push_str("    }\n");
}

/// Build the parameter type for the `impl Trait` method signature — must match
/// the original trait exactly (ref, mut-ref, original primitive widths).
fn trait_impl_param_type(
    p: &alef_core::ir::ParamDef,
    source_crate_name: &str,
    type_paths: &std::collections::HashMap<String, String>,
) -> String {
    /// Recursively build the owned (non-ref) Rust type using original widths.
    fn owned_ty(ty: &TypeRef, src: &str, tp: &std::collections::HashMap<String, String>) -> String {
        match ty {
            TypeRef::Bytes => "Vec<u8>".to_string(),
            TypeRef::String | TypeRef::Char => "String".to_string(),
            TypeRef::Path => "std::path::PathBuf".to_string(),
            TypeRef::Primitive(prim) => primitive_name(prim).to_string(),
            TypeRef::Named(name) => match tp.get(name) {
                Some(path) => path.clone(),
                None => format!("{src}::{name}"),
            },
            TypeRef::Vec(inner) => format!("Vec<{}>", owned_ty(inner, src, tp)),
            TypeRef::Optional(inner) => format!("Option<{}>", owned_ty(inner, src, tp)),
            TypeRef::Map(k, v) => format!(
                "std::collections::HashMap<{}, {}>",
                owned_ty(k, src, tp),
                owned_ty(v, src, tp)
            ),
            TypeRef::Unit => "()".to_string(),
            TypeRef::Json => "String".to_string(),
            TypeRef::Duration => "std::time::Duration".to_string(),
        }
    }

    if p.is_ref {
        // Reference parameters: use the slice/ref form for Bytes/Vec, plain ref for others.
        match &p.ty {
            TypeRef::Bytes => {
                if p.is_mut { "&mut [u8]".to_string() } else { "&[u8]".to_string() }
            }
            TypeRef::Vec(inner) => {
                let inner_ty = match inner.as_ref() {
                    TypeRef::Primitive(prim) => primitive_name(prim).to_string(),
                    TypeRef::Named(name) => match type_paths.get(name) {
                        Some(path) => path.clone(),
                        None => format!("{source_crate_name}::{name}"),
                    },
                    _ => frb_rust_type_inner(inner),
                };
                if p.is_mut {
                    format!("&mut [{inner_ty}]")
                } else {
                    format!("&[{inner_ty}]")
                }
            }
            TypeRef::String | TypeRef::Char => {
                if p.is_mut { "&mut String".to_string() } else { "&str".to_string() }
            }
            TypeRef::Path => {
                if p.is_mut { "&mut std::path::Path".to_string() } else { "&std::path::Path".to_string() }
            }
            _ => {
                let base = owned_ty(&p.ty, source_crate_name, type_paths);
                if p.is_mut { format!("&mut {base}") } else { format!("&{base}") }
            }
        }
    } else if p.optional {
        format!("Option<{}>", owned_ty(&p.ty, source_crate_name, type_paths))
    } else {
        owned_ty(&p.ty, source_crate_name, type_paths)
    }
}

/// Build the conversion expression that converts the parameter from its original
/// trait type to the FRB-friendly owned type expected by the DartFnFuture closure.
/// Returns an empty string if no conversion is needed.
fn trait_impl_param_conversion(p: &alef_core::ir::ParamDef) -> String {
    let name = &p.name;
    if p.is_ref {
        match &p.ty {
            TypeRef::Bytes => format!("let {name} = {name}.to_vec();"),
            TypeRef::String | TypeRef::Char => format!("let {name} = {name}.to_string();"),
            TypeRef::Path => {
                // &Path → String for FRB callback
                format!("let {name} = {name}.to_string_lossy().into_owned();")
            }
            TypeRef::Vec(inner) => {
                // &[T] → Vec<T>; inner type may need widening
                let target = frb_rust_type_inner(inner);
                let orig = match inner.as_ref() {
                    TypeRef::Primitive(prim) => primitive_name(prim).to_string(),
                    _ => return format!("let {name} = {name}.to_vec();"),
                };
                if target != orig {
                    // e.g. &[f32] → Vec<f64>
                    format!("let {name} = {name}.iter().map(|x| *x as {target}).collect::<Vec<_>>();")
                } else {
                    format!("let {name} = {name}.to_vec();")
                }
            }
            TypeRef::Named(_) => {
                // &T → T via clone (handles both &T and &mut T — mut ref is cloned anyway)
                if p.is_mut {
                    format!("let {name} = {name}.clone();")
                } else {
                    format!("let {name} = {name}.clone();")
                }
            }
            _ => String::new(),
        }
    } else {
        // Non-ref: primitive widening might be needed for the closure
        if let TypeRef::Primitive(prim) = &p.ty {
            let orig = primitive_name(prim);
            let widened = frb_rust_type_inner(&p.ty);
            if orig != widened {
                return format!("let {name} = {name} as {widened};");
            }
        }
        String::new()
    }
}

/// Build a return-value conversion suffix to transform the FRB-widened return
/// value from the DartFnFuture closure back to the original trait return type.
/// Returns an empty string when no conversion is needed.
fn trait_impl_return_conversion(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Primitive(prim) => {
            let orig = primitive_name(prim);
            let widened = frb_rust_type_inner(ty);
            if orig != widened {
                format!(" as {orig}")
            } else {
                String::new()
            }
        }
        TypeRef::Vec(inner) => {
            if let TypeRef::Vec(inner2) = inner.as_ref() {
                // Vec<Vec<f32>> → Vec<Vec<f64>> widened; convert back
                if let TypeRef::Primitive(prim) = inner2.as_ref() {
                    let orig = primitive_name(prim);
                    let widened = frb_rust_type_inner(inner2);
                    if orig != widened {
                        return format!(
                            ".into_iter().map(|v| v.into_iter().map(|x| x as {orig}).collect()).collect::<Vec<_>>()"
                        );
                    }
                }
                return String::new();
            }
            if let TypeRef::Primitive(prim) = inner.as_ref() {
                let orig = primitive_name(prim);
                let widened = frb_rust_type_inner(inner);
                if orig != widened {
                    return format!(".into_iter().map(|x| x as {orig}).collect::<Vec<_>>()");
                }
            }
            String::new()
        }
        _ => String::new(),
    }
}

/// Return the original Rust type for use in the `impl Trait` return position.
/// Uses the original primitive widths (not FRB-widened).
fn trait_impl_return_type(
    ty: &TypeRef,
    source_crate_name: &str,
    type_paths: &std::collections::HashMap<String, String>,
) -> String {
    match ty {
        TypeRef::Primitive(prim) => primitive_name(prim).to_string(),
        TypeRef::Unit => "()".to_string(),
        TypeRef::String | TypeRef::Char => "String".to_string(),
        TypeRef::Bytes => "Vec<u8>".to_string(),
        TypeRef::Named(name) => match type_paths.get(name) {
            Some(path) => path.clone(),
            None => format!("{source_crate_name}::{name}"),
        },
        TypeRef::Vec(inner) => format!("Vec<{}>", trait_impl_return_type(inner, source_crate_name, type_paths)),
        TypeRef::Optional(inner) => {
            format!("Option<{}>", trait_impl_return_type(inner, source_crate_name, type_paths))
        }
        TypeRef::Map(k, v) => format!(
            "std::collections::HashMap<{}, {}>",
            trait_impl_return_type(k, source_crate_name, type_paths),
            trait_impl_return_type(v, source_crate_name, type_paths),
        ),
        TypeRef::Path => "std::path::PathBuf".to_string(),
        TypeRef::Duration => "std::time::Duration".to_string(),
        TypeRef::Json => "String".to_string(),
    }
}

/// Maps an IR `TypeRef` to the FRB-friendly Rust type string.
/// FRB's primitive ABI: all integers → `i64`, floats → `f64`, strings → `String`.
///
/// NOTE: u64 values above i64::MAX silently wrap to negative on the Dart side
/// because Dart's native `int` is 64-bit signed. Producers of u64-bearing APIs
/// who need the full range should pre-truncate or document the contract.
fn frb_rust_type(ty: &TypeRef, optional: bool) -> String {
    let inner = frb_rust_type_inner(ty);
    if optional { format!("Option<{inner}>") } else { inner }
}

fn frb_rust_type_inner(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Primitive(p) => match p {
            PrimitiveType::Bool => "bool".to_string(),
            PrimitiveType::F32 | PrimitiveType::F64 => "f64".to_string(),
            // All integer widths → i64 (Dart int ↔ Rust i64 FRB primitive ABI)
            _ => "i64".to_string(),
        },
        TypeRef::String | TypeRef::Char => "String".to_string(),
        TypeRef::Bytes => "Vec<u8>".to_string(),
        TypeRef::Optional(inner) => format!("Option<{}>", frb_rust_type_inner(inner)),
        TypeRef::Vec(inner) => format!("Vec<{}>", frb_rust_type_inner(inner)),
        TypeRef::Map(k, v) => {
            format!("std::collections::HashMap<{}, {}>", frb_rust_type_inner(k), frb_rust_type_inner(v))
        }
        TypeRef::Named(name) => name.clone(),
        TypeRef::Path => "String".to_string(),
        TypeRef::Unit => "()".to_string(),
        TypeRef::Json => "String".to_string(),
        TypeRef::Duration => "i64".to_string(),
    }
}

fn primitive_name(prim: &alef_core::ir::PrimitiveType) -> &'static str {
    match prim {
        alef_core::ir::PrimitiveType::Bool => "bool",
        alef_core::ir::PrimitiveType::U8 => "u8",
        alef_core::ir::PrimitiveType::I8 => "i8",
        alef_core::ir::PrimitiveType::U16 => "u16",
        alef_core::ir::PrimitiveType::I16 => "i16",
        alef_core::ir::PrimitiveType::U32 => "u32",
        alef_core::ir::PrimitiveType::I32 => "i32",
        alef_core::ir::PrimitiveType::U64 => "u64",
        alef_core::ir::PrimitiveType::I64 => "i64",
        alef_core::ir::PrimitiveType::Usize => "usize",
        alef_core::ir::PrimitiveType::Isize => "isize",
        alef_core::ir::PrimitiveType::F32 => "f32",
        alef_core::ir::PrimitiveType::F64 => "f64",
    }
}

/// Build the call-site expression for a single parameter. The IR's
/// `original_type` field carries the Rust type the source function expects;
/// when present, we cast/convert the FRB-widened parameter to match.
fn dart_call_arg(p: &alef_core::ir::ParamDef) -> String {
    let name = &p.name;
    let original = p.original_type.as_deref().unwrap_or("");
    // Strip outer `&`, `&mut`, leading whitespace.
    let stripped_orig = original
        .trim()
        .trim_start_matches('&')
        .trim_start_matches("mut ")
        .trim();

    // Tuple parameters: the IR flattens `Vec<(A, B, ...)>` to `Vec<String>`,
    // losing the structural shape. Use `original_type` to spot these and emit
    // adapter logic that reconstructs a sensible default tuple. The IR stores
    // `original_type` as Rust Debug syntax (e.g.
    // `Vec(Named("(PathBuf, Option<FileExtractionConfig>)"))`).
    if !stripped_orig.is_empty() && stripped_orig.starts_with("Vec(") && stripped_orig.contains("Named(\"(") {
        let tuple_inner = stripped_orig
            .find("Named(\"(")
            .and_then(|start| {
                let rest = &stripped_orig[start + 8..]; // past `Named("(`
                rest.find(")\")")
                    .map(|end| rest[..end].trim_end_matches(')').to_string())
            })
            .unwrap_or_default();
        if tuple_inner.starts_with("PathBuf,") || tuple_inner.starts_with("PathBuf ,") {
            return format!(
                "{name}.into_iter().map(|p| (std::path::PathBuf::from(p), None)).collect::<Vec<_>>()"
            );
        }
        if tuple_inner.starts_with("Vec<u8>,") || tuple_inner.starts_with("Vec<u8> ,") {
            return format!("{{ let _ = {name}; ::std::unimplemented!(\"batch_extract_bytes from Dart not yet bridged\") }}");
        }
    }

    // Path: FRB sends String; the source likely wants &Path, PathBuf, or
    // Option<PathBuf>. Emit the conversion that matches `is_ref` and `optional`.
    if matches!(p.ty, alef_core::ir::TypeRef::Path) {
        if p.optional {
            if p.is_ref {
                return format!("{name}.as_ref().map(std::path::Path::new)");
            }
            return format!("{name}.map(std::path::PathBuf::from)");
        }
        if p.is_ref {
            return format!("std::path::Path::new(&{name})");
        }
        return format!("std::path::PathBuf::from({name})");
    }

    // Primitives: FRB widens all integer params to i64 and floats to f64. Cast
    // back to the actual primitive width before forwarding to the source fn.
    if let alef_core::ir::TypeRef::Primitive(prim) = &p.ty {
        let target = primitive_name(prim);
        if target != "i64" && target != "f64" && target != "bool" {
            if p.optional {
                return format!("{name}.map(|v| v as {target})");
            }
            return if p.is_ref {
                format!("&({name} as {target})")
            } else {
                format!("{name} as {target}")
            };
        }
    }

    // Inner-Vec primitive cast: FRB widens Vec<f32> → Vec<f64>; if the source
    // takes &[f32] we need to materialize a temporary cast Vec.
    if let alef_core::ir::TypeRef::Vec(inner) = &p.ty {
        if let alef_core::ir::TypeRef::Primitive(prim) = inner.as_ref() {
            let target = primitive_name(prim);
            if target != "i64" && target != "f64" && target != "bool" {
                if p.optional {
                    if p.is_ref {
                        return format!(
                            "{name}.as_ref().map(|v| v.iter().map(|x| *x as {target}).collect::<Vec<_>>()).as_deref()"
                        );
                    }
                    return format!(
                        "{name}.map(|v| v.into_iter().map(|x| x as {target}).collect::<Vec<_>>())"
                    );
                }
                if p.is_ref {
                    return format!(
                        "{name}.iter().map(|x| *x as {target}).collect::<Vec<_>>().as_slice()"
                    );
                }
                return format!(
                    "{name}.into_iter().map(|x| x as {target}).collect::<Vec<_>>()"
                );
            }
        }
    }

    if !p.is_ref {
        return name.clone();
    }

    match (&p.ty, p.optional) {
        (alef_core::ir::TypeRef::Bytes, false) => format!("&{name}"),
        (alef_core::ir::TypeRef::String | alef_core::ir::TypeRef::Char, false) => format!("&{name}"),
        (alef_core::ir::TypeRef::String | alef_core::ir::TypeRef::Char, true) => format!("{name}.as_deref()"),
        (alef_core::ir::TypeRef::Vec(_), true) => format!("{name}.as_deref()"),
        _ => format!("&{name}"),
    }
}

/// Like `frb_rust_type`, but Named types resolve to their source-crate path
/// so the bridge fn signature uses the original Rust type (the mirror struct
/// is layout-identical via `#[frb(mirror(T))]`).
fn frb_rust_type_with_source(
    ty: &TypeRef,
    optional: bool,
    source_crate: &str,
    type_paths: &std::collections::HashMap<String, String>,
) -> String {
    let inner = frb_rust_type_inner_with_source(ty, source_crate, type_paths);
    if optional { format!("Option<{inner}>") } else { inner }
}

fn frb_rust_type_inner_with_source(
    ty: &TypeRef,
    source_crate: &str,
    type_paths: &std::collections::HashMap<String, String>,
) -> String {
    match ty {
        TypeRef::Named(name) => match type_paths.get(name) {
            Some(path) => path.clone(),
            None => format!("{source_crate}::{name}"),
        },
        TypeRef::Optional(inner) => format!("Option<{}>", frb_rust_type_inner_with_source(inner, source_crate, type_paths)),
        TypeRef::Vec(inner) => format!("Vec<{}>", frb_rust_type_inner_with_source(inner, source_crate, type_paths)),
        TypeRef::Map(k, v) => format!(
            "std::collections::HashMap<{}, {}>",
            frb_rust_type_inner_with_source(k, source_crate, type_paths),
            frb_rust_type_inner_with_source(v, source_crate, type_paths)
        ),
        _ => frb_rust_type_inner(ty),
    }
}

/// Return type of a bridge fn (without Result wrapper).
fn frb_rust_return_type(ty: &TypeRef) -> String {
    frb_rust_type_inner(ty)
}

fn dart_module_name(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}

fn api_version(config: &AlefConfig) -> String {
    // Use explicit version override if set, otherwise fall back to "0.1.0" as a
    // safe default (the real version is resolved from Cargo.toml at publish time).
    config.version.as_deref().unwrap_or("0.1.0").to_string()
}
