use alef_codegen::type_mapper::TypeMapper;
use alef_core::backend::{Backend, BuildConfig, BuildDependency, Capabilities, GeneratedFile, PostBuildStep};
use alef_core::config::{AlefConfig, Language, resolve_output_dir};
use alef_core::ir::{ApiSurface, EnumDef, ErrorDef, FunctionDef, ParamDef, TypeDef, TypeRef};
use heck::ToLowerCamelCase;
use std::collections::BTreeSet;
use std::path::PathBuf;

use crate::gen_rust_crate;
use crate::type_map::DartMapper;

pub struct DartBackend;

impl Backend for DartBackend {
    fn name(&self) -> &str {
        "dart"
    }

    fn language(&self) -> Language {
        Language::Dart
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: true,
            supports_classes: true,
            supports_enums: true,
            supports_option: true,
            supports_result: true,
            supports_callbacks: false,
            supports_streaming: false,
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let module_name = dart_module_name(&config.crate_config.name);

        let mut imports: BTreeSet<String> = BTreeSet::new();
        let mut body = String::new();

        for ty in &api.types {
            emit_type(ty, &mut body, &mut imports);
            body.push('\n');
        }

        for en in &api.enums {
            emit_enum(en, &mut body);
            body.push('\n');
        }

        for error in &api.errors {
            emit_error(error, &mut body, &mut imports);
            body.push('\n');
        }

        if !api.functions.is_empty() {
            let has_async = api.functions.iter().any(|f| f.is_async);
            if has_async {
                imports.insert("import 'dart:async';".to_string());
            }

            let bridge_class = dart_bridge_class_name(&config.crate_config.name);
            body.push_str(&format!("class {bridge_class} {{\n"));
            for f in &api.functions {
                emit_function(f, &mut body, &mut imports);
                body.push('\n');
            }
            body.push_str("}\n");
        }

        let mut content = String::new();
        content.push_str("// Generated by alef. Do not edit by hand.\n\n");
        for import in &imports {
            content.push_str(import);
            content.push('\n');
        }
        if !imports.is_empty() {
            content.push('\n');
        }
        content.push_str(&body);

        let dir = resolve_output_dir(
            None,
            &config.crate_config.name,
            "packages/dart/lib/src",
        );
        let path = PathBuf::from(dir).join(format!("{module_name}.dart"));

        let mut files = vec![GeneratedFile {
            path,
            content,
            generated_header: false,
        }];

        let rust_crate_files = gen_rust_crate::emit(api, config)?;
        files.extend(rust_crate_files);

        Ok(files)
    }

    fn build_config(&self) -> Option<BuildConfig> {
        Some(BuildConfig {
            tool: "cargo",
            crate_suffix: "-dart",
            build_dep: BuildDependency::None,
            post_build: vec![PostBuildStep::RunCommand {
                cmd: "flutter_rust_bridge_codegen",
                args: vec!["generate"],
            }],
        })
    }
}

/// Converts a crate name like `"my-lib"` to snake_case `"my_lib"`.
fn dart_module_name(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}

/// Converts a crate name like `"my-lib"` to `"MyLibBridge"` for the bridge class.
fn dart_bridge_class_name(crate_name: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for ch in crate_name.chars() {
        if ch == '-' || ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out.push_str("Bridge");
    out
}

fn render_type(ty: &TypeRef, imports: &mut BTreeSet<String>) -> String {
    match ty {
        TypeRef::Bytes => {
            imports.insert("import 'dart:typed_data';".to_string());
            DartMapper.map_type(ty)
        }
        TypeRef::Optional(inner) => {
            format!("{}?", render_type(inner, imports))
        }
        TypeRef::Vec(inner) => {
            format!("List<{}>", render_type(inner, imports))
        }
        TypeRef::Map(k, v) => {
            format!("Map<{}, {}>", render_type(k, imports), render_type(v, imports))
        }
        _ => DartMapper.map_type(ty),
    }
}

fn emit_type(ty: &TypeDef, out: &mut String, imports: &mut BTreeSet<String>) {
    if !ty.doc.is_empty() {
        for line in ty.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    if ty.fields.is_empty() {
        out.push_str(&format!("class {} {{}}\n", ty.name));
        return;
    }
    out.push_str(&format!("class {} {{\n", ty.name));
    for field in &ty.fields {
        let ty_str = if field.optional {
            format!("{}?", render_type(&field.ty, imports))
        } else {
            render_type(&field.ty, imports)
        };
        let name = field.name.to_lower_camel_case();
        if !field.doc.is_empty() {
            for line in field.doc.lines() {
                out.push_str("  /// ");
                out.push_str(line);
                out.push('\n');
            }
        }
        out.push_str(&format!("  final {ty_str} {name};\n"));
    }
    // Constructor
    if ty.fields.len() == 1 {
        let name = ty.fields[0].name.to_lower_camel_case();
        let ty_str = if ty.fields[0].optional {
            format!("{}?", render_type(&ty.fields[0].ty, imports))
        } else {
            render_type(&ty.fields[0].ty, imports)
        };
        out.push_str(&format!("  {}(this.{name});\n", ty.name));
        let _ = ty_str; // used above for field emission, constructor uses `this.`
    } else {
        out.push_str(&format!("  {}({{\n", ty.name));
        for field in &ty.fields {
            let name = field.name.to_lower_camel_case();
            out.push_str(&format!("    required this.{name},\n"));
        }
        out.push_str("  });\n");
    }
    out.push_str("}\n");
}

fn emit_enum(en: &EnumDef, out: &mut String) {
    if !en.doc.is_empty() {
        for line in en.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    let all_unit = en.variants.iter().all(|v| v.fields.is_empty());
    if all_unit {
        out.push_str(&format!("enum {} {{\n", en.name));
        let count = en.variants.len();
        for (idx, variant) in en.variants.iter().enumerate() {
            if !variant.doc.is_empty() {
                for line in variant.doc.lines() {
                    out.push_str("  /// ");
                    out.push_str(line);
                    out.push('\n');
                }
            }
            let vname = variant.name.to_lower_camel_case();
            let semicolon = if idx + 1 == count { ";" } else { "," };
            out.push_str(&format!("  {vname}{semicolon}\n"));
        }
        out.push_str("}\n");
    } else {
        out.push_str(&format!("sealed class {} {{}}\n", en.name));
        for variant in &en.variants {
            if !variant.doc.is_empty() {
                for line in variant.doc.lines() {
                    out.push_str("/// ");
                    out.push_str(line);
                    out.push('\n');
                }
            }
            if variant.fields.is_empty() {
                out.push_str(&format!("final class {} extends {} {{}}\n", variant.name, en.name));
            } else {
                out.push_str(&format!("final class {} extends {} {{\n", variant.name, en.name));
                for (idx, f) in variant.fields.iter().enumerate() {
                    let ty_str = DartMapper.map_type(&f.ty);
                    let fname = if f.name.is_empty() {
                        format!("field{idx}")
                    } else {
                        f.name.to_lower_camel_case()
                    };
                    out.push_str(&format!("  final {ty_str} {fname};\n"));
                }
                if variant.fields.len() == 1 {
                    let fname = if variant.fields[0].name.is_empty() {
                        "field0".to_string()
                    } else {
                        variant.fields[0].name.to_lower_camel_case()
                    };
                    out.push_str(&format!("  {}(this.{fname});\n", variant.name));
                } else {
                    out.push_str(&format!("  {}({{\n", variant.name));
                    for (idx, f) in variant.fields.iter().enumerate() {
                        let fname = if f.name.is_empty() {
                            format!("field{idx}")
                        } else {
                            f.name.to_lower_camel_case()
                        };
                        out.push_str(&format!("    required this.{fname},\n"));
                    }
                    out.push_str("  });\n");
                }
                out.push_str("}\n");
            }
        }
    }
}

fn emit_error(error: &ErrorDef, out: &mut String, imports: &mut BTreeSet<String>) {
    if !error.doc.is_empty() {
        for line in error.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!("sealed class {} implements Exception {{\n", error.name));
    out.push_str("  String get message;\n");
    out.push_str("}\n\n");
    for variant in &error.variants {
        if !variant.doc.is_empty() {
            for line in variant.doc.lines() {
                out.push_str("/// ");
                out.push_str(line);
                out.push('\n');
            }
        }
        if variant.is_unit {
            let msg = variant.message_template.as_deref().unwrap_or(&variant.name);
            out.push_str(&format!("final class {} implements {} {{\n", variant.name, error.name));
            out.push_str(&format!("  @override\n  String get message => '{msg}';\n"));
            out.push_str(&format!("  const {}();\n", variant.name));
            out.push_str("}\n");
        } else {
            out.push_str(&format!("final class {} implements {} {{\n", variant.name, error.name));
            for f in &variant.fields {
                let ty_str = render_type(&f.ty, imports);
                let fname = f.name.to_lower_camel_case();
                out.push_str(&format!("  final {ty_str} {fname};\n"));
            }
            let msg = variant.message_template.as_deref().unwrap_or(&variant.name);
            out.push_str("  @override\n");
            out.push_str(&format!("  String get message => '{msg}';\n"));
            if variant.fields.len() == 1 {
                let fname = variant.fields[0].name.to_lower_camel_case();
                out.push_str(&format!("  {}(this.{fname});\n", variant.name));
            } else {
                out.push_str(&format!("  {}({{\n", variant.name));
                for f in &variant.fields {
                    let fname = f.name.to_lower_camel_case();
                    out.push_str(&format!("    required this.{fname},\n"));
                }
                out.push_str("  });\n");
            }
            out.push_str("}\n");
        }
    }
}

fn emit_function(f: &FunctionDef, out: &mut String, imports: &mut BTreeSet<String>) {
    if !f.doc.is_empty() {
        for line in f.doc.lines() {
            out.push_str("  /// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    if let Some(ref error_ty) = f.error_type {
        out.push_str(&format!("  /// throws {error_ty} on failure\n"));
    }

    let fn_name = f.name.to_lower_camel_case();
    let params: Vec<String> = f.params.iter().map(|p| format_param(p, imports)).collect();

    if f.is_async {
        let return_ty = if matches!(f.return_type, TypeRef::Unit) {
            "Future<void>".to_string()
        } else {
            format!("Future<{}>", render_type(&f.return_type, imports))
        };
        out.push_str(&format!(
            "  static {return_ty} {fn_name}({}) async {{\n",
            params.join(", ")
        ));
        out.push_str("    // TODO: bridge to flutter_rust_bridge generated API\n");
        out.push_str("    throw UnimplementedError();\n");
        out.push_str("  }\n");
    } else {
        let return_ty = render_type(&f.return_type, imports);
        out.push_str(&format!(
            "  static {return_ty} {fn_name}({}) {{\n",
            params.join(", ")
        ));
        out.push_str("    // TODO: bridge to flutter_rust_bridge generated API\n");
        out.push_str("    throw UnimplementedError();\n");
        out.push_str("  }\n");
    }
}

fn format_param(p: &ParamDef, imports: &mut BTreeSet<String>) -> String {
    let ty_str = if p.optional {
        format!("{}?", render_type(&p.ty, imports))
    } else {
        render_type(&p.ty, imports)
    };
    format!("{ty_str} {}", p.name.to_lower_camel_case())
}
