// Generated by alef. Do not edit by hand — this file is the codegen for codegen.
use alef_core::backend::GeneratedFile;
use alef_core::config::{AlefConfig, resolve_output_dir};
use alef_core::ir::{ApiSurface, EnumDef, FunctionDef, PrimitiveType, TypeDef, TypeRef};
use alef_core::template_versions::cargo as tv;
use std::path::PathBuf;

/// Emit the Rust-side flutter_rust_bridge bridge crate for the given API surface.
///
/// Returns four files that together form the `packages/dart/rust/` crate:
/// - `packages/dart/rust/Cargo.toml`
/// - `packages/dart/rust/src/lib.rs`
/// - `packages/dart/rust/build.rs`
/// - `packages/dart/rust/flutter_rust_bridge.yaml`
pub fn emit(api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
    let rust_dir = resolve_output_dir(None, &config.crate_config.name, "packages/dart/rust");
    let module_name = dart_module_name(&config.crate_config.name);
    let source_crate_name = config.crate_config.name.replace('-', "_");

    let exclude_functions: std::collections::HashSet<String> = config
        .dart
        .as_ref()
        .map(|c| c.exclude_functions.iter().cloned().collect())
        .unwrap_or_default();
    let exclude_types: std::collections::HashSet<String> = config
        .dart
        .as_ref()
        .map(|c| c.exclude_types.iter().cloned().collect())
        .unwrap_or_default();

    Ok(vec![
        emit_cargo_toml(&rust_dir, config, &source_crate_name),
        emit_lib_rs(&rust_dir, api, &source_crate_name, &exclude_functions, &exclude_types),
        emit_build_rs(&rust_dir),
        emit_frb_yaml(&rust_dir, &module_name),
    ])
}

fn emit_cargo_toml(rust_dir: &str, config: &AlefConfig, source_crate_name: &str) -> GeneratedFile {
    let crate_name = config.crate_config.name.as_str();
    let version = &api_version(config);
    let frb_version = tv::FLUTTER_RUST_BRIDGE;
    let core_crate_dir = config.core_crate_dir();
    let same_as_workspace = core_crate_dir == *crate_name && config.crate_config.workspace_root.is_none();
    let core_path = if same_as_workspace {
        "../../..".to_string()
    } else {
        format!("../../../crates/{core_crate_dir}")
    };

    let features = config.features_for_language(alef_core::config::extras::Language::Dart);
    let features_block = if features.is_empty() {
        String::new()
    } else {
        let list = features
            .iter()
            .map(|f| format!("\"{f}\""))
            .collect::<Vec<_>>()
            .join(", ");
        format!(", features = [{list}]")
    };

    let content = format!(
        r#"[package]
name = "{crate_name}-dart"
version = "{version}"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
{source_crate_name} = {{ path = "{core_path}"{features_block} }}
flutter_rust_bridge = "{frb_version}"
serde_json = "1"
"#
    );

    GeneratedFile {
        path: PathBuf::from(rust_dir).join("Cargo.toml"),
        content,
        generated_header: false,
    }
}

fn build_type_path_lookup(api: &ApiSurface, source_crate_name: &str) -> std::collections::HashMap<String, String> {
    let mut paths = std::collections::HashMap::new();
    for ty in &api.types {
        if !ty.rust_path.is_empty() {
            paths.insert(ty.name.clone(), ty.rust_path.replace('-', "_"));
        }
    }
    for en in &api.enums {
        if !en.rust_path.is_empty() {
            paths.insert(en.name.clone(), en.rust_path.replace('-', "_"));
        }
    }
    let _ = source_crate_name;
    paths
}

fn emit_lib_rs(
    rust_dir: &str,
    api: &ApiSurface,
    source_crate_name: &str,
    exclude_functions: &std::collections::HashSet<String>,
    exclude_types: &std::collections::HashSet<String>,
) -> GeneratedFile {
    let mut content = String::new();
    content.push_str("// Generated by alef. Do not edit by hand.\n");
    content.push_str("use flutter_rust_bridge::frb;\n");

    for ty in api.types.iter().filter(|t| !exclude_types.contains(&t.name)) {
        content.push('\n');
        emit_mirror_struct(&mut content, ty);
    }

    for en in api.enums.iter().filter(|e| !exclude_types.contains(&e.name)) {
        content.push('\n');
        emit_mirror_enum(&mut content, en);
    }

    let type_paths = build_type_path_lookup(api, source_crate_name);
    for f in api.functions.iter().filter(|f| !exclude_functions.contains(&f.name)) {
        content.push('\n');
        emit_bridge_fn(&mut content, f, source_crate_name, &type_paths);
    }

    GeneratedFile {
        path: PathBuf::from(rust_dir).join("src/lib.rs"),
        content,
        generated_header: false,
    }
}

fn emit_build_rs(rust_dir: &str) -> GeneratedFile {
    let content = "fn main() {\n    // FRB codegen runs as a separate command (`flutter_rust_bridge_codegen generate`).\n    // This build.rs is a placeholder for any pre-build steps.\n}\n".to_string();
    GeneratedFile {
        path: PathBuf::from(rust_dir).join("build.rs"),
        content,
        generated_header: false,
    }
}

fn emit_frb_yaml(rust_dir: &str, module_name: &str) -> GeneratedFile {
    // FRB v2 schema: `rust_root` points at the Rust crate dir (not a single file)
    // and `dart_output` is the directory where Dart bindings are written. The v1
    // `rust_input` / `rust_output` keys were removed in v2.
    let content = format!(
        "rust_root: .\ndart_output: ../lib/src/{module_name}_bridge_generated\n"
    );
    GeneratedFile {
        path: PathBuf::from(rust_dir).join("flutter_rust_bridge.yaml"),
        content,
        generated_header: false,
    }
}

fn emit_mirror_struct(out: &mut String, ty: &TypeDef) {
    // FRB v2 mirror convention: the mirror struct keeps the same name as the
    // original; the `mirror` attribute argument tells FRB which type this
    // declaration shadows for codegen purposes.
    out.push_str(&format!("#[frb(mirror({name}))]\n", name = ty.name));
    out.push_str(&format!("pub struct {} {{\n", ty.name));
    for field in &ty.fields {
        let rust_ty = frb_rust_type(&field.ty, field.optional);
        out.push_str(&format!("    pub {}: {rust_ty},\n", field.name));
    }
    out.push_str("}\n");
}

fn emit_mirror_enum(out: &mut String, en: &EnumDef) {
    let all_unit = en.variants.iter().all(|v| v.fields.is_empty());
    out.push_str(&format!("#[frb(mirror({name}))]\n", name = en.name));
    if all_unit {
        out.push_str(&format!("pub enum {} {{\n", en.name));
        for variant in &en.variants {
            out.push_str(&format!("    {},\n", variant.name));
        }
        out.push_str("}\n");
    } else {
        out.push_str(&format!("pub enum {} {{\n", en.name));
        for variant in &en.variants {
            if variant.fields.is_empty() {
                out.push_str(&format!("    {},\n", variant.name));
            } else {
                out.push_str(&format!("    {} {{\n", variant.name));
                for (idx, f) in variant.fields.iter().enumerate() {
                    let fname = if f.name.is_empty() {
                        format!("field{idx}")
                    } else {
                        f.name.clone()
                    };
                    let rust_ty = frb_rust_type(&f.ty, false);
                    out.push_str(&format!("        {fname}: {rust_ty},\n"));
                }
                out.push_str("    },\n");
            }
        }
        out.push_str("}\n");
    }
}

fn emit_bridge_fn(
    out: &mut String,
    f: &FunctionDef,
    source_crate_name: &str,
    type_paths: &std::collections::HashMap<String, String>,
) {
    // FRB v2: ordinary public functions need no annotation. A bare `#[frb]`
    // with no arguments is rejected by the macro. Don't emit it.
    let fn_name = &f.name;
    let async_kw = if f.is_async { "async " } else { "" };

    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| {
            // Use the source-crate type for Named types so the bridge fn passes
            // them straight through to the underlying Rust API. The `#[frb(mirror(T))]`
            // attribute on the mirror struct tells FRB that the local declaration
            // is layout-identical to the source type — FRB substitutes them on the
            // Dart side but the generated Rust code must still pass the original.
            let rust_ty = frb_rust_type_with_source(&p.ty, p.optional, source_crate_name, type_paths);
            format!("{}: {rust_ty}", p.name)
        })
        .collect();

    // For each parameter, build the call-site expression. The IR records whether
    // the underlying Rust function takes the value by reference (`is_ref`) and
    // the original concrete type (`original_type`). FRB widens primitives to
    // i64/f64 and Strings to `String`, but the source function may want `u16`,
    // `usize`, `&Path`, etc. — emit a cast (`as Foo`) or conversion call.
    let call_args: Vec<String> = f
        .params
        .iter()
        .map(|p| dart_call_arg(p))
        .collect();

    let has_error = f.error_type.is_some();
    let return_ty = if has_error {
        format!("Result<{}, String>", frb_rust_type_with_source(&f.return_type, false, source_crate_name, type_paths))
    } else {
        frb_rust_type_with_source(&f.return_type, false, source_crate_name, type_paths)
    };

    out.push_str(&format!(
        "pub {async_kw}fn {fn_name}({}) -> {return_ty} {{\n",
        params.join(", ")
    ));

    // Resolve the call target via the IR's full rust_path, falling back to the
    // backend's bare fn name if rust_path is empty. This matches alef-backend-ffi
    // and ensures functions defined in submodules (e.g. `my_lib::utils::helper`)
    // generate correct shim calls.
    let resolved_path = if f.rust_path.is_empty() {
        format!("{source_crate_name}::{fn_name}")
    } else {
        f.rust_path.replace('-', "_")
    };
    let call = format!("{resolved_path}({})", call_args.join(", "));

    // Handle return-type mismatches: FRB widens primitives but the source fn
    // may return e.g. `u64` or `&str`. Bridge with explicit conversions.
    let result_cast = match &f.return_type {
        TypeRef::Primitive(_) => {
            let target = frb_rust_type_inner(&f.return_type);
            format!(" as {target}")
        }
        // String/Path/Char returns may be `&str`/`&Path`/`&Path` from the source;
        // call .to_string() to ensure an owned String is returned.
        TypeRef::String | TypeRef::Path | TypeRef::Char => ".to_string()".to_string(),
        // Optional<String> with returns_ref=true is alef's fallback for
        // `Option<&'static T>` where T is a non-String type (like EmbeddingPreset).
        // Use Debug format so the Dart side gets a printable representation —
        // `serde_json::to_string` would require T: Serialize which isn't always true.
        TypeRef::Optional(inner)
            if matches!(inner.as_ref(), TypeRef::String | TypeRef::Path | TypeRef::Char) && f.returns_ref =>
        {
            ".map(|v| format!(\"{:?}\", v))".to_string()
        }
        TypeRef::Vec(inner) => match inner.as_ref() {
            TypeRef::Primitive(prim) => {
                let target = primitive_name(prim);
                if target == "f64" || target == "i64" || target == "bool" {
                    String::new()
                } else {
                    format!(".into_iter().map(|x| x as {}).collect::<Vec<_>>()", frb_rust_type_inner(inner))
                }
            }
            // Vec<&str> -> Vec<String>
            TypeRef::String | TypeRef::Path | TypeRef::Char => {
                ".into_iter().map(|s| s.to_string()).collect::<Vec<_>>()".to_string()
            }
            _ => String::new(),
        },
        TypeRef::Optional(inner) => match inner.as_ref() {
            TypeRef::String | TypeRef::Path | TypeRef::Char => ".map(|s| s.to_string())".to_string(),
            _ => String::new(),
        },
        _ => String::new(),
    };

    let body = if has_error {
        if f.is_async {
            format!("    {call}.await.map(|v| v{result_cast}).map_err(|e| e.to_string())\n")
        } else {
            format!("    {call}.map(|v| v{result_cast}).map_err(|e| e.to_string())\n")
        }
    } else if f.is_async {
        if result_cast.is_empty() {
            format!("    {call}.await\n")
        } else {
            format!("    {call}.await{result_cast}\n")
        }
    } else if result_cast.is_empty() {
        format!("    {call}\n")
    } else {
        format!("    {call}{result_cast}\n")
    };

    out.push_str(&body);
    out.push_str("}\n");
}

/// Maps an IR `TypeRef` to the FRB-friendly Rust type string.
/// FRB's primitive ABI: all integers → `i64`, floats → `f64`, strings → `String`.
///
/// NOTE: u64 values above i64::MAX silently wrap to negative on the Dart side
/// because Dart's native `int` is 64-bit signed. Producers of u64-bearing APIs
/// who need the full range should pre-truncate or document the contract.
fn frb_rust_type(ty: &TypeRef, optional: bool) -> String {
    let inner = frb_rust_type_inner(ty);
    if optional { format!("Option<{inner}>") } else { inner }
}

fn frb_rust_type_inner(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Primitive(p) => match p {
            PrimitiveType::Bool => "bool".to_string(),
            PrimitiveType::F32 | PrimitiveType::F64 => "f64".to_string(),
            // All integer widths → i64 (Dart int ↔ Rust i64 FRB primitive ABI)
            _ => "i64".to_string(),
        },
        TypeRef::String | TypeRef::Char => "String".to_string(),
        TypeRef::Bytes => "Vec<u8>".to_string(),
        TypeRef::Optional(inner) => format!("Option<{}>", frb_rust_type_inner(inner)),
        TypeRef::Vec(inner) => format!("Vec<{}>", frb_rust_type_inner(inner)),
        TypeRef::Map(k, v) => {
            format!("std::collections::HashMap<{}, {}>", frb_rust_type_inner(k), frb_rust_type_inner(v))
        }
        TypeRef::Named(name) => name.clone(),
        TypeRef::Path => "String".to_string(),
        TypeRef::Unit => "()".to_string(),
        TypeRef::Json => "String".to_string(),
        TypeRef::Duration => "i64".to_string(),
    }
}

fn primitive_name(prim: &alef_core::ir::PrimitiveType) -> &'static str {
    match prim {
        alef_core::ir::PrimitiveType::Bool => "bool",
        alef_core::ir::PrimitiveType::U8 => "u8",
        alef_core::ir::PrimitiveType::I8 => "i8",
        alef_core::ir::PrimitiveType::U16 => "u16",
        alef_core::ir::PrimitiveType::I16 => "i16",
        alef_core::ir::PrimitiveType::U32 => "u32",
        alef_core::ir::PrimitiveType::I32 => "i32",
        alef_core::ir::PrimitiveType::U64 => "u64",
        alef_core::ir::PrimitiveType::I64 => "i64",
        alef_core::ir::PrimitiveType::Usize => "usize",
        alef_core::ir::PrimitiveType::Isize => "isize",
        alef_core::ir::PrimitiveType::F32 => "f32",
        alef_core::ir::PrimitiveType::F64 => "f64",
    }
}

/// Build the call-site expression for a single parameter. The IR's
/// `original_type` field carries the Rust type the source function expects;
/// when present, we cast/convert the FRB-widened parameter to match.
fn dart_call_arg(p: &alef_core::ir::ParamDef) -> String {
    let name = &p.name;
    let original = p.original_type.as_deref().unwrap_or("");
    // Strip outer `&`, `&mut`, leading whitespace.
    let stripped_orig = original
        .trim()
        .trim_start_matches('&')
        .trim_start_matches("mut ")
        .trim();

    // Tuple parameters: the IR flattens `Vec<(A, B, ...)>` to `Vec<String>`,
    // losing the structural shape. Use `original_type` to spot these and emit
    // adapter logic that reconstructs a sensible default tuple. The IR stores
    // `original_type` as Rust Debug syntax (e.g.
    // `Vec(Named("(PathBuf, Option<FileExtractionConfig>)"))`).
    if !stripped_orig.is_empty() && stripped_orig.starts_with("Vec(") && stripped_orig.contains("Named(\"(") {
        let tuple_inner = stripped_orig
            .find("Named(\"(")
            .and_then(|start| {
                let rest = &stripped_orig[start + 8..]; // past `Named("(`
                rest.find(")\")")
                    .map(|end| rest[..end].trim_end_matches(')').to_string())
            })
            .unwrap_or_default();
        if tuple_inner.starts_with("PathBuf,") || tuple_inner.starts_with("PathBuf ,") {
            return format!(
                "{name}.into_iter().map(|p| (std::path::PathBuf::from(p), None)).collect::<Vec<_>>()"
            );
        }
        if tuple_inner.starts_with("Vec<u8>,") || tuple_inner.starts_with("Vec<u8> ,") {
            return format!("{{ let _ = {name}; ::std::unimplemented!(\"batch_extract_bytes from Dart not yet bridged\") }}");
        }
    }

    // Path: FRB sends String; the source likely wants &Path, PathBuf, or
    // Option<PathBuf>. Emit the conversion that matches `is_ref` and `optional`.
    if matches!(p.ty, alef_core::ir::TypeRef::Path) {
        if p.optional {
            if p.is_ref {
                return format!("{name}.as_ref().map(std::path::Path::new)");
            }
            return format!("{name}.map(std::path::PathBuf::from)");
        }
        if p.is_ref {
            return format!("std::path::Path::new(&{name})");
        }
        return format!("std::path::PathBuf::from({name})");
    }

    // Primitives: FRB widens all integer params to i64 and floats to f64. Cast
    // back to the actual primitive width before forwarding to the source fn.
    if let alef_core::ir::TypeRef::Primitive(prim) = &p.ty {
        let target = primitive_name(prim);
        if target != "i64" && target != "f64" && target != "bool" {
            if p.optional {
                return format!("{name}.map(|v| v as {target})");
            }
            return if p.is_ref {
                format!("&({name} as {target})")
            } else {
                format!("{name} as {target}")
            };
        }
    }

    // Inner-Vec primitive cast: FRB widens Vec<f32> → Vec<f64>; if the source
    // takes &[f32] we need to materialize a temporary cast Vec.
    if let alef_core::ir::TypeRef::Vec(inner) = &p.ty {
        if let alef_core::ir::TypeRef::Primitive(prim) = inner.as_ref() {
            let target = primitive_name(prim);
            if target != "i64" && target != "f64" && target != "bool" {
                if p.optional {
                    if p.is_ref {
                        return format!(
                            "{name}.as_ref().map(|v| v.iter().map(|x| *x as {target}).collect::<Vec<_>>()).as_deref()"
                        );
                    }
                    return format!(
                        "{name}.map(|v| v.into_iter().map(|x| x as {target}).collect::<Vec<_>>())"
                    );
                }
                if p.is_ref {
                    return format!(
                        "{name}.iter().map(|x| *x as {target}).collect::<Vec<_>>().as_slice()"
                    );
                }
                return format!(
                    "{name}.into_iter().map(|x| x as {target}).collect::<Vec<_>>()"
                );
            }
        }
    }

    if !p.is_ref {
        return name.clone();
    }

    match (&p.ty, p.optional) {
        (alef_core::ir::TypeRef::Bytes, false) => format!("&{name}"),
        (alef_core::ir::TypeRef::String | alef_core::ir::TypeRef::Char, false) => format!("&{name}"),
        (alef_core::ir::TypeRef::String | alef_core::ir::TypeRef::Char, true) => format!("{name}.as_deref()"),
        (alef_core::ir::TypeRef::Vec(_), true) => format!("{name}.as_deref()"),
        _ => format!("&{name}"),
    }
}

/// Like `frb_rust_type`, but Named types resolve to their source-crate path
/// so the bridge fn signature uses the original Rust type (the mirror struct
/// is layout-identical via `#[frb(mirror(T))]`).
fn frb_rust_type_with_source(
    ty: &TypeRef,
    optional: bool,
    source_crate: &str,
    type_paths: &std::collections::HashMap<String, String>,
) -> String {
    let inner = frb_rust_type_inner_with_source(ty, source_crate, type_paths);
    if optional { format!("Option<{inner}>") } else { inner }
}

fn frb_rust_type_inner_with_source(
    ty: &TypeRef,
    source_crate: &str,
    type_paths: &std::collections::HashMap<String, String>,
) -> String {
    match ty {
        TypeRef::Named(name) => match type_paths.get(name) {
            Some(path) => path.clone(),
            None => format!("{source_crate}::{name}"),
        },
        TypeRef::Optional(inner) => format!("Option<{}>", frb_rust_type_inner_with_source(inner, source_crate, type_paths)),
        TypeRef::Vec(inner) => format!("Vec<{}>", frb_rust_type_inner_with_source(inner, source_crate, type_paths)),
        TypeRef::Map(k, v) => format!(
            "std::collections::HashMap<{}, {}>",
            frb_rust_type_inner_with_source(k, source_crate, type_paths),
            frb_rust_type_inner_with_source(v, source_crate, type_paths)
        ),
        _ => frb_rust_type_inner(ty),
    }
}

/// Return type of a bridge fn (without Result wrapper).
fn frb_rust_return_type(ty: &TypeRef) -> String {
    frb_rust_type_inner(ty)
}

fn dart_module_name(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}

fn api_version(config: &AlefConfig) -> String {
    // Use explicit version override if set, otherwise fall back to "0.1.0" as a
    // safe default (the real version is resolved from Cargo.toml at publish time).
    config.version.as_deref().unwrap_or("0.1.0").to_string()
}
