// Generated by alef — raw `dart:ffi` backend (Phase 3).
//
// This module emits Dart source that calls the cbindgen-produced C shared library
// directly via `dart:ffi`. It does NOT emit a Rust crate; the same C library
// consumed by Go / Java / C# / Zig is reused.
//
// When `style = "ffi"` in [dart] config, the scaffold should use `package:ffi`
// (version `template_versions::pub_dev::FFI_PACKAGE`) instead of
// `flutter_rust_bridge`. The scaffold module update is Phase 1b follow-up work.

use alef_codegen::c_consumer;
use alef_codegen::type_mapper::TypeMapper;
use alef_core::backend::GeneratedFile;
use alef_core::config::{AlefConfig, resolve_output_dir};
use alef_core::ir::{ApiSurface, EnumDef, FunctionDef, ParamDef, PrimitiveType, TypeDef, TypeRef};
use heck::ToLowerCamelCase;
use std::path::PathBuf;

use crate::type_map::DartMapper;

/// Emit `dart:ffi` Dart source files for the given API surface.
///
/// Returns two generated files:
///
/// 1. `packages/dart/lib/src/<module>_ffi.dart` — the full `dart:ffi` implementation.
/// 2. `packages/dart/lib/src/<module>.dart` — a thin re-export wrapper so the
///    public API surface is the same regardless of bridging mode.
pub(crate) fn emit(api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
    let module_name = dart_module_name(&config.crate_config.name);
    let prefix = config.ffi_prefix();
    let lib_name = config.ffi_lib_name();

    let free_symbol = c_consumer::free_string_symbol(&prefix);
    let error_code_symbol = c_consumer::last_error_code_symbol(&prefix);
    let error_context_symbol = c_consumer::last_error_context_symbol(&prefix);

    let mut content = String::new();
    content.push_str("// Generated by alef. Do not edit by hand.\n\n");
    content.push_str("import 'dart:ffi';\n");
    content.push_str("import 'dart:io';\n");
    content.push_str("import 'package:ffi/ffi.dart';\n\n");

    // Platform-aware library loader.
    emit_lib_loader(&lib_name, &mut content);

    // Error helpers using the standard last-error pattern.
    emit_error_helpers(&prefix, &free_symbol, &error_code_symbol, &error_context_symbol, &mut content);

    for ty in &api.types {
        emit_type(ty, &mut content);
        content.push('\n');
    }

    for en in &api.enums {
        emit_enum(en, &mut content);
        content.push('\n');
    }

    for f in &api.functions {
        emit_function(f, &prefix, &free_symbol, &error_code_symbol, &mut content);
        content.push('\n');
    }

    let dir = resolve_output_dir(None, &config.crate_config.name, "packages/dart/lib/src");
    let ffi_path = PathBuf::from(&dir).join(format!("{module_name}_ffi.dart"));
    let wrapper_path = PathBuf::from(&dir).join(format!("{module_name}.dart"));

    let wrapper_content = format!(
        "// Generated by alef. Do not edit by hand.\n\nexport '{module_name}_ffi.dart';\n"
    );

    Ok(vec![
        GeneratedFile {
            path: ffi_path,
            content,
            generated_header: false,
        },
        GeneratedFile {
            path: wrapper_path,
            content: wrapper_content,
            generated_header: false,
        },
    ])
}

/// Emit the private `_lib` singleton and `_libraryPath()` helper.
fn emit_lib_loader(lib_name: &str, out: &mut String) {
    out.push_str("/// Private singleton: the loaded native library.\n");
    out.push_str("final DynamicLibrary _lib = DynamicLibrary.open(_libraryPath());\n\n");

    out.push_str("/// Resolve the platform-specific path for the native shared library.\n");
    out.push_str("String _libraryPath() {\n");
    out.push_str("  if (Platform.isMacOS) {\n");
    out.push_str(&format!("    return 'lib{lib_name}.dylib';\n"));
    out.push_str("  } else if (Platform.isWindows) {\n");
    out.push_str(&format!("    return '{lib_name}.dll';\n"));
    out.push_str("  } else {\n");
    out.push_str(&format!("    return 'lib{lib_name}.so';\n"));
    out.push_str("  }\n");
    out.push_str("}\n\n");
}

/// Emit helper functions for error introspection and string memory management.
fn emit_error_helpers(
    prefix: &str,
    free_symbol: &str,
    error_code_symbol: &str,
    error_context_symbol: &str,
    out: &mut String,
) {
    // free_string lookup
    out.push_str("/// Free a string allocated by the FFI layer.\n");
    out.push_str("/// The pointer must have been returned by a `");
    out.push_str(prefix);
    out.push_str("_*` C function.\n");
    out.push_str("typedef _FreeStringNative = Void Function(Pointer<Char> ptr);\n");
    out.push_str("typedef _FreeStringDart = void Function(Pointer<Char> ptr);\n");
    out.push_str("final void Function(Pointer<Char>) _freeString =\n");
    out.push_str(&format!(
        "    _lib.lookupFunction<_FreeStringNative, _FreeStringDart>('{free_symbol}');\n\n"
    ));

    // last_error_code lookup
    out.push_str("/// Check the last FFI error code (0 = success).\n");
    out.push_str("typedef _LastErrorCodeNative = Int32 Function();\n");
    out.push_str("typedef _LastErrorCodeDart = int Function();\n");
    out.push_str("final int Function() _lastErrorCode =\n");
    out.push_str(&format!(
        "    _lib.lookupFunction<_LastErrorCodeNative, _LastErrorCodeDart>('{error_code_symbol}');\n\n"
    ));

    // last_error_context lookup
    out.push_str("/// Retrieve the last FFI error message, or null if none.\n");
    out.push_str("typedef _LastErrorContextNative = Pointer<Utf8> Function();\n");
    out.push_str("typedef _LastErrorContextDart = Pointer<Utf8> Function();\n");
    out.push_str("final Pointer<Utf8> Function() _lastErrorContext =\n");
    out.push_str(&format!(
        "    _lib.lookupFunction<_LastErrorContextNative, _LastErrorContextDart>('{error_context_symbol}');\n\n"
    ));

    // _checkError helper
    out.push_str("/// Throw a [StateError] if the last FFI call failed.\n");
    out.push_str("void _checkError() {\n");
    out.push_str("  final code = _lastErrorCode();\n");
    out.push_str("  if (code != 0) {\n");
    out.push_str("    final ctx = _lastErrorContext();\n");
    out.push_str("    final message = ctx == nullptr ? 'FFI error code $code' : ctx.toDartString();\n");
    out.push_str("    throw StateError(message);\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");
}

/// Emit a Dart class for a struct-style type.
///
/// For types with no fields (opaque handles), the class wraps an opaque
/// `Pointer<Void>`. For value types with fields, fields are Dart-typed.
fn emit_type(ty: &TypeDef, out: &mut String) {
    if !ty.doc.is_empty() {
        for line in ty.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }

    if ty.fields.is_empty() || ty.is_opaque {
        // Opaque handle: wrap a raw pointer.
        out.push_str(&format!("class {} {{\n", ty.name));
        out.push_str("  final Pointer<Void> _ptr;\n");
        out.push_str(&format!("  {}(this._ptr);\n", ty.name));
        out.push_str("}\n");
        return;
    }

    out.push_str(&format!("class {} {{\n", ty.name));
    for field in &ty.fields {
        let ty_str = dart_type(&field.ty, field.optional);
        let name = field.name.to_lower_camel_case();
        if !field.doc.is_empty() {
            for line in field.doc.lines() {
                out.push_str("  /// ");
                out.push_str(line);
                out.push('\n');
            }
        }
        out.push_str(&format!("  final {ty_str} {name};\n"));
    }
    if ty.fields.len() == 1 {
        let name = ty.fields[0].name.to_lower_camel_case();
        out.push_str(&format!("  {}(this.{name});\n", ty.name));
    } else {
        out.push_str(&format!("  {}({{\n", ty.name));
        for field in &ty.fields {
            let name = field.name.to_lower_camel_case();
            out.push_str(&format!("    required this.{name},\n"));
        }
        out.push_str("  });\n");
    }
    out.push_str("}\n");
}

/// Emit a Dart enum (unit variants only in FFI mode).
///
/// Data variants (tagged unions) cannot be expressed ergonomically via
/// `dart:ffi` since C has no stable tagged-union ABI. Non-unit variants
/// emit a `// TODO` comment and are skipped.
fn emit_enum(en: &EnumDef, out: &mut String) {
    if !en.doc.is_empty() {
        for line in en.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }

    let all_unit = en.variants.iter().all(|v| v.fields.is_empty());
    if all_unit {
        out.push_str(&format!("enum {} {{\n", en.name));
        let count = en.variants.len();
        for (idx, variant) in en.variants.iter().enumerate() {
            if !variant.doc.is_empty() {
                for line in variant.doc.lines() {
                    out.push_str("  /// ");
                    out.push_str(line);
                    out.push('\n');
                }
            }
            let vname = variant.name.to_lower_camel_case();
            let suffix = if idx + 1 == count { ";" } else { "," };
            out.push_str(&format!("  {vname}{suffix}\n"));
        }
        out.push_str("}\n");
    } else {
        // TODO: data variants are deferred for FFI mode. dart:ffi cannot represent
        // tagged unions ergonomically. Emit a unit placeholder for now.
        out.push_str(&format!(
            "// TODO: {} has data variants; dart:ffi tagged-union support is deferred.\n",
            en.name
        ));
        out.push_str(&format!("enum {} {{\n", en.name));
        let count = en.variants.len();
        for (idx, variant) in en.variants.iter().enumerate() {
            let vname = variant.name.to_lower_camel_case();
            let suffix = if idx + 1 == count { ";" } else { "," };
            out.push_str(&format!("  {vname}{suffix}\n"));
        }
        out.push_str("}\n");
    }
}

/// Emit a Dart function that resolves its C symbol via `_lib.lookupFunction`.
fn emit_function(
    f: &FunctionDef,
    prefix: &str,
    free_symbol: &str,
    error_code_symbol: &str,
    out: &mut String,
) {
    if f.is_async {
        // TODO: dart:ffi async requires Isolate plumbing; deferred for Phase 3b.
        out.push_str(&format!(
            "// TODO: async function '{}' is not supported in dart:ffi mode; deferred.\n",
            f.name
        ));
        return;
    }

    if !f.doc.is_empty() {
        for line in f.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    if let Some(ref error_ty) = f.error_type {
        out.push_str(&format!("/// Throws [StateError] on failure (was: {error_ty}).\n"));
    }

    let c_symbol = format!("{prefix}_{}", f.name);
    let fn_name = f.name.to_lower_camel_case();

    // Emit the native and Dart typedef pair.
    let native_params: Vec<String> = f.params.iter().map(native_param_type).collect();
    let native_return = native_return_type(&f.return_type);
    let dart_params: Vec<String> = f.params.iter().map(dart_callable_type).collect();
    let dart_return = dart_callable_return(&f.return_type);

    let typedef_native = format!("_{fn_name}Native");
    let typedef_dart = format!("_{fn_name}Dart");

    out.push_str(&format!(
        "typedef {typedef_native} = {native_return} Function({});\n",
        native_params.join(", ")
    ));
    out.push_str(&format!(
        "typedef {typedef_dart} = {dart_return} Function({});\n",
        dart_params.join(", ")
    ));
    out.push_str(&format!(
        "final {dart_return} Function({}) _{fn_name}Fn =\n",
        dart_params.join(", ")
    ));
    out.push_str(&format!(
        "    _lib.lookupFunction<{typedef_native}, {typedef_dart}>('{c_symbol}');\n\n"
    ));

    // Emit the public wrapper function.
    let dart_wrapper_params: Vec<String> = f.params.iter().map(dart_wrapper_param).collect();
    let wrapper_return = dart_public_return(&f.return_type);

    out.push_str(&format!(
        "{wrapper_return} {fn_name}({}) {{\n",
        dart_wrapper_params.join(", ")
    ));

    // Allocate native strings for each string parameter.
    for p in &f.params {
        emit_param_alloc(p, out);
    }

    // Build the C call argument list.
    let call_args: Vec<String> = f.params.iter().map(call_arg_name).collect();
    let call_args_str = call_args.join(", ");

    if matches!(f.return_type, TypeRef::Unit) {
        out.push_str(&format!("  _{fn_name}Fn({call_args_str});\n"));
        if f.error_type.is_some() {
            out.push_str("  _checkError();\n");
        }
        emit_param_free_all(&f.params, out);
    } else {
        out.push_str(&format!("  final _result = _{fn_name}Fn({call_args_str});\n"));
        if f.error_type.is_some() {
            out.push_str("  _checkError();\n");
        }
        emit_param_free_all(&f.params, out);
        let ret_expr = unwrap_return_expr("_result", &f.return_type, free_symbol, error_code_symbol);
        out.push_str(&format!("  return {ret_expr};\n"));
    }

    out.push_str("}\n");
}

/// Allocate a native UTF-8 string for a string/path parameter.
fn emit_param_alloc(p: &ParamDef, out: &mut String) {
    let name = p.name.to_lower_camel_case();
    match &p.ty {
        TypeRef::String | TypeRef::Path | TypeRef::Json | TypeRef::Vec(_) | TypeRef::Map(_, _) => {
            out.push_str(&format!("  final {name}Native = {name}.toNativeUtf8();\n"));
        }
        _ => {}
    }
}

/// Free all previously allocated native strings.
fn emit_param_free_all(params: &[ParamDef], out: &mut String) {
    for p in params {
        let name = p.name.to_lower_camel_case();
        match &p.ty {
            TypeRef::String | TypeRef::Path | TypeRef::Json | TypeRef::Vec(_) | TypeRef::Map(_, _) => {
                out.push_str(&format!("  calloc.free({name}Native);\n"));
            }
            _ => {}
        }
    }
}

/// The `dart:ffi` native C type for a function parameter (in the native typedef).
fn native_param_type(p: &ParamDef) -> String {
    match &p.ty {
        TypeRef::String | TypeRef::Path | TypeRef::Json | TypeRef::Vec(_) | TypeRef::Map(_, _) => {
            "Pointer<Utf8>".to_string()
        }
        TypeRef::Bytes => "Pointer<Uint8>".to_string(),
        TypeRef::Primitive(prim) => native_primitive(prim),
        TypeRef::Char => "Uint32".to_string(),
        _ => "Pointer<Void>".to_string(),
    }
}

/// The Dart callable type for a function parameter (in the Dart typedef).
fn dart_callable_type(p: &ParamDef) -> String {
    match &p.ty {
        TypeRef::String | TypeRef::Path | TypeRef::Json | TypeRef::Vec(_) | TypeRef::Map(_, _) => {
            "Pointer<Utf8>".to_string()
        }
        TypeRef::Bytes => "Pointer<Uint8>".to_string(),
        TypeRef::Primitive(prim) => dart_primitive_callable(prim),
        TypeRef::Char => "int".to_string(),
        _ => "Pointer<Void>".to_string(),
    }
}

/// Dart public wrapper parameter declaration (e.g. `String name`).
fn dart_wrapper_param(p: &ParamDef) -> String {
    let ty = dart_type(&p.ty, p.optional);
    let name = p.name.to_lower_camel_case();
    format!("{ty} {name}")
}

/// Argument expression to pass into the low-level `_fnName` call.
fn call_arg_name(p: &ParamDef) -> String {
    let name = p.name.to_lower_camel_case();
    match &p.ty {
        TypeRef::String | TypeRef::Path | TypeRef::Json | TypeRef::Vec(_) | TypeRef::Map(_, _) => {
            format!("{name}Native.cast<Utf8>()")
        }
        _ => name,
    }
}

/// Native C return type (used in the native typedef).
fn native_return_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Unit => "Void".to_string(),
        TypeRef::String | TypeRef::Path | TypeRef::Json | TypeRef::Vec(_) | TypeRef::Map(_, _) => {
            "Pointer<Char>".to_string()
        }
        TypeRef::Bytes => "Pointer<Uint8>".to_string(),
        TypeRef::Primitive(prim) => native_primitive(prim),
        TypeRef::Char => "Uint32".to_string(),
        _ => "Pointer<Void>".to_string(),
    }
}

/// Dart callable return type (used in the Dart typedef).
fn dart_callable_return(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Unit => "void".to_string(),
        TypeRef::String | TypeRef::Path | TypeRef::Json | TypeRef::Vec(_) | TypeRef::Map(_, _) => {
            "Pointer<Char>".to_string()
        }
        TypeRef::Bytes => "Pointer<Uint8>".to_string(),
        TypeRef::Primitive(prim) => dart_primitive_callable(prim),
        TypeRef::Char => "int".to_string(),
        _ => "Pointer<Void>".to_string(),
    }
}

/// Public Dart return type in the wrapper function signature.
fn dart_public_return(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Unit => "void".to_string(),
        _ => dart_type(ty, false),
    }
}

/// Convert a raw C return value to the public Dart type.
fn unwrap_return_expr(raw: &str, ty: &TypeRef, _free_symbol: &str, _error_code_symbol: &str) -> String {
    match ty {
        TypeRef::String | TypeRef::Path | TypeRef::Json => {
            // Marshal the null-terminated C string to Dart, then free the FFI allocation.
            format!(
                "() {{ final s = {raw}.cast<Utf8>().toDartString(); _freeString({raw}.cast<Char>()); return s; }}()"
            )
        }
        TypeRef::Vec(_) | TypeRef::Map(_, _) => {
            // Vec/Map are serialised as JSON strings across the C boundary.
            format!(
                "() {{ final s = {raw}.cast<Utf8>().toDartString(); _freeString({raw}.cast<Char>()); return s; }}()"
            )
        }
        _ => raw.to_string(),
    }
}

/// `dart:ffi` native (C) type for a primitive.
fn native_primitive(prim: &PrimitiveType) -> String {
    match prim {
        PrimitiveType::Bool => "Bool".to_string(),
        PrimitiveType::U8 => "Uint8".to_string(),
        PrimitiveType::I8 => "Int8".to_string(),
        PrimitiveType::U16 => "Uint16".to_string(),
        PrimitiveType::I16 => "Int16".to_string(),
        PrimitiveType::U32 => "Uint32".to_string(),
        PrimitiveType::I32 => "Int32".to_string(),
        PrimitiveType::U64 => "Uint64".to_string(),
        PrimitiveType::I64 => "Int64".to_string(),
        PrimitiveType::Usize => "Size".to_string(),
        PrimitiveType::Isize => "IntPtr".to_string(),
        PrimitiveType::F32 => "Float".to_string(),
        PrimitiveType::F64 => "Double".to_string(),
    }
}

/// Dart callable (non-native) type for a primitive.
fn dart_primitive_callable(prim: &PrimitiveType) -> String {
    match prim {
        PrimitiveType::Bool => "bool".to_string(),
        PrimitiveType::F32 | PrimitiveType::F64 => "double".to_string(),
        _ => "int".to_string(),
    }
}

/// Public Dart type (high-level) for a type ref.
fn dart_type(ty: &TypeRef, optional: bool) -> String {
    let inner = match ty {
        TypeRef::Bytes => "Uint8List".to_string(),
        TypeRef::Optional(inner) => return dart_type(inner, true),
        TypeRef::Vec(inner) => format!("List<{}>", dart_type(inner, false)),
        TypeRef::Map(k, v) => format!("Map<{}, {}>", dart_type(k, false), dart_type(v, false)),
        TypeRef::Primitive(prim) => DartMapper.primitive(prim).into_owned(),
        _ => DartMapper.map_type(ty),
    };
    if optional { format!("{inner}?") } else { inner }
}

fn dart_module_name(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lib_loader_contains_platform_branches() {
        let mut out = String::new();
        emit_lib_loader("my_lib", &mut out);
        assert!(out.contains("Platform.isMacOS"), "missing macOS branch");
        assert!(out.contains("Platform.isWindows"), "missing Windows branch");
        assert!(out.contains("libmy_lib.dylib"), "missing dylib");
        assert!(out.contains("my_lib.dll"), "missing dll");
        assert!(out.contains("libmy_lib.so"), "missing so");
    }

    #[test]
    fn error_helpers_reference_correct_symbols() {
        let mut out = String::new();
        emit_error_helpers(
            "mylib",
            "mylib_free_string",
            "mylib_last_error_code",
            "mylib_last_error_context",
            &mut out,
        );
        assert!(out.contains("mylib_free_string"), "missing free_string symbol");
        assert!(out.contains("mylib_last_error_code"), "missing error_code symbol");
        assert!(out.contains("mylib_last_error_context"), "missing error_context symbol");
        assert!(out.contains("_checkError"), "missing _checkError helper");
    }
}
