use alef_codegen::type_mapper::TypeMapper;
use alef_core::backend::{Backend, BuildConfig, BuildDependency, Capabilities, GeneratedFile};
use alef_core::config::{AlefConfig, KotlinTarget, Language, resolve_output_dir};
use alef_core::ir::{ApiSurface, EnumDef, FunctionDef, ParamDef, TypeDef, TypeRef};
use std::collections::BTreeSet;
use std::path::PathBuf;

use crate::type_map::KotlinMapper;

pub struct KotlinBackend;

const BRIDGE_ALIAS: &str = "Bridge";

impl Backend for KotlinBackend {
    fn name(&self) -> &str {
        "kotlin"
    }

    fn language(&self) -> Language {
        Language::Kotlin
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: true,
            supports_classes: true,
            supports_enums: true,
            supports_option: true,
            supports_result: true,
            supports_callbacks: false,
            supports_streaming: false,
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        match config.kotlin_target() {
            KotlinTarget::Jvm => generate_jvm(api, config),
            KotlinTarget::Native => crate::gen_native::emit(api, config),
            KotlinTarget::Multiplatform => {
                anyhow::bail!("Kotlin Multiplatform target is reserved for a follow-up phase")
            }
        }
    }

    fn build_config(&self) -> Option<BuildConfig> {
        Some(BuildConfig {
            tool: "gradle",
            crate_suffix: "",
            build_dep: BuildDependency::Ffi,
            post_build: vec![],
        })
    }
}

fn generate_jvm(api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
    let package = kotlin_package(config);
    let module_name = kotlin_module_name(&config.crate_config.name);
    let java_package = java_package(config);

    let mut imports: BTreeSet<String> = BTreeSet::new();
    let mut body = String::new();

    for ty in &api.types {
        emit_type_with_imports(ty, &mut body, &mut imports);
        body.push('\n');
    }

    for en in &api.enums {
        emit_enum(en, &mut body);
        body.push('\n');
    }

    for error in &api.errors {
        emit_error_type_with_imports(error, &mut body, &mut imports);
        body.push('\n');
    }

    if !api.functions.is_empty() {
        // Import the Java facade class with an alias so it does not collide with the
        // Kotlin object that wraps it (both share the PascalCase crate name).
        imports.insert(format!("import {java_package}.{module_name} as {BRIDGE_ALIAS}"));
        if api.functions.iter().any(|f| f.is_async) {
            imports.insert("import kotlinx.coroutines.Dispatchers".to_string());
            imports.insert("import kotlinx.coroutines.future.await".to_string());
            imports.insert("import kotlinx.coroutines.withContext".to_string());
        }

        body.push_str(&format!("object {module_name} {{\n"));
        for f in &api.functions {
            emit_function(f, &mut body, &mut imports, &java_package);
            body.push('\n');
        }
        body.push_str("}\n");
    }

    let mut content = String::new();
    content.push_str("// Generated by alef. Do not edit by hand.\n\n");
    content.push_str(&format!("package {package}\n\n"));
    for import in &imports {
        content.push_str(import);
        content.push('\n');
    }
    if !imports.is_empty() {
        content.push('\n');
    }
    content.push_str(&body);

    let package_path = package.replace('.', "/");
    let dir = resolve_output_dir(
        None,
        &config.crate_config.name,
        &format!("packages/kotlin/src/main/kotlin/{package_path}"),
    );
    let path = PathBuf::from(dir).join(format!("{module_name}.kt"));

    Ok(vec![GeneratedFile {
        path,
        content,
        generated_header: false,
    }])
}

fn emit_type_with_imports(ty: &TypeDef, out: &mut String, imports: &mut BTreeSet<String>) {
    if !ty.doc.is_empty() {
        for line in ty.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    if ty.fields.is_empty() {
        out.push_str(&format!("class {} {{}}\n", ty.name));
        return;
    }
    out.push_str(&format!("data class {}(\n", ty.name));
    for (idx, field) in ty.fields.iter().enumerate() {
        let ty_str = kotlin_type_with_string_imports(&field.ty, field.optional, imports);
        let name = to_lower_camel(&field.name);
        let comma = if idx + 1 == ty.fields.len() { "" } else { "," };
        out.push_str(&format!("    val {name}: {ty_str}{comma}\n"));
    }
    out.push_str(")\n");
}

fn emit_enum(en: &EnumDef, out: &mut String) {
    if !en.doc.is_empty() {
        for line in en.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    let all_unit = en.variants.iter().all(|v| v.fields.is_empty());
    if all_unit {
        out.push_str(&format!("enum class {} {{\n", en.name));
        let names: Vec<String> = en.variants.iter().map(|v| to_screaming_snake(&v.name)).collect();
        for (idx, name) in names.iter().enumerate() {
            let comma = if idx + 1 == names.len() { ";" } else { "," };
            out.push_str(&format!("    {name}{comma}\n"));
        }
        out.push_str("}\n");
    } else {
        out.push_str(&format!("sealed class {} {{\n", en.name));
        for variant in &en.variants {
            if variant.fields.is_empty() {
                out.push_str(&format!("    object {} : {}()\n", variant.name, en.name));
            } else {
                out.push_str(&format!("    data class {}(\n", variant.name));
                for (idx, f) in variant.fields.iter().enumerate() {
                    let ty_str = kotlin_type(&f.ty, f.optional, &mut BTreeSet::new());
                    let name = if f.name.is_empty() {
                        format!("field{idx}")
                    } else {
                        to_lower_camel(&f.name)
                    };
                    let comma = if idx + 1 == variant.fields.len() { "" } else { "," };
                    out.push_str(&format!("        val {name}: {ty_str}{comma}\n"));
                }
                out.push_str(&format!("    ) : {}()\n", en.name));
            }
        }
        out.push_str("}\n");
    }
}

fn emit_error_type_with_imports(error: &alef_core::ir::ErrorDef, out: &mut String, imports: &mut BTreeSet<String>) {
    if !error.doc.is_empty() {
        for line in error.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!(
        "sealed class {}(message: String) : Exception(message) {{\n",
        error.name
    ));
    for variant in &error.variants {
        if variant.is_unit {
            out.push_str(&format!(
                "    object {} : {}(\"{}\")\n",
                variant.name,
                error.name,
                variant.message_template.as_deref().unwrap_or(&variant.name)
            ));
        } else {
            out.push_str(&format!("    data class {}(\n", variant.name));
            for (idx, f) in variant.fields.iter().enumerate() {
                let ty_str = kotlin_type_with_string_imports(&f.ty, f.optional, imports);
                let name = to_lower_camel(&f.name);
                let comma = if idx + 1 == variant.fields.len() { "" } else { "," };
                out.push_str(&format!("        val {name}: {ty_str}{comma}\n"));
            }
            let message_template = variant.message_template.as_deref().unwrap_or(&variant.name);
            out.push_str(&format!("    ) : {}(\"{message_template}\")\n", error.name));
        }
    }
    out.push_str("}\n");
}

fn emit_function(f: &FunctionDef, out: &mut String, imports: &mut BTreeSet<String>, _java_package: &str) {
    if !f.doc.is_empty() {
        for line in f.doc.lines() {
            out.push_str("    /// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    let params: Vec<String> = f.params.iter().map(|p| format_param_with_imports(p, imports)).collect();
    let return_ty = kotlin_type_with_string_imports(&f.return_type, false, imports);
    let async_kw = if f.is_async { "suspend " } else { "" };
    let func_name_camel = to_lower_camel(&f.name);
    let call_args = f
        .params
        .iter()
        .map(|p| to_lower_camel(&p.name))
        .collect::<Vec<_>>()
        .join(", ");

    out.push_str(&format!(
        "    {async_kw}fun {}({}): {} {{\n",
        func_name_camel,
        params.join(", "),
        return_ty
    ));

    if f.is_async {
        out.push_str("        return withContext(Dispatchers.IO) {\n");
        if matches!(f.return_type, TypeRef::Unit) {
            out.push_str(&format!("            Bridge.{}({})\n", func_name_camel, call_args));
        } else {
            out.push_str(&format!(
                "            Bridge.{}({}).await()\n",
                func_name_camel, call_args
            ));
        }
        out.push_str("        }\n");
    } else {
        if matches!(f.return_type, TypeRef::Unit) {
            out.push_str(&format!("        Bridge.{}({})\n", func_name_camel, call_args));
        } else {
            out.push_str(&format!("        return Bridge.{}({})\n", func_name_camel, call_args));
        }
    }
    out.push_str("    }\n");
}

fn format_param_with_imports(p: &ParamDef, imports: &mut BTreeSet<String>) -> String {
    let ty_str = kotlin_type_with_string_imports(&p.ty, p.optional, imports);
    format!("{}: {}", to_lower_camel(&p.name), ty_str)
}

fn kotlin_type(ty: &TypeRef, optional: bool, imports: &mut BTreeSet<&'static str>) -> String {
    let inner = render_type_ref_with_imports(ty, imports);
    if optional { format!("{inner}?") } else { inner }
}

fn render_type_ref_with_imports(ty: &TypeRef, imports: &mut BTreeSet<&'static str>) -> String {
    let mapper = KotlinMapper;
    match ty {
        TypeRef::Path => {
            imports.insert("import java.nio.file.Path");
            mapper.map_type(ty)
        }
        TypeRef::Duration => {
            imports.insert("import kotlin.time.Duration");
            mapper.map_type(ty)
        }
        TypeRef::Optional(inner) => format!("{}?", render_type_ref_with_imports(inner, imports)),
        TypeRef::Vec(inner) => {
            format!("List<{}>", render_type_ref_with_imports(inner, imports))
        }
        TypeRef::Map(k, v) => {
            format!(
                "Map<{}, {}>",
                render_type_ref_with_imports(k, imports),
                render_type_ref_with_imports(v, imports)
            )
        }
        _ => mapper.map_type(ty),
    }
}

fn render_type_ref_with_string_imports(ty: &TypeRef, imports: &mut BTreeSet<String>) -> String {
    let mapper = KotlinMapper;
    match ty {
        TypeRef::Path => {
            imports.insert("import java.nio.file.Path".to_string());
            mapper.map_type(ty)
        }
        TypeRef::Duration => {
            imports.insert("import kotlin.time.Duration".to_string());
            mapper.map_type(ty)
        }
        TypeRef::Optional(inner) => format!("{}?", render_type_ref_with_string_imports(inner, imports)),
        TypeRef::Vec(inner) => {
            format!("List<{}>", render_type_ref_with_string_imports(inner, imports))
        }
        TypeRef::Map(k, v) => {
            format!(
                "Map<{}, {}>",
                render_type_ref_with_string_imports(k, imports),
                render_type_ref_with_string_imports(v, imports)
            )
        }
        _ => mapper.map_type(ty),
    }
}

fn kotlin_type_with_string_imports(ty: &TypeRef, optional: bool, imports: &mut BTreeSet<String>) -> String {
    let inner = render_type_ref_with_string_imports(ty, imports);
    if optional { format!("{inner}?") } else { inner }
}

fn kotlin_package(config: &AlefConfig) -> String {
    config.kotlin_package()
}

fn java_package(config: &AlefConfig) -> String {
    config.java_package()
}

fn kotlin_module_name(crate_name: &str) -> String {
    to_pascal_case(crate_name)
}

fn to_pascal_case(name: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for ch in name.chars() {
        if ch == '-' || ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn to_lower_camel(name: &str) -> String {
    let pascal = to_pascal_case(name);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

fn to_screaming_snake(name: &str) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(ch.to_uppercase());
        } else {
            out.extend(ch.to_uppercase());
        }
    }
    out
}
