use alef_core::backend::{Backend, BuildConfig, BuildDependency, Capabilities, GeneratedFile};
use alef_core::config::{AlefConfig, Language, resolve_output_dir};
use alef_core::ir::{ApiSurface, EnumDef, FunctionDef, ParamDef, PrimitiveType, TypeDef, TypeRef};
use std::collections::BTreeSet;
use std::path::PathBuf;

pub struct KotlinBackend;

const DEFAULT_PACKAGE: &str = "dev.kreuzberg";

impl Backend for KotlinBackend {
    fn name(&self) -> &str {
        "kotlin"
    }

    fn language(&self) -> Language {
        Language::Kotlin
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: true,
            supports_classes: true,
            supports_enums: true,
            supports_option: true,
            supports_result: true,
            supports_callbacks: false,
            supports_streaming: false,
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let package = kotlin_package(config);
        let module_name = kotlin_module_name(&config.crate_config.name);

        let mut imports: BTreeSet<&'static str> = BTreeSet::new();
        let mut body = String::new();

        for ty in &api.types {
            emit_type(ty, &mut body, &mut imports);
            body.push('\n');
        }

        for en in &api.enums {
            emit_enum(en, &mut body);
            body.push('\n');
        }

        if !api.functions.is_empty() {
            body.push_str(&format!("object {module_name} {{\n"));
            for f in &api.functions {
                emit_function(f, &mut body, &mut imports);
                body.push('\n');
            }
            body.push_str("}\n");
        }

        let mut content = String::new();
        content.push_str("// Generated by alef. Do not edit by hand.\n\n");
        content.push_str(&format!("package {package}\n\n"));
        for import in &imports {
            content.push_str(import);
            content.push('\n');
        }
        if !imports.is_empty() {
            content.push('\n');
        }
        content.push_str(&body);

        let package_path = package.replace('.', "/");
        let dir = resolve_output_dir(
            None,
            &config.crate_config.name,
            &format!("packages/kotlin/src/main/kotlin/{package_path}"),
        );
        let path = PathBuf::from(dir).join(format!("{module_name}.kt"));

        Ok(vec![GeneratedFile {
            path,
            content,
            generated_header: false,
        }])
    }

    fn build_config(&self) -> Option<BuildConfig> {
        Some(BuildConfig {
            tool: "gradle",
            crate_suffix: "",
            build_dep: BuildDependency::Ffi,
            post_build: vec![],
        })
    }
}

fn emit_type(ty: &TypeDef, out: &mut String, imports: &mut BTreeSet<&'static str>) {
    if !ty.doc.is_empty() {
        for line in ty.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    if ty.fields.is_empty() {
        out.push_str(&format!("class {} {{}}\n", ty.name));
        return;
    }
    out.push_str(&format!("data class {}(\n", ty.name));
    for (idx, field) in ty.fields.iter().enumerate() {
        let ty_str = kotlin_type(&field.ty, field.optional, imports);
        let name = to_lower_camel(&field.name);
        let comma = if idx + 1 == ty.fields.len() { "" } else { "," };
        out.push_str(&format!("    val {name}: {ty_str}{comma}\n"));
    }
    out.push_str(")\n");
}

fn emit_enum(en: &EnumDef, out: &mut String) {
    if !en.doc.is_empty() {
        for line in en.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    let all_unit = en.variants.iter().all(|v| v.fields.is_empty());
    if all_unit {
        out.push_str(&format!("enum class {} {{\n", en.name));
        let names: Vec<String> = en.variants.iter().map(|v| to_screaming_snake(&v.name)).collect();
        for (idx, name) in names.iter().enumerate() {
            let comma = if idx + 1 == names.len() { ";" } else { "," };
            out.push_str(&format!("    {name}{comma}\n"));
        }
        out.push_str("}\n");
    } else {
        out.push_str(&format!("sealed class {} {{\n", en.name));
        for variant in &en.variants {
            if variant.fields.is_empty() {
                out.push_str(&format!("    object {} : {}()\n", variant.name, en.name));
            } else {
                out.push_str(&format!("    data class {}(\n", variant.name));
                for (idx, f) in variant.fields.iter().enumerate() {
                    let ty_str = kotlin_type(&f.ty, f.optional, &mut BTreeSet::new());
                    let name = if f.name.is_empty() {
                        format!("field{idx}")
                    } else {
                        to_lower_camel(&f.name)
                    };
                    let comma = if idx + 1 == variant.fields.len() { "" } else { "," };
                    out.push_str(&format!("        val {name}: {ty_str}{comma}\n"));
                }
                out.push_str(&format!("    ) : {}()\n", en.name));
            }
        }
        out.push_str("}\n");
    }
}

fn emit_function(f: &FunctionDef, out: &mut String, imports: &mut BTreeSet<&'static str>) {
    if !f.doc.is_empty() {
        for line in f.doc.lines() {
            out.push_str("    /// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    let params: Vec<String> = f.params.iter().map(|p| format_param(p, imports)).collect();
    let return_ty = kotlin_type(&f.return_type, false, imports);
    let async_kw = if f.is_async { "suspend " } else { "" };
    out.push_str(&format!(
        "    {async_kw}fun {}({}): {} = TODO(\"Phase 1C: bridge to Java/Panama\")\n",
        to_lower_camel(&f.name),
        params.join(", "),
        return_ty
    ));
}

fn format_param(p: &ParamDef, imports: &mut BTreeSet<&'static str>) -> String {
    let ty_str = kotlin_type(&p.ty, p.optional, imports);
    format!("{}: {}", to_lower_camel(&p.name), ty_str)
}

fn kotlin_type(ty: &TypeRef, optional: bool, imports: &mut BTreeSet<&'static str>) -> String {
    let inner = render_type_ref(ty, imports);
    if optional { format!("{inner}?") } else { inner }
}

fn render_type_ref(ty: &TypeRef, imports: &mut BTreeSet<&'static str>) -> String {
    match ty {
        TypeRef::Primitive(p) => primitive(p).to_string(),
        TypeRef::String | TypeRef::Json => "String".to_string(),
        TypeRef::Char => "Char".to_string(),
        TypeRef::Bytes => "ByteArray".to_string(),
        TypeRef::Path => {
            imports.insert("import java.nio.file.Path");
            "Path".to_string()
        }
        TypeRef::Optional(inner) => format!("{}?", render_type_ref(inner, imports)),
        TypeRef::Vec(inner) => format!("List<{}>", render_type_ref(inner, imports)),
        TypeRef::Map(k, v) => format!(
            "Map<{}, {}>",
            render_type_ref(k, imports),
            render_type_ref(v, imports)
        ),
        TypeRef::Named(name) => name.clone(),
        TypeRef::Unit => "Unit".to_string(),
        TypeRef::Duration => {
            imports.insert("import kotlin.time.Duration");
            "Duration".to_string()
        }
    }
}

fn primitive(p: &PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::Bool => "Boolean",
        PrimitiveType::U8 => "UByte",
        PrimitiveType::U16 => "UShort",
        PrimitiveType::U32 => "UInt",
        PrimitiveType::U64 | PrimitiveType::Usize => "ULong",
        PrimitiveType::I8 => "Byte",
        PrimitiveType::I16 => "Short",
        PrimitiveType::I32 => "Int",
        PrimitiveType::I64 | PrimitiveType::Isize => "Long",
        PrimitiveType::F32 => "Float",
        PrimitiveType::F64 => "Double",
    }
}

fn kotlin_package(_config: &AlefConfig) -> String {
    DEFAULT_PACKAGE.to_string()
}

fn kotlin_module_name(crate_name: &str) -> String {
    to_pascal_case(crate_name)
}

fn to_pascal_case(name: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for ch in name.chars() {
        if ch == '-' || ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn to_lower_camel(name: &str) -> String {
    let pascal = to_pascal_case(name);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

fn to_screaming_snake(name: &str) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(ch.to_uppercase());
        } else {
            out.extend(ch.to_uppercase());
        }
    }
    out
}
