//! Kotlin/Native binding generator — Phase 3.
//!
//! Emits Kotlin/Native source that calls into the cbindgen-produced C FFI library
//! via `kotlinx.cinterop.*`. The consumer pattern mirrors the Go and Zig backends:
//! use `config.ffi_prefix()`, `config.ffi_header_name()`, and `config.ffi_lib_name()`
//! as the single source of truth for symbol names and linking directives.

use alef_codegen::c_consumer;
use alef_core::backend::GeneratedFile;
use alef_core::config::{AlefConfig, resolve_output_dir};
use alef_core::ir::{ApiSurface, EnumDef, ErrorDef, FunctionDef, ParamDef, TypeDef, TypeRef};
use alef_core::template_versions;
use std::collections::BTreeSet;
use std::path::PathBuf;

use crate::gen_bindings::{to_lower_camel, to_pascal_case, to_screaming_snake};

/// Emit all Kotlin/Native files for the given API surface.
///
/// Returns three generated files:
/// 1. `packages/kotlin-native/src/nativeMain/kotlin/<package>/<Module>.kt`
/// 2. `packages/kotlin-native/<crate>.def`
/// 3. `packages/kotlin-native/build.gradle.kts`
pub fn emit(api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
    let kt = emit_kotlin_source(api, config);
    let def = emit_def_file(config);
    let gradle = emit_gradle_build(config);

    let package = config.kotlin_package();
    let package_path = package.replace('.', "/");
    let module_name = to_pascal_case(&config.crate_config.name);
    let crate_name = &config.crate_config.name;

    let native_root = resolve_output_dir(None, crate_name, "packages/kotlin-native");

    let kt_path = PathBuf::from(&native_root)
        .join("src/nativeMain/kotlin")
        .join(&package_path)
        .join(format!("{module_name}.kt"));

    let def_path = PathBuf::from(&native_root).join(format!("{crate_name}.def"));
    let gradle_path = PathBuf::from(&native_root).join("build.gradle.kts");

    Ok(vec![
        GeneratedFile {
            path: kt_path,
            content: kt,
            generated_header: false,
        },
        GeneratedFile {
            path: def_path,
            content: def,
            generated_header: false,
        },
        GeneratedFile {
            path: gradle_path,
            content: gradle,
            generated_header: false,
        },
    ])
}

// ---------------------------------------------------------------------------
// Kotlin/Native source file
// ---------------------------------------------------------------------------

fn emit_kotlin_source(api: &ApiSurface, config: &AlefConfig) -> String {
    let package = config.kotlin_package();
    let module_name = to_pascal_case(&config.crate_config.name);
    let prefix = config.ffi_prefix();
    let crate_name = &config.crate_config.name;

    let mut imports: BTreeSet<String> = BTreeSet::new();
    imports.insert("import kotlinx.cinterop.*".to_string());
    imports.insert(format!("import {crate_name}.*"));

    let mut body = String::new();

    for ty in &api.types {
        emit_native_type(ty, &mut body);
        body.push('\n');
    }

    for en in &api.enums {
        emit_native_enum(en, &mut body);
        body.push('\n');
    }

    for error in &api.errors {
        emit_native_error(error, &mut body);
        body.push('\n');
    }

    if !api.functions.is_empty() {
        body.push_str(&format!("object {module_name} {{\n"));
        for f in &api.functions {
            emit_native_function(f, &prefix, &mut body);
            body.push('\n');
        }
        body.push_str("}\n");
    }

    let mut content = String::new();
    content.push_str("// Generated by alef. Do not edit by hand.\n\n");
    content.push_str(&format!("package {package}\n\n"));
    for import in &imports {
        content.push_str(import);
        content.push('\n');
    }
    content.push('\n');
    content.push_str(&body);
    content
}

fn emit_native_type(ty: &TypeDef, out: &mut String) {
    if !ty.doc.is_empty() {
        for line in ty.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    if ty.fields.is_empty() {
        out.push_str(&format!("class {} {{}}\n", ty.name));
        return;
    }
    out.push_str(&format!("data class {}(\n", ty.name));
    for (idx, field) in ty.fields.iter().enumerate() {
        let ty_str = native_type_str(&field.ty, field.optional);
        let name = to_lower_camel(&field.name);
        let comma = if idx + 1 == ty.fields.len() { "" } else { "," };
        out.push_str(&format!("    val {name}: {ty_str}{comma}\n"));
    }
    out.push_str(")\n");
}

fn emit_native_enum(en: &EnumDef, out: &mut String) {
    if !en.doc.is_empty() {
        for line in en.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    let all_unit = en.variants.iter().all(|v| v.fields.is_empty());
    if all_unit {
        out.push_str(&format!("enum class {} {{\n", en.name));
        let names: Vec<String> = en.variants.iter().map(|v| to_screaming_snake(&v.name)).collect();
        for (idx, name) in names.iter().enumerate() {
            let comma = if idx + 1 == names.len() { ";" } else { "," };
            out.push_str(&format!("    {name}{comma}\n"));
        }
        out.push_str("}\n");
    } else {
        out.push_str(&format!("sealed class {} {{\n", en.name));
        for variant in &en.variants {
            if variant.fields.is_empty() {
                out.push_str(&format!("    object {} : {}()\n", variant.name, en.name));
            } else {
                out.push_str(&format!("    data class {}(\n", variant.name));
                for (idx, f) in variant.fields.iter().enumerate() {
                    let ty_str = native_type_str(&f.ty, f.optional);
                    let name = if f.name.is_empty() {
                        format!("field{idx}")
                    } else {
                        to_lower_camel(&f.name)
                    };
                    let comma = if idx + 1 == variant.fields.len() { "" } else { "," };
                    out.push_str(&format!("        val {name}: {ty_str}{comma}\n"));
                }
                out.push_str(&format!("    ) : {}()\n", en.name));
            }
        }
        out.push_str("}\n");
    }
}

fn emit_native_error(error: &ErrorDef, out: &mut String) {
    if !error.doc.is_empty() {
        for line in error.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!(
        "sealed class {}(message: String) : Exception(message) {{\n",
        error.name
    ));
    for variant in &error.variants {
        if variant.is_unit {
            out.push_str(&format!(
                "    object {} : {}(\"{}\")\n",
                variant.name,
                error.name,
                variant.message_template.as_deref().unwrap_or(&variant.name)
            ));
        } else {
            out.push_str(&format!("    data class {}(\n", variant.name));
            for (idx, f) in variant.fields.iter().enumerate() {
                let ty_str = native_type_str(&f.ty, f.optional);
                let name = to_lower_camel(&f.name);
                let comma = if idx + 1 == variant.fields.len() { "" } else { "," };
                out.push_str(&format!("        val {name}: {ty_str}{comma}\n"));
            }
            let message_template = variant.message_template.as_deref().unwrap_or(&variant.name);
            out.push_str(&format!("    ) : {}(\"{message_template}\")\n", error.name));
        }
    }
    out.push_str("}\n");
}

/// Emit a Kotlin/Native function body — exposed for `gen_mpp` to reuse.
pub(crate) fn emit_native_function_pub(f: &FunctionDef, prefix: &str, out: &mut String) {
    emit_native_function(f, prefix, out)
}

fn emit_native_function(f: &FunctionDef, prefix: &str, out: &mut String) {
    if !f.doc.is_empty() {
        for line in f.doc.lines() {
            out.push_str("    /// ");
            out.push_str(line);
            out.push('\n');
        }
    }

    let params: Vec<String> = f.params.iter().map(format_native_param).collect();
    let return_ty = native_return_type_str(&f.return_type);
    let func_name_camel = to_lower_camel(&f.name);

    let error_code_sym = c_consumer::last_error_code_symbol(prefix);
    let error_context_sym = c_consumer::last_error_context_symbol(prefix);
    let free_sym = c_consumer::free_string_symbol(prefix);
    let c_fn = format!("{prefix}_{}", f.name);

    out.push_str(&format!(
        "    fun {}({}): {} {{\n",
        func_name_camel,
        params.join(", "),
        return_ty
    ));
    out.push_str("        return memScoped {\n");

    // Emit C-string conversions for string/path parameters inside the memScoped block.
    for p in &f.params {
        emit_native_param_conversion(p, out);
    }

    // Build the C call argument list.
    let c_args: Vec<String> = f.params.iter().map(native_c_arg).collect();
    let call = format!("{c_fn}({})", c_args.join(", "));

    if f.error_type.is_some() {
        // Fallible: capture result, check error code, throw if non-zero.
        out.push_str(&format!("            val _result = {call}\n"));
        out.push_str(&format!("            val _code = {error_code_sym}()\n"));
        out.push_str("            if (_code != 0) {\n");
        out.push_str(&format!(
            "                val _msg = {error_context_sym}()?.toKString() ?: \"unknown error (code $_code)\"\n"
        ));
        out.push_str("                throw RuntimeException(_msg)\n");
        out.push_str("            }\n");
        if matches!(f.return_type, TypeRef::Unit) {
            out.push_str("            Unit\n");
        } else {
            let expr = native_unwrap_return("_result", &f.return_type, &free_sym);
            out.push_str(&format!("            {expr}\n"));
        }
    } else if matches!(f.return_type, TypeRef::Unit) {
        out.push_str(&format!("            {call}\n"));
        out.push_str("            Unit\n");
    } else {
        out.push_str(&format!("            val _result = {call}\n"));
        let expr = native_unwrap_return("_result", &f.return_type, &free_sym);
        out.push_str(&format!("            {expr}\n"));
    }

    out.push_str("        }\n");
    out.push_str("    }\n");
}

fn format_native_param(p: &ParamDef) -> String {
    let ty_str = native_param_type_str(&p.ty, p.optional);
    format!("{}: {}", to_lower_camel(&p.name), ty_str)
}

/// The Kotlin/Native type used at the wrapper boundary for a function parameter.
///
/// `String`, `Path`, `Bytes`, `Vec`, `Map` → `String` (caller supplies value;
/// String/Path are converted to `cstr`, Bytes/Vec/Map are passed as JSON strings).
fn native_param_type_str(ty: &TypeRef, optional: bool) -> String {
    let inner = match ty {
        TypeRef::String
        | TypeRef::Path
        | TypeRef::Char
        | TypeRef::Json
        | TypeRef::Vec(_)
        | TypeRef::Map(_, _) => "String".to_string(),
        TypeRef::Bytes => "ByteArray".to_string(),
        TypeRef::Optional(inner) => return format!("{}?", native_param_type_str(inner, false)),
        other => native_type_str(other, false),
    };
    if optional { format!("{inner}?") } else { inner }
}

/// Emit the `memScoped`-local conversion for a parameter before the C call.
fn emit_native_param_conversion(p: &ParamDef, out: &mut String) {
    let name = to_lower_camel(&p.name);
    match &p.ty {
        TypeRef::String
        | TypeRef::Path
        | TypeRef::Char
        | TypeRef::Json
        | TypeRef::Vec(_)
        | TypeRef::Map(_, _) => {
            out.push_str(&format!("            val {name}C = {name}.cstr.ptr\n"));
        }
        TypeRef::Bytes => {
            // Bytes: pin the ByteArray and pass pointer + length.
            out.push_str(&format!("            val {name}Pin = {name}.pin()\n"));
        }
        _ => {}
    }
}

/// The C argument expression for a parameter.
fn native_c_arg(p: &ParamDef) -> String {
    let name = to_lower_camel(&p.name);
    match &p.ty {
        TypeRef::String
        | TypeRef::Path
        | TypeRef::Char
        | TypeRef::Json
        | TypeRef::Vec(_)
        | TypeRef::Map(_, _) => format!("{name}C"),
        TypeRef::Bytes => format!("{name}Pin.addressOf(0), {name}.size"),
        _ => name,
    }
}

/// Produce the Kotlin expression that converts a raw C return value to the
/// Kotlin return type.
///
/// String-like returns: copy via `toKString()` then free the C allocation.
/// Everything else: pass through unchanged.
fn native_unwrap_return(raw: &str, ty: &TypeRef, free_sym: &str) -> String {
    match ty {
        TypeRef::String
        | TypeRef::Path
        | TypeRef::Char
        | TypeRef::Json
        | TypeRef::Vec(_)
        | TypeRef::Map(_, _) => {
            format!("run {{ val _s = {raw}!!.toKString(); {free_sym}({raw}); _s }}")
        }
        TypeRef::Bytes => {
            // Bytes: reconstruct a ByteArray from the returned pointer + length is not standard
            // in the simple C ABI; fall back to treating as a string for now.
            format!("run {{ val _s = {raw}!!.toKString().encodeToByteArray(); {free_sym}({raw}); _s }}")
        }
        _ => raw.to_string(),
    }
}

/// Kotlin/Native return type for a function (not for struct fields).
fn native_return_type_str(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Unit => "Unit".to_string(),
        TypeRef::String
        | TypeRef::Path
        | TypeRef::Char
        | TypeRef::Json
        | TypeRef::Vec(_)
        | TypeRef::Map(_, _) => "String".to_string(),
        TypeRef::Bytes => "ByteArray".to_string(),
        other => native_type_str(other, false),
    }
}

/// Kotlin/Native type for struct fields (same as JVM type; cinterop types are
/// used only inside function bodies, not in data class declarations).
fn native_type_str(ty: &TypeRef, optional: bool) -> String {
    use alef_core::ir::PrimitiveType;
    let inner = match ty {
        TypeRef::Primitive(p) => match p {
            PrimitiveType::Bool => "Boolean".to_string(),
            PrimitiveType::U8 | PrimitiveType::I8 => "Byte".to_string(),
            PrimitiveType::U16 | PrimitiveType::I16 => "Short".to_string(),
            PrimitiveType::U32 | PrimitiveType::I32 => "Int".to_string(),
            PrimitiveType::U64 | PrimitiveType::I64 | PrimitiveType::Usize | PrimitiveType::Isize => {
                "Long".to_string()
            }
            PrimitiveType::F32 => "Float".to_string(),
            PrimitiveType::F64 => "Double".to_string(),
        },
        TypeRef::String | TypeRef::Json => "String".to_string(),
        // Path is just String in Native mode — no java.nio.file.Path.
        TypeRef::Path => "String".to_string(),
        // Char: single Unicode codepoint, represented as a Kotlin Char.
        TypeRef::Char => "Char".to_string(),
        TypeRef::Bytes => "ByteArray".to_string(),
        TypeRef::Unit => "Unit".to_string(),
        TypeRef::Duration => "Long".to_string(),
        TypeRef::Named(name) => name.clone(),
        TypeRef::Optional(inner) => return format!("{}?", native_type_str(inner, false)),
        TypeRef::Vec(inner) => format!("List<{}>", native_type_str(inner, false)),
        TypeRef::Map(k, v) => format!("Map<{}, {}>", native_type_str(k, false), native_type_str(v, false)),
    };
    if optional { format!("{inner}?") } else { inner }
}

// ---------------------------------------------------------------------------
// cinterop .def file
// ---------------------------------------------------------------------------

fn emit_def_file(config: &AlefConfig) -> String {
    let header = config.ffi_header_name();
    let lib_name = config.ffi_lib_name();
    let prefix = config.ffi_prefix();

    format!(
        "headers = {header}\nheaderFilter = {prefix}_*\nlinkerOpts = -L../../../target/release -l{lib_name}\n"
    )
}

// ---------------------------------------------------------------------------
// build.gradle.kts
// ---------------------------------------------------------------------------

fn emit_gradle_build(config: &AlefConfig) -> String {
    let crate_name = &config.crate_config.name;
    let kotlin_version = template_versions::maven::KOTLIN_JVM_PLUGIN;

    format!(
        r#"// Generated by alef. Do not edit by hand.
// To build for a different host triple, replace `linuxX64()` with
// `macosX64()` or `macosArm64()` and update the linkerOpts path accordingly.

plugins {{
    kotlin("multiplatform") version "{kotlin_version}"
}}

kotlin {{
    linuxX64 {{
        compilations["main"].cinterops {{
            val {crate_name} by creating {{
                defFile = project.file("{crate_name}.def")
            }}
        }}
        binaries {{
            sharedLib()
        }}
    }}
}}
"#
    )
}
