use alef_core::backend::GeneratedFile;
use alef_core::config::AlefConfig;
use alef_core::ir::ApiSurface;
use std::path::PathBuf;

pub(crate) fn scaffold_gleam(api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
    let version = &api.version;
    let gleam_app = config.gleam_app_name();

    let gleam_toml = format!(
        r#"name = "{app_name}"
version = "{version}"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
"#,
        app_name = gleam_app,
        version = version,
    );

    let manifest_toml = "# This file is generated by gleam build\n# Do not manually edit\n";

    let gitignore = "build/\n";

    Ok(vec![
        GeneratedFile {
            path: PathBuf::from("packages/gleam/gleam.toml"),
            content: gleam_toml,
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from("packages/gleam/manifest.toml"),
            content: manifest_toml.to_string(),
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from("packages/gleam/.gitignore"),
            content: gitignore.to_string(),
            generated_header: false,
        },
    ])
}
