use alef_core::backend::GeneratedFile;
use alef_core::config::ResolvedCrateConfig;
use alef_core::ir::ApiSurface;
use std::path::PathBuf;

/// Scaffold the `<crate>-jni/Cargo.toml` for a JNI shim crate.
///
/// Emits a single `Cargo.toml` as a `cdylib` depending on `jni`, `tokio`,
/// `serde_json`, and `futures-util`.  The `<crate>` dependency path is
/// `../crate` inside the same workspace; features come from
/// `[crates.kotlin_android] features` if present.
pub(crate) fn scaffold_jni(api: &ApiSurface, config: &ResolvedCrateConfig) -> anyhow::Result<Vec<GeneratedFile>> {
    let core_crate_dir = config.core_crate_dir();
    let jni_crate_name = format!("{core_crate_dir}-jni");
    let jni_lib_name = jni_crate_name.replace('-', "_");

    // Prefer kotlin_android features, then empty.
    let features: Vec<String> = config
        .kotlin_android
        .as_ref()
        .and_then(|k| k.features.as_ref())
        .map(|f| f.iter().map(|s| format!("\"{s}\"")).collect())
        .unwrap_or_default();

    let features_str = if features.is_empty() {
        String::new()
    } else {
        format!(", features = [{}]", features.join(", "))
    };

    let content = format!(
        r#"# Generated by alef. Do not edit by hand.

[package]
name = "{jni_crate_name}"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "{jni_lib_name}"
crate-type = ["cdylib"]

[dependencies]
{core_crate_dir} = {{ path = "../{core_crate_dir}"{features_str} }}
futures-util = "0.3"
jni = "0.21"
serde_json = "1"
tokio = {{ version = "1", features = ["rt-multi-thread", "macros", "sync"] }}
"#,
        jni_crate_name = jni_crate_name,
        jni_lib_name = jni_lib_name,
        core_crate_dir = core_crate_dir,
        features_str = features_str,
    );

    let _ = api; // api not needed for Cargo.toml scaffold

    Ok(vec![GeneratedFile {
        path: PathBuf::from(format!("crates/{jni_crate_name}/Cargo.toml")),
        content,
        generated_header: false,
    }])
}
