use alef_core::backend::GeneratedFile;
use alef_core::config::AlefConfig;
use alef_core::ir::ApiSurface;
use std::path::PathBuf;

pub(crate) fn scaffold_swift(_api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
    let module = config.swift_module();
    // Strip the minor version component: "13.0" → "13", "16.0" → "16".
    // Swift PackageDescription uses e.g. `.v13` and `.v16`.
    let min_macos_major = config
        .swift_min_macos()
        .split('.')
        .next()
        .unwrap_or("13")
        .to_string();
    let min_ios_major = config
        .swift_min_ios()
        .split('.')
        .next()
        .unwrap_or("16")
        .to_string();

    // crate_name is e.g. "kreuzberg", the Cargo crate being wrapped.
    // The swift-bridge output files are named after the *binding* crate, e.g. "kreuzberg-swift".
    let crate_name = &config.crate_config.name;
    let binding_crate_name = format!("{crate_name}-swift");
    let binding_crate_underscore = binding_crate_name.replace('-', "_");

    let package_swift = format!(
        r#"// swift-tools-version: 5.9
import PackageDescription

// NOTE: Run `cargo build -p {binding_crate}` before `swift build`.
// That step generates Sources/RustBridge/{{RustBridge,SwiftBridgeCore}}.swift and RustBridge.h.
// See BUILDING.md for the full workflow.
let package = Package(
    name: "{module}",
    platforms: [
        .macOS(.v{min_macos}),
        .iOS(.v{min_ios}),
    ],
    products: [
        .library(name: "{module}", targets: ["{module}"]),
    ],
    targets: [
        // RustBridge: wraps the static library produced by `cargo build -p {binding_crate}`.
        // The Swift and C sources here are placeholders; `cargo build` populates them.
        .target(
            name: "RustBridge",
            path: "Sources/RustBridge",
            linkerSettings: [
                .linkedLibrary("{binding_crate_underscore}"),
                .unsafeFlags(["-L../../target/debug"]),
            ]
        ),
        .target(name: "{module}", dependencies: ["RustBridge"], path: "Sources/{module}"),
        .testTarget(name: "{module}Tests", dependencies: ["{module}"], path: "Tests/{module}Tests"),
    ]
)
"#,
        module = module,
        min_macos = min_macos_major,
        min_ios = min_ios_major,
        binding_crate = binding_crate_name,
        binding_crate_underscore = binding_crate_underscore,
    );

    let gitignore = ".build/\nPackages/\nxcuserdata/\nDerivedData/\n.swiftpm/\n*.xcodeproj\n";

    let test_stub = format!(
        r#"import XCTest
@testable import {module}

final class {module}Tests: XCTestCase {{
    func testPlaceholder() throws {{
        // Placeholder test so `swift test` has a target to run.
        // Replace or extend with real tests against the {module} module.
        XCTAssertTrue(true)
    }}
}}
"#,
        module = module,
    );

    // RustBridge placeholder header — real declarations are generated by swift-bridge-build
    // during `cargo build -p {binding_crate_name}` and copied into this directory.
    let rust_bridge_header = format!(
        r#"#ifndef RUST_BRIDGE_H
#define RUST_BRIDGE_H

// Placeholder header for the RustBridge SwiftPM target.
// Run `cargo build -p {binding_crate}` and copy the generated header here.
// See BUILDING.md for instructions.

#endif /* RUST_BRIDGE_H */
"#,
        binding_crate = binding_crate_name,
    );

    // module.modulemap exposes the C header to Swift as the RustBridge module.
    let module_modulemap = "module RustBridge {\n    header \"RustBridge.h\"\n    export *\n}\n";

    // RustBridge.swift placeholder — the target needs at least one Swift source.
    // Real content is copied from cargo build output; this file is overwritten.
    let rust_bridge_swift = format!(
        r#"// Placeholder Swift source for the RustBridge target.
// Run `cargo build -p {binding_crate}` and copy the generated Swift files here.
// See BUILDING.md for instructions.
//
// This file is intentionally minimal so SwiftPM accepts the target before
// the cargo build step has been run.
public enum RustBridgePlaceholder {{}}
"#,
        binding_crate = binding_crate_name,
    );

    let building_md = format!(
        r#"# Building {module}

The Swift package wraps a Rust library via [swift-bridge](https://github.com/chinedufn/swift-bridge).
SwiftPM cannot invoke Cargo directly, so you must run the cargo build step first.

## Workflow

### 1. Build the Rust binding crate

From the **repository root**:

```sh
cargo build -p {binding_crate}
```

This compiles `target/debug/lib{binding_crate_underscore}.a` and runs
`swift-bridge-build` in `build.rs`, which writes generated Swift and C sources
into `target/debug/build/{binding_crate}-*/out/`.

### 2. Copy generated sources into the SwiftPM target

```sh
# Locate the generated files (hash changes on dependency updates):
find target/debug/build -name "*.swift" -path "*{binding_crate}*"

# Copy Swift sources (RustBridge.swift, SwiftBridgeCore.swift, etc.):
cp target/debug/build/{binding_crate}-*/out/*.swift \
   packages/swift/Sources/RustBridge/

# Copy the generated C header:
cp target/debug/build/{binding_crate}-*/out/*.h \
   packages/swift/Sources/RustBridge/RustBridge.h
```

If the glob `{binding_crate}-*` matches multiple directories, pick the most
recently modified one.

### 3. Build and test the Swift package

```sh
cd packages/swift
swift build
swift test
```

## Release builds

Replace `target/debug` with `target/release` and pass
`--configuration release` to `swift build`:

```sh
cargo build --release -p {binding_crate}
cp target/release/build/{binding_crate}-*/out/*.swift \
   packages/swift/Sources/RustBridge/
cp target/release/build/{binding_crate}-*/out/*.h \
   packages/swift/Sources/RustBridge/RustBridge.h
swift build --package-path packages/swift --configuration release
```

## Notes

- `Sources/RustBridge/RustBridge.swift` and `RustBridge.h` are **generated
  artifacts** — do not edit them by hand.
- The `Sources/RustBridge/module.modulemap` exposes the C header to Swift and
  is **checked in** (it is not generated).
- `target/` is in `.gitignore`; regenerate after every `cargo clean`.
"#,
        module = module,
        binding_crate = binding_crate_name,
        binding_crate_underscore = binding_crate_underscore,
    );

    Ok(vec![
        GeneratedFile {
            path: PathBuf::from("packages/swift/Package.swift"),
            content: package_swift,
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from("packages/swift/.gitignore"),
            content: gitignore.to_string(),
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from(format!("packages/swift/Tests/{module}Tests/{module}Tests.swift")),
            content: test_stub,
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from("packages/swift/Sources/RustBridge/RustBridge.h"),
            content: rust_bridge_header,
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from("packages/swift/Sources/RustBridge/module.modulemap"),
            content: module_modulemap.to_string(),
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from("packages/swift/Sources/RustBridge/RustBridge.swift"),
            content: rust_bridge_swift,
            generated_header: false,
        },
        GeneratedFile {
            path: PathBuf::from("packages/swift/BUILDING.md"),
            content: building_md,
            generated_header: false,
        },
    ])
}
