//! `.editorconfig` emitter — provides per-project style + ktlint rule overrides.
//!
//! Generated Kotlin/Android projects co-locate the alef-emitted Java facade
//! inside the AAR's `src/main/java/<java_pkg>/` tree. The Java package is
//! derived from the umbrella crate's `repository` URL, which (for hyphenated
//! GitHub orgs such as `kreuzberg-dev`) introduces underscores in the
//! resulting reverse-DNS package name (e.g. `com.github.kreuzberg_dev`).
//! That trips ktlint's `standard:package-name` rule, which forbids
//! underscores. Since the package is determined upstream and constrained by
//! Java conventions, we disable that one rule for the generated tree rather
//! than rewrite every repository name. All other ktlint rules remain on.

/// Emit `.editorconfig` for the AAR project root.
pub fn emit() -> String {
    String::from(
        r#"# Generated by alef. Do not edit by hand.
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.kt]
indent_style = space
indent_size = 4
# Java packages derived from hyphenated GitHub orgs (e.g. `kreuzberg-dev` →
# `com.github.kreuzberg_dev`) carry underscores; allow them for the
# co-located Java facade and its Kotlin wrappers.
ktlint_standard_package-name = disabled

[*.gradle.kts]
indent_style = space
indent_size = 4

[*.{xml,pro,gitignore}]
indent_style = space
indent_size = 2
"#,
    )
}
