use alef_core::config::{AlefConfig, Language};
use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};
use tracing::info;

/// Markers that indicate a file was auto-generated by alef.
const ALEF_HEADER_MARKERS: &[&str] = &["auto-generated by alef", "AUTO-GENERATED by alef", "DO NOT EDIT"];

/// Clean up orphan alef-generated files that are no longer in the current generation output.
///
/// Walks each configured per-language output directory and removes files that:
/// 1. Have an alef-generated header marker in their first few lines
/// 2. Are NOT in the set of files generated in the current run
///
/// This prevents stale alef-emitted files from blocking builds when types are removed
/// from the public API.
pub fn cleanup_orphaned_files(
    config: &AlefConfig,
    current_gen_paths: &HashSet<PathBuf>,
    base_dir: &Path,
) -> anyhow::Result<usize> {
    let mut removed_count = 0;

    // Collect output directories from config for all non-FFI languages
    let output_dirs = [
        (Language::Python, config.output.python.as_ref()),
        (Language::Node, config.output.node.as_ref()),
        (Language::Ruby, config.output.ruby.as_ref()),
        (Language::Php, config.output.php.as_ref()),
        (Language::Elixir, config.output.elixir.as_ref()),
        (Language::Wasm, config.output.wasm.as_ref()),
        (Language::Ffi, config.output.ffi.as_ref()),
        (Language::Go, config.output.go.as_ref()),
        (Language::Java, config.output.java.as_ref()),
        (Language::Csharp, config.output.csharp.as_ref()),
        (Language::R, config.output.r.as_ref()),
    ];

    for (_, output_dir_opt) in &output_dirs {
        if let Some(output_dir) = output_dir_opt {
            let abs_output_dir = base_dir.join(output_dir);
            if !abs_output_dir.exists() {
                continue;
            }

            removed_count += cleanup_language_dir(&abs_output_dir, current_gen_paths)?;
        }
    }

    Ok(removed_count)
}

/// Walk a language output directory and remove orphaned alef-generated files.
fn cleanup_language_dir(dir: &Path, current_gen_paths: &HashSet<PathBuf>) -> anyhow::Result<usize> {
    let mut removed_count = 0;
    let mut paths = Vec::new();

    collect_paths(dir, &mut paths)?;

    for path in paths {
        // Skip directories
        if path.is_dir() {
            continue;
        }

        // Check if it has an alef header
        if has_alef_header(&path)? {
            // Check if it's in the current generation set
            let canonical_path = path.canonicalize().unwrap_or_else(|_| path.clone());
            if !current_gen_paths.contains(&canonical_path) {
                // It's an orphan; remove it
                info!("Removing stale alef-generated file: {}", path.display());
                fs::remove_file(&path)?;
                removed_count += 1;
            }
        }
    }

    Ok(removed_count)
}

/// Recursively collect all file paths in a directory.
fn collect_paths(dir: &Path, paths: &mut Vec<PathBuf>) -> anyhow::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        paths.push(path.clone());

        if path.is_dir() {
            collect_paths(&path, paths)?;
        }
    }
    Ok(())
}

/// Check if a file has an alef-generated header marker.
fn has_alef_header(path: &Path) -> anyhow::Result<bool> {
    // Read first ~2KB to check for header marker
    let content = match fs::read_to_string(path) {
        Ok(c) => c,
        Err(_) => {
            // If we can't read as UTF-8, skip it
            return Ok(false);
        }
    };

    // Check the first few lines for a marker
    let first_lines = content.lines().take(5).collect::<Vec<_>>().join("\n");

    for marker in ALEF_HEADER_MARKERS {
        if first_lines.contains(marker) {
            return Ok(true);
        }
    }

    Ok(false)
}
