use alef_codegen::type_mapper::TypeMapper;
use alef_core::backend::{Backend, BuildConfig, BuildDependency, Capabilities, GeneratedFile};
use alef_core::config::{AlefConfig, Language, resolve_output_dir};
use alef_core::ir::{ApiSurface, EnumDef, EnumVariant, ErrorDef, FieldDef, FunctionDef, ParamDef, TypeDef, TypeRef};
use heck::ToLowerCamelCase;
use std::collections::BTreeSet;
use std::path::PathBuf;

use crate::type_map::SwiftMapper;

pub struct SwiftBackend;

impl Backend for SwiftBackend {
    fn name(&self) -> &str {
        "swift"
    }

    fn language(&self) -> Language {
        Language::Swift
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: true,
            supports_classes: true,
            supports_enums: true,
            supports_option: true,
            supports_result: true,
            supports_callbacks: false,
            supports_streaming: false,
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let module_name = config.swift_module();
        let mapper = SwiftMapper;

        let mut imports: BTreeSet<String> = BTreeSet::new();
        // Foundation is always included — Codable, Data, URL all live there.
        imports.insert("import Foundation".to_string());

        let mut body = String::new();

        for ty in &api.types {
            emit_struct(ty, &mut body, &mapper);
            body.push('\n');
        }

        for en in &api.enums {
            emit_enum(en, &mut body, &mapper);
            body.push('\n');
        }

        for error in &api.errors {
            emit_error(error, &mut body, &mapper);
            body.push('\n');
        }

        if !api.functions.is_empty() {
            body.push_str(&format!("public enum {module_name} {{\n"));
            for f in &api.functions {
                emit_function(f, &mut body, &mapper);
                body.push('\n');
            }
            body.push_str("}\n");
        }

        let mut content = String::new();
        content.push_str("// Generated by alef. Do not edit by hand.\n\n");
        for import in &imports {
            content.push_str(import);
            content.push('\n');
        }
        content.push('\n');
        content.push_str(&body);

        let dir = resolve_output_dir(
            config.output.swift.as_ref(),
            &config.crate_config.name,
            &format!("Sources/{module_name}"),
        );
        let path = PathBuf::from(dir).join(format!("{module_name}.swift"));

        Ok(vec![GeneratedFile {
            path,
            content,
            generated_header: false,
        }])
    }

    fn build_config(&self) -> Option<BuildConfig> {
        Some(BuildConfig {
            tool: "swift",
            crate_suffix: "-swift",
            build_dep: BuildDependency::None,
            post_build: vec![],
        })
    }
}

/// Emits a Swift `public struct` for the given `TypeDef`.
fn emit_struct(ty: &TypeDef, out: &mut String, mapper: &SwiftMapper) {
    emit_doc_comment(&ty.doc, "", out);

    let codable = if ty.has_serde { ": Codable" } else { "" };

    if ty.fields.is_empty() {
        out.push_str(&format!("public struct {}{} {{}}\n", ty.name, codable));
        return;
    }

    out.push_str(&format!("public struct {}{} {{\n", ty.name, codable));

    // Stored properties
    for field in &ty.fields {
        emit_field_doc_comment(&field.doc, out);
        let ty_str = resolve_field_type(field, mapper);
        let name = field.name.to_lower_camel_case();
        out.push_str(&format!("    public let {name}: {ty_str}\n"));
    }

    // Memberwise initialiser (Swift structs do not expose their synthesised init as `public`)
    out.push('\n');
    let init_params: Vec<String> = ty
        .fields
        .iter()
        .map(|f| {
            let ty_str = resolve_field_type(f, mapper);
            let name = f.name.to_lower_camel_case();
            format!("{name}: {ty_str}")
        })
        .collect();
    out.push_str(&format!("    public init({}) {{\n", init_params.join(", ")));
    for field in &ty.fields {
        let name = field.name.to_lower_camel_case();
        out.push_str(&format!("        self.{name} = {name}\n"));
    }
    out.push_str("    }\n");
    out.push_str("}\n");
}

/// Resolves a `FieldDef`'s full Swift type string (handles optionality).
fn resolve_field_type(field: &FieldDef, mapper: &SwiftMapper) -> String {
    let base = mapper.map_type(&field.ty);
    if field.optional {
        format!("{base}?")
    } else {
        base
    }
}

/// Emits a Swift `public enum` for the given `EnumDef`.
fn emit_enum(en: &EnumDef, out: &mut String, mapper: &SwiftMapper) {
    emit_doc_comment(&en.doc, "", out);

    let all_unit = en.variants.iter().all(|v| v.fields.is_empty());

    if all_unit {
        out.push_str(&format!("public enum {} {{\n", en.name));
        for variant in &en.variants {
            emit_doc_comment(&variant.doc, "    ", out);
            let case_name = variant.name.to_lower_camel_case();
            out.push_str(&format!("    case {case_name}\n"));
        }
        out.push_str("}\n");
    } else {
        out.push_str(&format!("public enum {} {{\n", en.name));
        for variant in &en.variants {
            emit_variant_with_data(variant, out, mapper);
        }
        out.push_str("}\n");
    }
}

/// Emits a single enum case, with or without associated values.
fn emit_variant_with_data(variant: &EnumVariant, out: &mut String, mapper: &SwiftMapper) {
    emit_doc_comment(&variant.doc, "    ", out);
    let case_name = variant.name.to_lower_camel_case();
    if variant.fields.is_empty() {
        out.push_str(&format!("    case {case_name}\n"));
    } else {
        let assoc: Vec<String> = variant
            .fields
            .iter()
            .enumerate()
            .map(|(idx, f)| {
                let ty_str = mapper.map_type(&f.ty);
                let label = if f.name.is_empty() {
                    format!("field{idx}")
                } else {
                    f.name.to_lower_camel_case()
                };
                format!("{label}: {ty_str}")
            })
            .collect();
        out.push_str(&format!("    case {case_name}({})\n", assoc.join(", ")));
    }
}

/// Emits a Swift `Error`-conforming `public enum` for the given `ErrorDef`.
fn emit_error(error: &ErrorDef, out: &mut String, mapper: &SwiftMapper) {
    emit_doc_comment(&error.doc, "", out);
    out.push_str(&format!("public enum {}: Error {{\n", error.name));
    for variant in &error.variants {
        emit_doc_comment(&variant.doc, "    ", out);
        let case_name = variant.name.to_lower_camel_case();
        if variant.is_unit || variant.fields.is_empty() {
            out.push_str(&format!("    case {case_name}(message: String)\n"));
        } else {
            let mut assoc: Vec<String> = vec!["message: String".to_string()];
            for (idx, f) in variant.fields.iter().enumerate() {
                let ty_str = mapper.map_type(&f.ty);
                let label = if f.name.is_empty() {
                    format!("field{idx}")
                } else {
                    f.name.to_lower_camel_case()
                };
                assoc.push(format!("{label}: {ty_str}"));
            }
            out.push_str(&format!("    case {case_name}({})\n", assoc.join(", ")));
        }
    }
    out.push_str("}\n");
}

/// Emits a single `public static func` inside the module enum namespace.
fn emit_function(f: &FunctionDef, out: &mut String, mapper: &SwiftMapper) {
    emit_doc_comment(&f.doc, "    ", out);

    let params: Vec<String> = f.params.iter().map(|p| format_param(p, mapper)).collect();
    let return_ty = mapper.map_type(&f.return_type);

    let func_name = f.name.to_lower_camel_case();

    // Build the qualifier string: [async] [throws] [-> ReturnType]
    let mut qualifiers = String::new();
    if f.is_async {
        qualifiers.push_str("async ");
    }
    if f.error_type.is_some() {
        qualifiers.push_str("throws ");
    }
    // Omit `-> Void` per Swift convention.
    if !matches!(f.return_type, TypeRef::Unit) {
        qualifiers.push_str(&format!("-> {return_ty} "));
    }

    out.push_str(&format!(
        "    public static func {func_name}({}) {qualifiers}{{\n",
        params.join(", "),
    ));
    out.push_str("        // TODO: bridge to swift-bridge generated Rust functions\n");
    out.push_str("        fatalError(\"Stage 2C: bridge to swift-bridge\")\n");
    out.push_str("    }\n");
}

/// Formats a single parameter as `label: Type`.
fn format_param(p: &ParamDef, mapper: &SwiftMapper) -> String {
    let ty_str = mapper.map_type(&p.ty);
    let name = p.name.to_lower_camel_case();
    format!("{name}: {ty_str}")
}

/// Emits `/// <line>` doc-comment lines with the given indent prefix.
fn emit_doc_comment(doc: &str, indent: &str, out: &mut String) {
    if doc.is_empty() {
        return;
    }
    for line in doc.lines() {
        out.push_str(indent);
        out.push_str("/// ");
        out.push_str(line);
        out.push('\n');
    }
}

/// Emits field-level doc comments.
fn emit_field_doc_comment(doc: &str, out: &mut String) {
    emit_doc_comment(doc, "    ", out);
}
