//! Emits the Rust-side swift-bridge crate for Phase 2C.
//!
//! Three files are generated into `packages/swift/rust/`:
//! - `Cargo.toml` — declares the `cdylib`/`staticlib` crate with swift-bridge dependencies
//! - `src/lib.rs` — `#[swift_bridge::bridge] mod ffi { … }` plus wrapper newtypes and shims
//! - `build.rs` — calls `swift_bridge_build::parse_bridges` to run codegen at build time

use alef_core::backend::GeneratedFile;
use alef_core::config::AlefConfig;
use alef_core::ir::{ApiSurface, EnumDef, FunctionDef, PrimitiveType, TypeDef, TypeRef};
use alef_core::template_versions;
use heck::{ToSnakeCase, ToUpperCamelCase};
use std::path::PathBuf;

/// Top-level entry point: emit all three files for the swift-bridge crate.
pub fn emit(api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
    let base = PathBuf::from("packages/swift/rust");
    let crate_name = &api.crate_name;
    let version = &api.version;

    let swift_bridge_ver = template_versions::cargo::SWIFT_BRIDGE;
    let swift_bridge_build_ver = template_versions::cargo::SWIFT_BRIDGE_BUILD;
    let core_crate_dir = config.core_crate_dir();
    let same_as_workspace = core_crate_dir == *crate_name && config.crate_config.workspace_root.is_none();
    let core_path = if same_as_workspace {
        "../../..".to_string()
    } else {
        format!("../../../crates/{core_crate_dir}")
    };

    let cargo_toml = emit_cargo_toml(crate_name, version, swift_bridge_ver, swift_bridge_build_ver, &core_path);
    let lib_rs = emit_lib_rs(api, crate_name);
    let build_rs = emit_build_rs();

    Ok(vec![
        GeneratedFile {
            path: base.join("Cargo.toml"),
            content: cargo_toml,
            generated_header: false,
        },
        GeneratedFile {
            path: base.join("src/lib.rs"),
            content: lib_rs,
            generated_header: false,
        },
        GeneratedFile {
            path: base.join("build.rs"),
            content: build_rs,
            generated_header: false,
        },
    ])
}

// ── Cargo.toml ────────────────────────────────────────────────────────────────

fn emit_cargo_toml(
    crate_name: &str,
    version: &str,
    swift_bridge_ver: &str,
    swift_bridge_build_ver: &str,
    core_path: &str,
) -> String {
    let source_crate_name = crate_name.replace('-', "_");
    format!(
        r#"# Generated by alef. Do not edit by hand.
[package]
name = "{crate_name}-swift"
version = "{version}"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
{source_crate_name} = {{ path = "{core_path}" }}
swift-bridge = "{swift_bridge_ver}"

[build-dependencies]
swift-bridge-build = "{swift_bridge_build_ver}"
"#
    )
}

// ── build.rs ──────────────────────────────────────────────────────────────────

fn emit_build_rs() -> String {
    r#"// Generated by alef. Do not edit by hand.
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR unset"));
    let crate_name = std::env::var("CARGO_PKG_NAME").expect("CARGO_PKG_NAME unset");
    let bridges = vec!["src/lib.rs"];
    swift_bridge_build::parse_bridges(bridges).write_all_concatenated(out_dir, &crate_name);
    println!("cargo:rerun-if-changed=src/lib.rs");
}
"#
    .to_string()
}

// ── lib.rs ────────────────────────────────────────────────────────────────────

fn emit_lib_rs(api: &ApiSurface, crate_name: &str) -> String {
    let source_crate = crate_name.replace('-', "_");

    let mut out = String::new();
    out.push_str("// Generated by alef. Do not edit by hand.\n\n");

    // Collect extern "Rust" blocks for the ffi module
    let mut extern_blocks: Vec<String> = Vec::new();

    // One extern block per type
    for ty in &api.types {
        extern_blocks.push(emit_extern_block_for_type(ty));
    }

    // One extern block per enum
    for en in &api.enums {
        extern_blocks.push(emit_extern_block_for_enum(en));
    }

    // Free functions block (if any)
    if !api.functions.is_empty() {
        extern_blocks.push(emit_extern_block_for_functions(&api.functions));
    }

    // Emit the bridge module
    out.push_str("#[swift_bridge::bridge]\nmod ffi {\n");
    for block in &extern_blocks {
        out.push_str(block);
    }
    out.push_str("}\n\n");

    // Emit wrapper newtypes and impls for types
    for ty in &api.types {
        out.push_str(&emit_type_wrapper(ty, &source_crate));
        out.push('\n');
    }

    // Emit wrapper enums for enums
    for en in &api.enums {
        out.push_str(&emit_enum_wrapper(en, &source_crate));
        out.push('\n');
    }

    // Emit free-function shims
    for f in &api.functions {
        out.push_str(&emit_function_shim(f, &source_crate));
        out.push('\n');
    }

    out
}

// ── extern block emitters ─────────────────────────────────────────────────────

fn emit_extern_block_for_type(ty: &TypeDef) -> String {
    let mut block = String::new();
    block.push_str("    extern \"Rust\" {\n");
    block.push_str(&format!("        type {};\n", ty.name));

    // Constructor
    if !ty.fields.is_empty() {
        let params: Vec<String> = ty
            .fields
            .iter()
            .map(|f| {
                let rust_ty = swift_bridge_rust_type(&f.ty);
                let name = f.name.to_snake_case();
                format!("{name}: {rust_ty}")
            })
            .collect();
        block.push_str("        #[swift_bridge(init)]\n");
        block.push_str(&format!(
            "        fn new({}) -> {};\n",
            params.join(", "),
            ty.name
        ));
    }

    // Getters
    for field in &ty.fields {
        let rust_ty = swift_bridge_rust_type(&field.ty);
        let name = field.name.to_snake_case();
        block.push_str(&format!("        fn {name}(&self) -> {rust_ty};\n"));
    }

    block.push_str("    }\n\n");
    block
}

fn emit_extern_block_for_enum(en: &EnumDef) -> String {
    let mut block = String::new();
    block.push_str("    extern \"Rust\" {\n");
    block.push_str(&format!("        type {};\n", en.name));
    block.push_str("    }\n\n");
    block
}

fn emit_extern_block_for_functions(functions: &[FunctionDef]) -> String {
    let mut block = String::new();
    block.push_str("    extern \"Rust\" {\n");

    for f in functions {
        // swift-bridge v0.1.59 has no `async` attribute or `async fn` support
        // inside extern blocks. Async functions emit a sync placeholder + a
        // `// TODO(swift-bridge async)` marker for users to fill in via the
        // callback-based pattern. See https://chinedufn.github.io/swift-bridge/
        if f.is_async {
            block.push_str(&format!(
                "        // TODO(swift-bridge async): function `{}` is async; swift-bridge\n",
                f.name
            ));
            block.push_str(
                "        // 0.1.x has no async-extern support — wire via callback bridging.\n",
            );
        }

        let fn_name = f.name.to_snake_case();
        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                let rust_ty = swift_bridge_rust_type(&p.ty);
                let name = p.name.to_snake_case();
                format!("{name}: {rust_ty}")
            })
            .collect();
        let params_str = params.join(", ");

        let return_ty = if f.error_type.is_some() {
            // Result<ReturnType, String> for error-throwing functions
            let ok_ty = swift_bridge_rust_type(&f.return_type);
            if matches!(f.return_type, TypeRef::Unit) {
                "Result<(), String>".to_string()
            } else {
                format!("Result<{ok_ty}, String>")
            }
        } else {
            swift_bridge_rust_type(&f.return_type)
        };

        block.push_str(&format!(
            "        fn {fn_name}({params_str}) -> {return_ty};\n"
        ));
    }

    block.push_str("    }\n\n");
    block
}

// ── wrapper type emitters ─────────────────────────────────────────────────────

fn emit_type_wrapper(ty: &TypeDef, source_crate: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "pub struct {}(pub {}::{});\n\n",
        ty.name, source_crate, ty.name
    ));

    if !ty.fields.is_empty() {
        out.push_str(&format!("impl {} {{\n", ty.name));

        // Constructor
        let params: Vec<String> = ty
            .fields
            .iter()
            .map(|f| {
                let rust_ty = swift_bridge_rust_type(&f.ty);
                let name = f.name.to_snake_case();
                format!("{name}: {rust_ty}")
            })
            .collect();
        let field_inits: Vec<String> = ty
            .fields
            .iter()
            .map(|f| {
                let name = f.name.to_snake_case();
                format!("            {name}")
            })
            .collect();
        out.push_str(&format!(
            "    pub fn new({}) -> {} {{\n",
            params.join(", "),
            ty.name
        ));
        out.push_str(&format!(
            "        {}({}::{} {{\n",
            ty.name, source_crate, ty.name
        ));
        for init in &field_inits {
            out.push_str(init);
            out.push_str(",\n");
        }
        out.push_str("        })\n");
        out.push_str("    }\n");

        // Getters
        for field in &ty.fields {
            let rust_ty = swift_bridge_rust_type(&field.ty);
            let name = field.name.to_snake_case();
            out.push_str(&format!(
                "    pub fn {name}(&self) -> {rust_ty} {{ self.0.{name} }}\n"
            ));
        }

        out.push_str("}\n");
    }

    out
}

fn emit_enum_wrapper(en: &EnumDef, source_crate: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("pub enum {} {{\n", en.name));
    for variant in &en.variants {
        let variant_name = variant.name.to_upper_camel_case();
        out.push_str(&format!("    {variant_name},\n"));
    }
    out.push_str("}\n\n");

    // From conversion
    out.push_str(&format!(
        "impl From<{}::{}> for {} {{\n",
        source_crate, en.name, en.name
    ));
    out.push_str(&format!(
        "    fn from(val: {}::{}) -> Self {{\n",
        source_crate, en.name
    ));
    out.push_str("        match val {\n");
    for variant in &en.variants {
        let variant_name = variant.name.to_upper_camel_case();
        out.push_str(&format!(
            "            {}::{}::{} => Self::{},\n",
            source_crate, en.name, variant_name, variant_name
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

// ── function shim emitters ────────────────────────────────────────────────────

fn emit_function_shim(f: &FunctionDef, source_crate: &str) -> String {
    let fn_name = f.name.to_snake_case();
    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| {
            let rust_ty = swift_bridge_rust_type(&p.ty);
            let name = p.name.to_snake_case();
            format!("{name}: {rust_ty}")
        })
        .collect();
    let params_str = params.join(", ");

    let return_ty = if f.error_type.is_some() {
        let ok_ty = swift_bridge_rust_type(&f.return_type);
        if matches!(f.return_type, TypeRef::Unit) {
            "Result<(), String>".to_string()
        } else {
            format!("Result<{ok_ty}, String>")
        }
    } else {
        swift_bridge_rust_type(&f.return_type)
    };

    let call_args: Vec<String> = f
        .params
        .iter()
        .map(|p| p.name.to_snake_case())
        .collect();
    let call_args_str = call_args.join(", ");

    // Resolve the source call via the IR's full rust_path so module-prefixed
    // functions (e.g. `my_lib::utils::helper`) generate correct shim calls.
    // Falls back to the bare fn name if rust_path is empty.
    let resolved_path = if f.rust_path.is_empty() {
        format!("{source_crate}::{fn_name}")
    } else {
        f.rust_path.replace('-', "_")
    };
    let source_call = format!("{resolved_path}({call_args_str})");

    let body = if f.error_type.is_some() {
        format!("{source_call}.map_err(|e| e.to_string())")
    } else {
        source_call
    };

    if f.is_async {
        // swift-bridge v0.1.59 cannot expose `async fn` directly in extern blocks.
        // The wrapper compiles for non-bridge use; the extern block above carries
        // a TODO marker pointing to swift-bridge callback-based async wiring.
        format!(
            "pub async fn {fn_name}({params_str}) -> {return_ty} {{\n    {body}.await\n}}\n"
        )
    } else {
        format!("pub fn {fn_name}({params_str}) -> {return_ty} {{\n    {body}\n}}\n")
    }
}

// ── type mapping for swift-bridge Rust side ───────────────────────────────────

/// Maps an IR `TypeRef` to the Rust type string used in swift-bridge extern blocks.
///
/// swift-bridge's Rust side uses plain Rust types — NOT Swift types.
/// All integer widths are preserved (swift-bridge supports i8..i64, u8..u64).
/// Named types are left as-is (they are the wrapper newtypes defined below the bridge mod).
fn swift_bridge_rust_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Primitive(p) => rust_primitive_str(p).to_string(),
        TypeRef::String => "String".to_string(),
        TypeRef::Char => "char".to_string(),
        TypeRef::Bytes => "Vec<u8>".to_string(),
        TypeRef::Path => "String".to_string(),
        TypeRef::Json => "String".to_string(),
        TypeRef::Unit => "()".to_string(),
        TypeRef::Duration => "u64".to_string(),
        TypeRef::Optional(inner) => format!("Option<{}>", swift_bridge_rust_type(inner)),
        TypeRef::Vec(inner) => format!("Vec<{}>", swift_bridge_rust_type(inner)),
        TypeRef::Map(k, v) => {
            // swift-bridge does not natively support HashMap; use a String representation
            // The caller should handle this — we emit a best-effort type.
            format!("std::collections::HashMap<{}, {}>", swift_bridge_rust_type(k), swift_bridge_rust_type(v))
        }
        TypeRef::Named(name) => name.clone(),
    }
}

fn rust_primitive_str(p: &PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::Bool => "bool",
        PrimitiveType::U8 => "u8",
        PrimitiveType::I8 => "i8",
        PrimitiveType::U16 => "u16",
        PrimitiveType::I16 => "i16",
        PrimitiveType::U32 => "u32",
        PrimitiveType::I32 => "i32",
        PrimitiveType::U64 => "u64",
        PrimitiveType::I64 => "i64",
        PrimitiveType::Usize => "usize",
        PrimitiveType::Isize => "isize",
        PrimitiveType::F32 => "f32",
        PrimitiveType::F64 => "f64",
    }
}
