//! Emits the Rust-side swift-bridge crate for Phase 2C.
//!
//! Three files are generated into `packages/swift/rust/`:
//! - `Cargo.toml` — declares the `cdylib`/`staticlib` crate with swift-bridge dependencies
//! - `src/lib.rs` — `#[swift_bridge::bridge] mod ffi { … }` plus wrapper newtypes and shims
//! - `build.rs` — calls `swift_bridge_build::parse_bridges` to run codegen at build time

use alef_codegen::generators::type_paths::{build_type_path_lookup, resolve_type_path};
use alef_core::backend::GeneratedFile;
use alef_core::config::{AlefConfig, TraitBridgeConfig};
use alef_core::ir::{ApiSurface, EnumDef, FunctionDef, MethodDef, PrimitiveType, TypeDef, TypeRef};
use alef_core::keywords::swift_ident;
use alef_core::template_versions;
use heck::ToSnakeCase;
use std::collections::{HashMap, HashSet};
use std::path::PathBuf;

/// Top-level entry point: emit all three files for the swift-bridge crate.
pub fn emit(api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
    let base = PathBuf::from("packages/swift/rust");
    let crate_name = &api.crate_name;
    let version = &api.version;

    let swift_bridge_ver = template_versions::cargo::SWIFT_BRIDGE;
    let swift_bridge_build_ver = template_versions::cargo::SWIFT_BRIDGE_BUILD;
    let core_crate_dir = config.core_crate_dir();
    let same_as_workspace = core_crate_dir == *crate_name && config.crate_config.workspace_root.is_none();
    let core_path = if same_as_workspace {
        "../../..".to_string()
    } else {
        format!("../../../crates/{core_crate_dir}")
    };

    let features = config.features_for_language(alef_core::config::extras::Language::Swift);
    let exclude_functions: std::collections::HashSet<String> = config
        .swift
        .as_ref()
        .map(|c| c.exclude_functions.iter().cloned().collect())
        .unwrap_or_default();
    let exclude_types: std::collections::HashSet<String> = config
        .swift
        .as_ref()
        .map(|c| c.exclude_types.iter().cloned().collect())
        .unwrap_or_default();
    let exclude_fields: std::collections::HashSet<String> = config
        .swift
        .as_ref()
        .map(|c| c.exclude_fields.iter().cloned().collect())
        .unwrap_or_default();
    let cargo_toml = emit_cargo_toml(crate_name, version, swift_bridge_ver, swift_bridge_build_ver, &core_path, features);
    let lib_rs = emit_lib_rs(api, config, crate_name, &exclude_functions, &exclude_types, &exclude_fields);
    let build_rs = emit_build_rs();

    Ok(vec![
        GeneratedFile {
            path: base.join("Cargo.toml"),
            content: cargo_toml,
            generated_header: false,
        },
        GeneratedFile {
            path: base.join("src/lib.rs"),
            content: lib_rs,
            generated_header: false,
        },
        GeneratedFile {
            path: base.join("build.rs"),
            content: build_rs,
            generated_header: false,
        },
    ])
}

// ── Cargo.toml ────────────────────────────────────────────────────────────────

fn emit_cargo_toml(
    crate_name: &str,
    version: &str,
    swift_bridge_ver: &str,
    swift_bridge_build_ver: &str,
    core_path: &str,
    features: &[String],
) -> String {
    let source_crate_name = crate_name.replace('-', "_");
    let features_block = if features.is_empty() {
        String::new()
    } else {
        let list = features
            .iter()
            .map(|f| format!("\"{f}\""))
            .collect::<Vec<_>>()
            .join(", ");
        format!(", features = [{list}]")
    };
    format!(
        r#"# Generated by alef. Do not edit by hand.
[package]
name = "{crate_name}-swift"
version = "{version}"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
{source_crate_name} = {{ path = "{core_path}"{features_block} }}
serde_json = "1"
tokio = {{ version = "1", features = ["rt", "macros"] }}
swift-bridge = "{swift_bridge_ver}"

[build-dependencies]
swift-bridge-build = "{swift_bridge_build_ver}"
"#
    )
}

// ── build.rs ──────────────────────────────────────────────────────────────────

fn emit_build_rs() -> String {
    r#"// Generated by alef. Do not edit by hand.
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR unset"));
    let crate_name = std::env::var("CARGO_PKG_NAME").expect("CARGO_PKG_NAME unset");
    let bridges = vec!["src/lib.rs"];
    swift_bridge_build::parse_bridges(bridges).write_all_concatenated(out_dir, &crate_name);
    println!("cargo:rerun-if-changed=src/lib.rs");
}
"#
    .to_string()
}

// ── lib.rs ────────────────────────────────────────────────────────────────────

fn emit_lib_rs(
    api: &ApiSurface,
    config: &AlefConfig,
    crate_name: &str,
    exclude_functions: &HashSet<String>,
    exclude_types: &HashSet<String>,
    exclude_fields: &HashSet<String>,
) -> String {
    let source_crate = crate_name.replace('-', "_");

    // Build lookup from short type name → fully-qualified rust_path.
    // This resolves Bug A: types living at sub-module paths (e.g.
    // `kreuzberg::extraction::docx::drawing::AnchorProperties`) were previously
    // emitted as `kreuzberg::AnchorProperties` because the codegen used only
    // `{source_crate}::{name}`. The lookup uses the IR's `rust_path` field which
    // carries the full path as extracted from source.
    let type_paths = build_type_path_lookup(api);

    let mut out = String::new();
    // Fallback constructor bodies (no Default impl) and enum-field constructors
    // intentionally drop their parameters — they call unimplemented!() or leave
    // fields at Default::default(). batch_extract_bytes* shims embed an
    // unimplemented!() block as a function argument, making later arguments
    // unreachable. Suppress the resulting noise crate-wide; all real functions
    // use every parameter they declare and have reachable code paths.
    out.push_str("// Generated by alef. Do not edit by hand.\n\n");
    out.push_str("#![allow(unused_variables, unreachable_code)]\n\n");

    let visible_types: Vec<&TypeDef> = api
        .types
        .iter()
        .filter(|t| !exclude_types.contains(&t.name) && !t.is_trait)
        .collect();
    let visible_enums: Vec<&EnumDef> = api
        .enums
        .iter()
        .filter(|e| !exclude_types.contains(&e.name))
        .collect();
    let visible_functions: Vec<&FunctionDef> = api
        .functions
        .iter()
        .filter(|f| !exclude_functions.contains(&f.name))
        .collect();

    // Set of enum names (not struct names) so wrappers can use the correct
    // conversion idiom: `T::from(val)` for enums, `T(val)` for struct newtypes.
    let enum_names: HashSet<&str> = visible_enums.iter().map(|e| e.name.as_str()).collect();

    // Set of type names that do NOT implement serde (Serialize + Deserialize).
    // These cannot be JSON-bridged and must use unimplemented!() placeholders
    // when they appear as inner Named types in Optional/Vec fields or return types.
    let no_serde_names: HashSet<&str> = api
        .types
        .iter()
        .filter(|t| !t.has_serde)
        .map(|t| t.name.as_str())
        .collect();

    // Collect trait bridge definitions for configured traits.
    // Only traits listed in config.trait_bridges and present in the IR (is_trait=true)
    // are included. The Swift host side (Swift protocol + class conformance) is a
    // follow-up; here we only emit the Rust-side Box<dyn Trait> wrapper and trampolines.
    let active_bridges: Vec<(&TraitBridgeConfig, &TypeDef)> = config
        .trait_bridges
        .iter()
        .filter(|b| !b.exclude_languages.iter().any(|l| l == "swift"))
        .filter_map(|b| {
            api.types
                .iter()
                .find(|t| t.is_trait && t.name == b.trait_name)
                .map(|t| (b, t))
        })
        .collect();

    // Collect extern "Rust" blocks for the ffi module
    let mut extern_blocks: Vec<String> = Vec::new();
    for ty in &visible_types {
        extern_blocks.push(emit_extern_block_for_type(ty, exclude_fields));
    }
    for en in &visible_enums {
        extern_blocks.push(emit_extern_block_for_enum(en));
    }
    if !visible_functions.is_empty() {
        // Build a Vec<FunctionDef> so the existing emitter API is reused.
        let visible: Vec<FunctionDef> = visible_functions.iter().map(|f| (*f).clone()).collect();
        extern_blocks.push(emit_extern_block_for_functions(&visible));
    }
    // Trait bridge extern blocks — one per configured bridge.
    for (_bridge_cfg, trait_def) in &active_bridges {
        extern_blocks.push(emit_extern_block_for_trait_bridge(trait_def));
    }

    out.push_str("#[swift_bridge::bridge]\nmod ffi {\n");
    for block in &extern_blocks {
        out.push_str(block);
    }
    out.push_str("}\n\n");

    for ty in &visible_types {
        out.push_str(&emit_type_wrapper(ty, &source_crate, &type_paths, &enum_names, &no_serde_names, exclude_fields));
        out.push('\n');
    }
    for en in &visible_enums {
        out.push_str(&emit_enum_wrapper(en, &source_crate, &type_paths));
        out.push('\n');
    }
    for f in &visible_functions {
        out.push_str(&emit_function_shim(f, &source_crate, &type_paths, &enum_names, &no_serde_names));
        out.push('\n');
    }
    // Trait bridge wrapper structs and trampolines.
    for (_bridge_cfg, trait_def) in &active_bridges {
        out.push_str(&emit_trait_bridge_wrapper(trait_def, &source_crate, &enum_names));
        out.push('\n');
    }

    out
}

// ── extern block emitters ─────────────────────────────────────────────────────

fn emit_extern_block_for_type(ty: &TypeDef, exclude_fields: &HashSet<String>) -> String {
    let mut block = String::new();
    block.push_str("    extern \"Rust\" {\n");
    block.push_str(&format!("        type {};\n", ty.name));

    // Constructor — use bridge_type to avoid nested generics that swift-bridge 0.1.59
    // cannot parse (Vec<Vec<T>>, HashMap<K,V>); those become String (JSON).
    // Excluded fields are omitted from the constructor params.
    if !ty.fields.is_empty() {
        let params: Vec<String> = ty
            .fields
            .iter()
            .filter(|f| {
                let field_key = format!("{}.{}", ty.name, f.name.to_snake_case());
                !exclude_fields.contains(&field_key)
            })
            .map(|f| {
                let bridge_ty = bridge_type(&f.ty);
                let bridge_ty = if f.optional && !needs_json_bridge(&f.ty) {
                    format!("Option<{bridge_ty}>")
                } else {
                    bridge_ty
                };
                let name = f.name.to_snake_case();
                format!("{name}: {bridge_ty}")
            })
            .collect();
        block.push_str("        #[swift_bridge(init)]\n");
        block.push_str(&format!(
            "        fn new({}) -> {};\n",
            params.join(", "),
            ty.name
        ));
    }

    // Getters — excluded fields still get a getter declaration (the impl emits unimplemented!()).
    for field in &ty.fields {
        let bridge_ty = bridge_type(&field.ty);
        let bridge_ty = if field.optional && !needs_json_bridge(&field.ty) {
            format!("Option<{bridge_ty}>")
        } else {
            bridge_ty
        };
        let name = field.name.to_snake_case();
        block.push_str(&format!("        fn {name}(&self) -> {bridge_ty};\n"));
    }

    block.push_str("    }\n\n");
    block
}

fn emit_extern_block_for_enum(en: &EnumDef) -> String {
    let mut block = String::new();
    block.push_str("    extern \"Rust\" {\n");
    block.push_str(&format!("        type {};\n", en.name));
    block.push_str("    }\n\n");
    block
}

fn emit_extern_block_for_functions(functions: &[FunctionDef]) -> String {
    let mut block = String::new();
    block.push_str("    extern \"Rust\" {\n");

    for f in functions {
        // Escape Swift reserved keywords; swift-bridge emits the bridge fn name
        // verbatim into Swift, so `fn subscript(...)` would become invalid Swift.
        let fn_name = swift_ident(&f.name.to_snake_case());
        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                let bridge_ty = bridge_type(&p.ty);
                let bridge_ty = if p.optional {
                    format!("Option<{bridge_ty}>")
                } else {
                    bridge_ty
                };
                let name = swift_ident(&p.name.to_snake_case());
                format!("{name}: {bridge_ty}")
            })
            .collect();
        let params_str = params.join(", ");

        let return_ty = if f.error_type.is_some() {
            // Result<ReturnType, String> for error-throwing functions
            let ok_ty = bridge_type(&f.return_type);
            if matches!(f.return_type, TypeRef::Unit) {
                "Result<(), String>".to_string()
            } else {
                format!("Result<{ok_ty}, String>")
            }
        } else {
            bridge_type(&f.return_type)
        };

        // swift-bridge 0.1.59 does not support the `#[swift_bridge(async)]`
        // attribute (the build script's parser rejects it). To bridge async
        // functions, we declare them as plain `fn` in the extern block — the
        // wrapper will block on the future at the bridge boundary.
        block.push_str(&format!(
            "        fn {fn_name}({params_str}) -> {return_ty};\n"
        ));
    }

    block.push_str("    }\n\n");
    block
}

/// Emit the `extern "Rust"` block for a trait bridge.
///
/// Declares an opaque `{Trait}Box` type plus one free trampoline function per method:
/// `fn {trait_snake}_call_{method}(this: &{Trait}Box, args…) -> ret`.
/// All parameter/return types are flattened to swift-bridge-safe types (primitives,
/// String, Vec<leaf>). Complex types (Named, Optional, Map, Vec<non-leaf>) are JSON-bridged.
fn emit_extern_block_for_trait_bridge(trait_def: &TypeDef) -> String {
    let mut block = String::new();
    block.push_str("    extern \"Rust\" {\n");
    block.push_str(&format!("        type {}Box;\n", trait_def.name));

    let trait_snake = heck::AsSnakeCase(trait_def.name.as_str()).to_string();
    for method in &trait_def.methods {
        let method_name = method.name.to_snake_case();
        let fn_name = format!("{trait_snake}_call_{method_name}");

        let mut params = vec!["this: &".to_string() + &format!("{}Box", trait_def.name)];
        for p in &method.params {
            let bridge_ty = bridge_type_for_trait_method(&p.ty);
            let name = p.name.to_snake_case();
            params.push(format!("{name}: {bridge_ty}"));
        }

        let return_ty = if method.error_type.is_some() {
            let ok_ty = bridge_type_for_trait_method(&method.return_type);
            if matches!(method.return_type, TypeRef::Unit) {
                "Result<(), String>".to_string()
            } else {
                format!("Result<{ok_ty}, String>")
            }
        } else {
            bridge_type_for_trait_method(&method.return_type)
        };

        let params_str = params.join(", ");
        block.push_str(&format!("        fn {fn_name}({params_str}) -> {return_ty};\n"));
    }

    block.push_str("    }\n\n");
    block
}

/// Emit the Rust wrapper struct and trampoline functions for a trait bridge.
///
/// Emits:
/// - `pub struct {Trait}Box(pub Box<dyn source_crate::path::Trait + Send + Sync>);`
/// - For each method: a `pub fn {trait_snake}_call_{method}(this: &{Trait}Box, …) -> ret`
///   that delegates to `this.0.{method}(…)`.
/// - Async methods block on a current-thread Tokio runtime (same as async function shims).
fn emit_trait_bridge_wrapper<'a>(trait_def: &TypeDef, source_crate: &str, enum_names: &HashSet<&'a str>) -> String {
    let mut out = String::new();
    let trait_name = &trait_def.name;
    let trait_snake = heck::AsSnakeCase(trait_name.as_str()).to_string();

    // Derive the fully-qualified dyn trait path from rust_path (e.g. kreuzberg::plugins::OcrBackend).
    let trait_path = if trait_def.rust_path.is_empty() {
        format!("{source_crate}::{trait_name}")
    } else {
        trait_def.rust_path.replace('-', "_")
    };

    out.push_str(&format!(
        "pub struct {trait_name}Box(pub Box<dyn {trait_path} + Send + Sync>);\n\n"
    ));

    for method in &trait_def.methods {
        let method_name = method.name.to_snake_case();
        let fn_name = format!("{trait_snake}_call_{method_name}");

        // Build parameter list for the trampoline signature.
        // When a parameter needs to be passed as &mut to the trait, declare it `mut`
        // in the function signature so we can borrow mutably from the local binding.
        let mut sig_params = vec![format!("this: &{trait_name}Box")];
        for p in &method.params {
            let bridge_ty = bridge_type_for_trait_method(&p.ty);
            let name = p.name.to_snake_case();
            // Declare `mut` when the trait method takes `&mut` (is_mut=true on a Named type).
            let needs_mut = p.is_mut && matches!(p.ty, TypeRef::Named(_));
            if needs_mut {
                sig_params.push(format!("mut {name}: {bridge_ty}"));
            } else {
                sig_params.push(format!("{name}: {bridge_ty}"));
            }
        }
        let sig_params_str = sig_params.join(", ");

        let return_ty = if method.error_type.is_some() {
            let ok_ty = bridge_type_for_trait_method(&method.return_type);
            if matches!(method.return_type, TypeRef::Unit) {
                "Result<(), String>".to_string()
            } else {
                format!("Result<{ok_ty}, String>")
            }
        } else {
            bridge_type_for_trait_method(&method.return_type)
        };

        // Build the call arguments — convert bridge types back to what the trait expects.
        let call_args: Vec<String> = method.params.iter().map(|p| trait_call_arg(p)).collect();
        let call_args_str = call_args.join(", ");
        let source_call = format!("this.0.{method_name}({call_args_str})");

        let body = emit_trait_method_body(method, &source_call, &return_ty, enum_names);

        out.push_str(&format!(
            "pub fn {fn_name}({sig_params_str}) -> {return_ty} {{\n{body}}}\n\n"
        ));
    }

    out
}

/// Bridge type for trait method parameters/return types.
/// All Named types, Optional types, Vec<non-leaf>, and Map types are JSON-bridged (String).
/// This matches `bridge_type` but applied to trait method contexts.
fn bridge_type_for_trait_method(ty: &TypeRef) -> String {
    bridge_type(ty)
}

/// Build the call-site argument expression for a trait method parameter.
/// JSON-bridged params are deserialized; Path params are converted to PathBuf/Path;
/// Named types are passed through directly (they are not bridge wrappers in trait context).
fn trait_call_arg(p: &alef_core::ir::ParamDef) -> String {
    let name = p.name.to_snake_case();

    // JSON-bridged types: deserialize from the bridged String.
    if needs_json_bridge(&p.ty) {
        let native_ty = swift_bridge_rust_type(&p.ty);
        let deser = format!("serde_json::from_str::<{native_ty}>(&{name}).expect(\"valid JSON for {name}\")");
        if p.is_ref {
            return format!("&{deser}");
        }
        return deser;
    }

    // Path: bridged as String; convert to PathBuf.
    if matches!(p.ty, TypeRef::Path) {
        if p.optional {
            if p.is_ref {
                return format!("{name}.as_ref().map(std::path::Path::new)");
            }
            return format!("{name}.map(std::path::PathBuf::from)");
        }
        if p.is_ref {
            return format!("std::path::Path::new(&{name})");
        }
        return format!("std::path::PathBuf::from({name})");
    }

    // Named types in trait bridges are swift-bridge wrapper newtypes (e.g. `OcrConfig` wrapper
    // which holds `pub kreuzberg::OcrConfig`). The trait method expects the inner type (possibly
    // behind a reference). Extract `.0` and apply the appropriate reference.
    if matches!(p.ty, TypeRef::Named(_)) {
        if p.optional {
            if p.is_ref {
                return format!("{name}.as_ref().map(|w| &w.0)");
            }
            return format!("{name}.map(|w| w.0)");
        }
        if p.is_mut {
            return format!("&mut {name}.0");
        }
        if p.is_ref {
            return format!("&{name}.0");
        }
        return format!("{name}.0");
    }

    // Primitives and String.
    if p.is_ref {
        match &p.ty {
            TypeRef::Bytes | TypeRef::String | TypeRef::Char => return format!("&{name}"),
            TypeRef::Vec(_) if p.optional => return format!("{name}.as_deref()"),
            _ => return format!("&{name}"),
        }
    }
    name
}

/// Emit the body of a trait method trampoline, handling sync vs async and error types.
fn emit_trait_method_body(method: &MethodDef, source_call: &str, _return_ty: &str, enum_names: &HashSet<&str>) -> String {
    // Wrap the return value for methods that return Named types (bridged as JSON or swift-bridge
    // newtype wrappers). JSON-bridged types use serde_json::to_string. Named types not
    // JSON-bridged (i.e. plain Named leaf types) need to be wrapped in the bridge newtype.
    // Enum wrappers use `::from(val)`; struct newtypes use `T(val)`.
    let wrap_return = |expr: String| -> String {
        if needs_json_bridge(&method.return_type) {
            format!("serde_json::to_string(&({expr})).expect(\"serializable return\")")
        } else {
            match &method.return_type {
                TypeRef::String | TypeRef::Path => format!("{expr}.to_string()"),
                // Named leaf types are represented as bridge wrapper newtypes — wrap.
                TypeRef::Named(name) => {
                    if enum_names.contains(name.as_str()) {
                        format!("{name}::from({expr})")
                    } else {
                        format!("{name}({expr})")
                    }
                }
                _ => expr,
            }
        }
    };

    // Build the error+value mapping expression for a Result-returning method.
    // Handles JSON-bridged, String/Path, Named newtypes/enums, and plain cases.
    let map_result_expr = |base: String| -> String {
        if needs_json_bridge(&method.return_type) && !matches!(method.return_type, TypeRef::Unit) {
            format!("{base}.map(|v| serde_json::to_string(&v).expect(\"serializable return\")).map_err(|e| e.to_string())")
        } else if matches!(method.return_type, TypeRef::String | TypeRef::Path) {
            format!("{base}.map(|s| s.to_string()).map_err(|e| e.to_string())")
        } else if let TypeRef::Named(wrapper) = &method.return_type {
            // Result<kreuzberg::T, E> → Result<BridgeWrapper, String>
            let w = wrapper.clone();
            if enum_names.contains(w.as_str()) {
                format!("{base}.map(|v| {w}::from(v)).map_err(|e| e.to_string())")
            } else {
                format!("{base}.map(|v| {w}(v)).map_err(|e| e.to_string())")
            }
        } else {
            format!("{base}.map_err(|e| e.to_string())")
        }
    };

    if method.is_async {
        let await_expr = format!("{source_call}.await");
        let body = if method.error_type.is_some() {
            let mapped = map_result_expr(await_expr);
            format!("    ::tokio::runtime::Builder::new_current_thread()\n        .enable_all()\n        .build()\n        .expect(\"build tokio runtime\")\n        .block_on(async {{ {mapped} }})\n")
        } else {
            let inner = wrap_return(await_expr);
            format!("    ::tokio::runtime::Builder::new_current_thread()\n        .enable_all()\n        .build()\n        .expect(\"build tokio runtime\")\n        .block_on(async {{ {inner} }})\n")
        };
        body
    } else if method.error_type.is_some() {
        let mapped = map_result_expr(source_call.to_string());
        format!("    {mapped}\n")
    } else {
        let wrapped = wrap_return(source_call.to_string());
        format!("    {wrapped}\n")
    }
}

// ── wrapper type emitters ─────────────────────────────────────────────────────

fn emit_type_wrapper(
    ty: &TypeDef,
    source_crate: &str,
    type_paths: &HashMap<String, String>,
    enum_names: &HashSet<&str>,
    no_serde_names: &HashSet<&str>,
    exclude_fields: &HashSet<String>,
) -> String {
    let mut out = String::new();
    let source_path = resolve_type_path(&ty.name, source_crate, type_paths);
    out.push_str(&format!("pub struct {}(pub {});\n\n", ty.name, source_path));

    if !ty.fields.is_empty() {
        out.push_str(&format!("impl {} {{\n", ty.name));

        // Constructor — params use bridge types (String for JSON-bridged fields)
        // and Option<bridge_ty> when the field is optional.
        // Excluded fields (via exclude_fields config) are omitted from params
        // and left at Default::default() in the field initializers.
        let params: Vec<String> = ty
            .fields
            .iter()
            .filter(|f| {
                let field_key = format!("{}.{}", ty.name, f.name.to_snake_case());
                !exclude_fields.contains(&field_key)
            })
            .map(|f| {
                let bridge_ty = bridge_type(&f.ty);
                let bridge_ty = if f.optional && !needs_json_bridge(&f.ty) {
                    // Optional fields are JSON-bridged so this branch is rarely hit;
                    // when it is (a primitive Option), wrap in Option<>.
                    format!("Option<{bridge_ty}>")
                } else {
                    bridge_ty
                };
                let name = f.name.to_snake_case();
                format!("{name}: {bridge_ty}")
            })
            .collect();
        // Field initializers: JSON-deserialize, unwrap newtype wrappers, etc.
        // String-like fields are JSON-deserialized at runtime so the codegen
        // works for both real String fields and source fields that map to
        // alef String fallbacks (enums, serde_json::Value, etc.).
        let field_inits: Vec<String> = ty
            .fields
            .iter()
            .map(|f| {
                let name = f.name.to_snake_case();
                // Explicitly excluded fields: leave at Default::default().
                let field_key = format!("{}.{}", ty.name, name);
                if exclude_fields.contains(&field_key) {
                    return format!("            {name}: ::std::default::Default::default()");
                }
                // If the JSON-bridged field contains an excluded/no-serde Named type, skip it.
                let is_excluded_inner = needs_json_bridge(&f.ty) && {
                    match &f.ty {
                        TypeRef::Optional(inner) | TypeRef::Vec(inner) => matches!(inner.as_ref(),
                            TypeRef::Named(n) if !type_paths.contains_key(n.as_str()) || no_serde_names.contains(n.as_str())
                        ),
                        TypeRef::Named(n) => !type_paths.contains_key(n.as_str()) || no_serde_names.contains(n.as_str()),
                        _ => false,
                    }
                };
                if is_excluded_inner {
                    // Field type contains an excluded Named type that doesn't impl serde.
                    // Use Default::default() for the field rather than failing to compile.
                    format!("            {name}: ::std::default::Default::default()")
                } else if needs_json_bridge(&f.ty) {
                    let native_ty = swift_bridge_rust_type(&f.ty);
                    let opt_ty = if f.optional { format!("Option<{native_ty}>") } else { native_ty };
                    format!(
                        "            {name}: serde_json::from_str::<{opt_ty}>(&{name}).expect(\"valid JSON for {name}\")"
                    )
                } else if let TypeRef::Named(n) = &f.ty {
                    // Enum wrappers only have From<kreuzberg::T> for BridgeT (not the reverse).
                    // For struct newtypes use .0; for enum types leave at Default.
                    let is_enum = enum_names.contains(n.as_str());
                    if is_enum {
                        // Enum fields can't be reverse-converted — use Default
                        format!("            {name}: ::std::default::Default::default()")
                    } else if f.optional {
                        if matches!(f.core_wrapper, alef_core::ir::CoreWrapper::Arc) {
                            format!("            {name}: {name}.map(|w| std::sync::Arc::new(w.0))")
                        } else {
                            format!("            {name}: {name}.map(|w| w.0)")
                        }
                    } else if matches!(f.core_wrapper, alef_core::ir::CoreWrapper::Arc) {
                        format!("            {name}: std::sync::Arc::new({name}.0)")
                    } else {
                        format!("            {name}: {name}.0")
                    }
                } else if let TypeRef::Vec(inner) = &f.ty {
                    // Vec<Named> — unwrap bridge wrappers element-wise
                    if let TypeRef::Named(inner_n) = inner.as_ref() {
                        use alef_core::ir::CoreWrapper;
                        let is_enum = enum_names.contains(inner_n.as_str());
                        if is_enum {
                            // Vec<EnumT> fields: enum reverse-conversion not generated — use Default
                            format!("            {name}: ::std::default::Default::default()")
                        } else {
                            let unwrap_expr = match f.vec_inner_core_wrapper {
                                CoreWrapper::Arc => "std::sync::Arc::new(w.0)".to_string(),
                                _ => "w.0".to_string(),
                            };
                            if f.optional {
                                format!("            {name}: {name}.map(|v| v.into_iter().map(|w| {unwrap_expr}).collect())")
                            } else {
                                format!("            {name}: {name}.into_iter().map(|w| {unwrap_expr}).collect()")
                            }
                        }
                    } else {
                        format!("            {name}")
                    }
                } else if matches!(f.ty, TypeRef::String | TypeRef::Path | TypeRef::Char | TypeRef::Json) {
                    // String-like fields are serde-deserialized from the bridge String.
                    // Bytes (Vec<u8>) is excluded: it bridges as Vec<u8> directly, not as String.
                    // When the struct doesn't have serde derives, the source field
                    // might be a non-String type that was mapped to String by the IR
                    // (e.g. HeaderFooterType). Avoid serde-based deserialization for
                    // non-serde structs — leave the field at Default.
                    if !ty.has_serde {
                        format!("            {name}: ::std::default::Default::default()")
                    } else if f.optional {
                        format!(
                            "            {name}: {name}.and_then(|s| serde_json::from_str(&s).ok().or_else(|| serde_json::from_value(::serde_json::Value::String(s)).ok()))"
                        )
                    } else {
                        format!(
                            "            {name}: serde_json::from_str(&{name}).ok().or_else(|| serde_json::from_value::<_>(::serde_json::Value::String({name}.clone())).ok()).unwrap_or_else(|| panic!(\"failed to deserialize {name}\"))"
                        )
                    }
                } else if matches!(f.ty, TypeRef::Bytes) {
                    // bytes::Bytes != Vec<u8>; convert with .into().
                    format!("            {name}: {name}.into()")
                } else {
                    format!("            {name}")
                }
            })
            .collect();
        out.push_str(&format!(
            "    pub fn new({}) -> {} {{\n",
            params.join(", "),
            ty.name
        ));
        // Wrap source struct construction in a closure that takes a mutable
        // default and populates each field by JSON-decoding the bridge string
        // into a `serde_json::Value` first; this side-steps Rust's static type
        // check when alef's IR has lost the precise field type. For fields
        // alef *did* extract precisely (primitives, collections of primitives),
        // we still set them directly. The output requires the source struct
        // to implement `Default`.
        //
        // We also force the serde/Default path for structs that implement serde
        // (has_serde=true): the IR sometimes maps complex fields (e.g. Vec<Paragraph>)
        // to simpler types (Vec<String>). Without serde round-tripping, the direct
        // struct literal fails with type mismatches. Serde round-trips are safe for
        // any serde-capable struct.
        //
        // We also catch Vec<non-Primitive> fields in ANY struct: the IR may have mapped
        // Vec<Paragraph> to Vec<String>, Vec<(A,B)> to Vec<String>, etc. These cause
        // type mismatches in direct literals. Routing through Default+serde (or
        // unimplemented! when no Default) is the only safe option.
        let has_vec_non_primitive = ty.fields.iter().any(|f| {
            matches!(&f.ty, TypeRef::Vec(inner) if !matches!(inner.as_ref(), TypeRef::Primitive(_) | TypeRef::Bytes))
        });
        // Non-serde structs may have String/Path/Json fields whose actual kreuzberg type
        // is not Default (e.g. StyleType enum). We can't safely populate such fields
        // with Default::default() in a direct struct literal — route non-serde structs
        // with any String-like fields through the __target path as well.
        let has_non_serde_string_field = !ty.has_serde
            && ty.fields.iter().any(|f| {
                matches!(f.ty, TypeRef::String | TypeRef::Path | TypeRef::Json | TypeRef::Char)
            });
        let needs_default_construction = ty.has_serde
            || has_vec_non_primitive
            || has_non_serde_string_field
            || ty.fields.iter().any(|f| {
                // If the field has Optional<Named> where Named isn't in api.types
                // we don't know the exact type — fall back to Default + JSON.
                needs_json_bridge(&f.ty) || matches!(f.ty, TypeRef::Named(_))
            });
        if needs_default_construction && !ty.has_default {
            // The struct needs mutable-default construction but doesn't impl Default.
            // This happens when it contains enum fields (no Default on enums), opaque
            // service types (BoxCloneService), Arc/Box wrappers, or IR type mismatches
            // (Vec<Paragraph> mapped to Vec<String>). We cannot emit a correct constructor.
            out.push_str("        ::std::unimplemented!(\"constructor not available: struct requires Default which is not implemented\")\n");
        } else if needs_default_construction && ty.has_default {
            out.push_str(&format!(
                "        let mut __target: {} = ::std::default::Default::default();\n",
                source_path
            ));
            for f in &ty.fields {
                let name = f.name.to_snake_case();
                // Explicitly excluded fields: leave at Default::default() silently.
                let field_key = format!("{}.{}", ty.name, name);
                if exclude_fields.contains(&field_key) {
                    out.push_str(&format!(
                        "        // alef: excluded field `{name}` — actual type is not serializable, left at default\n"
                    ));
                    continue;
                }
                // Check if the inner Named type (if any) is excluded or lacks serde.
                let excluded_inner: Option<&str> = if needs_json_bridge(&f.ty) {
                    match &f.ty {
                        TypeRef::Optional(inner) | TypeRef::Vec(inner) => match inner.as_ref() {
                            TypeRef::Named(n)
                                if !type_paths.contains_key(n.as_str())
                                    || no_serde_names.contains(n.as_str()) =>
                            {
                                Some(n.as_str())
                            }
                            _ => None,
                        },
                        TypeRef::Named(n)
                            if !type_paths.contains_key(n.as_str()) || no_serde_names.contains(n.as_str()) =>
                        {
                            Some(n.as_str())
                        }
                        _ => None,
                    }
                } else {
                    None
                };
                if excluded_inner.is_some() {
                    // The inner type is excluded (e.g. InternalDocument — no serde derive).
                    // Leave the field at its Default value; the serde bridge can't work.
                    out.push_str(&format!(
                        "        // alef: skipped — field `{name}` contains excluded type, left at default\n"
                    ));
                } else if needs_json_bridge(&f.ty) {
                    // JSON-decode into a serde_json::Value, then assign as JSON-deserialized
                    // typed value via reinterpret.
                    out.push_str(&format!(
                        "        if let Ok(v) = ::serde_json::from_str::<::serde_json::Value>(&{name}) {{\n"
                    ));
                    out.push_str(&format!(
                        "            if let Ok(t) = ::serde_json::from_value(v) {{ __target.{name} = t; }}\n"
                    ));
                    out.push_str("        }\n");
                } else if let TypeRef::Named(n) = &f.ty {
                    // Enum wrappers only have From<kreuzberg::T> for BridgeT (not the reverse),
                    // so we cannot convert a bridge enum back to the source type via .into().
                    // For struct newtypes, use .0; for enums, leave at Default.
                    // The constructor param is still accepted (so the API is stable) but
                    // the value is dropped for enum fields. This is a known limitation.
                    let is_enum = enum_names.contains(n.as_str());
                    if is_enum {
                        // alef: enum fields in constructors are not converted back — leave at default
                        out.push_str(&format!(
                            "        // alef: {name} ({n}) is an enum; reverse From not generated — left at default\n"
                        ));
                    } else if f.optional {
                        // Optional Named field; wrap in Some(w.0), Box::new, or Arc::new if needed.
                        if f.is_boxed {
                            out.push_str(&format!(
                                "        if let Some(w) = {name} {{ __target.{name} = Some(Box::new(w.0)); }}\n"
                            ));
                        } else if matches!(f.core_wrapper, alef_core::ir::CoreWrapper::Arc) {
                            out.push_str(&format!(
                                "        if let Some(w) = {name} {{ __target.{name} = Some(std::sync::Arc::new(w.0)); }}\n"
                            ));
                        } else {
                            out.push_str(&format!(
                                "        if let Some(w) = {name} {{ __target.{name} = Some(w.0); }}\n"
                            ));
                        }
                    } else if f.is_boxed {
                        // The source field is Box<T>; wrap in Box::new().
                        out.push_str(&format!("        __target.{name} = Box::new({name}.0);\n"));
                    } else if matches!(f.core_wrapper, alef_core::ir::CoreWrapper::Arc) {
                        // The source field is Arc<T>; wrap in Arc::new().
                        out.push_str(&format!("        __target.{name} = std::sync::Arc::new({name}.0);\n"));
                    } else {
                        out.push_str(&format!("        __target.{name} = {name}.0;\n"));
                    }
                } else if let TypeRef::Vec(inner) = &f.ty {
                    // Vec<Named> fields: unwrap bridge wrappers element-wise.
                    // Enum elements: same limitation as above — leave at default.
                    if let TypeRef::Named(inner_n) = inner.as_ref() {
                        use alef_core::ir::CoreWrapper;
                        let is_enum = enum_names.contains(inner_n.as_str());
                        if is_enum {
                            out.push_str(&format!(
                                "        // alef: {name} (Vec<{inner_n}>) contains enum elements — left at default\n"
                            ));
                        } else {
                            // When the source field is Vec<Arc<T>>, wrap each element in Arc::new().
                            let unwrap_expr = match f.vec_inner_core_wrapper {
                                CoreWrapper::Arc => "std::sync::Arc::new(w.0)".to_string(),
                                _ => "w.0".to_string(),
                            };
                            if f.optional {
                                out.push_str(&format!(
                                    "        if let Some(v) = {name} {{ __target.{name} = Some(v.into_iter().map(|w| {unwrap_expr}).collect()); }}\n"
                                ));
                            } else {
                                out.push_str(&format!(
                                    "        __target.{name} = {name}.into_iter().map(|w| {unwrap_expr}).collect();\n"
                                ));
                            }
                        }
                    } else if ty.has_serde {
                        // Vec<non-Named> field in a serde struct. The IR may have mapped
                        // Vec<Paragraph> to Vec<String>, Vec<T> to Option<Vec<T>>, etc.
                        // Use serde JSON round-trip WITHOUT a type annotation so that the
                        // target field type is inferred from __target.{name}. This handles
                        // Vec→Option<Vec>, Vec<String>→Vec<OtherType>, etc. gracefully:
                        // the deserialized JSON is coerced to whatever type kreuzberg uses.
                        out.push_str(&format!(
                            "        if let Ok(__v) = ::serde_json::to_value({name}) {{\n"
                        ));
                        out.push_str(&format!(
                            "            if let Ok(t) = ::serde_json::from_value(__v) {{ __target.{name} = t; }}\n"
                        ));
                        out.push_str("        }\n");
                    } else if matches!(inner.as_ref(), TypeRef::Primitive(_) | TypeRef::Bytes) {
                        // Vec<Primitive> or Vec<Bytes> in non-serde struct: types should match.
                        out.push_str(&format!("        __target.{name} = {name};\n"));
                    } else {
                        // Vec<non-Primitive> in non-serde struct: actual type may differ from IR.
                        // Leave at Default to avoid type mismatches.
                        out.push_str(&format!(
                            "        // alef: {name} — Vec field type may differ from IR in non-serde struct, left at default\n"
                        ));
                    }
                } else if matches!(f.ty, TypeRef::String | TypeRef::Path | TypeRef::Char | TypeRef::Json) {
                    // String-like fields may map to enum/Named types in the source struct
                    // (alef's IR uses String as a fallback when the actual type can't be
                    // resolved). When the struct lacks serde derives, the field type is
                    // likely a non-serde type — leave at default to avoid compile errors.
                    // Bytes (Vec<u8>) is excluded: bridges as Vec<u8> directly, not String.
                    if !ty.has_serde {
                        out.push_str(&format!(
                            "        // alef: {name} — String fallback in non-serde struct, left at default\n"
                        ));
                    } else if f.optional {
                        out.push_str(&format!(
                            "        if let Some(s) = {name} {{\n"
                        ));
                        out.push_str(&format!(
                            "            if let Ok(v) = ::serde_json::from_str::<::serde_json::Value>(&s) {{\n"
                        ));
                        out.push_str(&format!(
                            "                if let Ok(t) = ::serde_json::from_value(v) {{ __target.{name} = Some(t); }}\n"
                        ));
                        out.push_str("            }\n        }\n");
                    } else {
                        out.push_str(&format!(
                            "        if let Ok(v) = ::serde_json::from_str::<::serde_json::Value>(&{name}) {{\n"
                        ));
                        out.push_str(&format!(
                            "            if let Ok(t) = ::serde_json::from_value(v) {{ __target.{name} = t; }}\n"
                        ));
                        out.push_str("        }\n");
                    }
                } else if matches!(f.ty, TypeRef::Bytes) {
                    // bytes::Bytes != Vec<u8>; convert with .into() so the assignment compiles.
                    out.push_str(&format!("        __target.{name} = {name}.into();\n"));
                } else {
                    out.push_str(&format!("        __target.{name} = {name};\n"));
                }
            }
            out.push_str(&format!("        {}(__target)\n", ty.name));
        } else {
            out.push_str(&format!(
                "        {}({} {{\n",
                ty.name, source_path
            ));
            for init in &field_inits {
                out.push_str(init);
                out.push_str(",\n");
            }
            out.push_str("        })\n");
        }
        out.push_str("    }\n");

        // Getters — return bridge types (String for JSON-bridged, wrappers for Named).
        for field in &ty.fields {
            let bridge_ty = bridge_type(&field.ty);
            let bridge_ty_owned = if field.optional && !needs_json_bridge(&field.ty) {
                format!("Option<{bridge_ty}>")
            } else {
                bridge_ty
            };
            let name = field.name.to_snake_case();
            // Explicitly excluded fields: emit an unimplemented getter that compiles
            // but panics at runtime if called. This handles fields whose actual
            // Rust type is not serializable but was mapped to String by the IR.
            let field_key = format!("{}.{}", ty.name, name);
            if exclude_fields.contains(&field_key) {
                out.push_str(&format!(
                    "    // alef: excluded field `{name}` — actual type is not serializable\n"
                ));
                out.push_str(&format!(
                    "    pub fn {name}(&self) -> {bridge_ty_owned} {{ ::std::unimplemented!(\"{name}: excluded field\") }}\n"
                ));
                continue;
            }
            // Check whether the inner Named type (if any) is in the type table.
            // When it is not (e.g. InternalDocument, EmbeddingPreset — excluded because
            // they lack serde derives), we cannot JSON-bridge the field. Emit an
            // unimplemented getter so the crate compiles but panics at runtime if called.
            // A Named inner type is "excluded" when it is either:
            //   (a) not in the type_paths map at all (not part of the API surface), or
            //   (b) present in the API surface but lacks serde derives (e.g. InternalDocument,
            //       EmbeddingPreset) — serde_json::to_string/from_str won't compile for those.
            let excluded_inner_named: Option<&str> = if needs_json_bridge(&field.ty) {
                match &field.ty {
                    TypeRef::Optional(inner) | TypeRef::Vec(inner) => match inner.as_ref() {
                        TypeRef::Named(n)
                            if !type_paths.contains_key(n.as_str())
                                || no_serde_names.contains(n.as_str()) =>
                        {
                            Some(n.as_str())
                        }
                        _ => None,
                    },
                    TypeRef::Named(n)
                        if !type_paths.contains_key(n.as_str()) || no_serde_names.contains(n.as_str()) =>
                    {
                        Some(n.as_str())
                    }
                    _ => None,
                }
            } else {
                None
            };
            if let Some(excluded) = excluded_inner_named {
                // alef: skipped — inner type is excluded from codegen (no serde derive)
                out.push_str(&format!(
                    "    // alef: skipped — field `{name}` contains `{excluded}` which is excluded from codegen\n"
                ));
                out.push_str(&format!(
                    "    pub fn {name}(&self) -> {bridge_ty_owned} {{ ::std::unimplemented!(\"{name}: {excluded} is not bridgeable\") }}\n"
                ));
            } else if needs_json_bridge(&field.ty) {
                out.push_str(&format!(
                    "    pub fn {name}(&self) -> {bridge_ty_owned} {{ serde_json::to_string(&self.0.{name}).expect(\"serializable {name}\") }}\n"
                ));
            } else if let TypeRef::Named(wrapper) = &field.ty {
                // Named field: wrap source value in our bridge wrapper.
                // Enum wrappers implement From<kreuzberg::T> so use ::from(val).
                // Struct newtypes use T(val) constructor directly.
                // When the source field is Box<T>, we must deref before wrapping.
                let is_enum = enum_names.contains(wrapper.as_str());
                if field.optional {
                    use alef_core::ir::CoreWrapper;
                    // Optional Named: self.0.field.clone().map(T) or T::from
                    // Handle Box<T> and Arc<T> wrappers when present.
                    let getter_expr = if field.is_boxed {
                        if is_enum {
                            format!("self.0.{name}.clone().map(|w| {wrapper}::from(*w))")
                        } else {
                            format!("self.0.{name}.clone().map(|w| {wrapper}(*w))")
                        }
                    } else if matches!(field.core_wrapper, CoreWrapper::Arc) {
                        if is_enum {
                            format!("self.0.{name}.clone().map(|w| {wrapper}::from((*w).clone()))")
                        } else {
                            format!("self.0.{name}.clone().map(|w| {wrapper}((*w).clone()))")
                        }
                    } else if is_enum {
                        format!("self.0.{name}.clone().map({wrapper}::from)")
                    } else {
                        format!("self.0.{name}.clone().map({wrapper})")
                    };
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> Option<{wrapper}> {{ {getter_expr} }}\n"
                    ));
                } else {
                    use alef_core::ir::CoreWrapper;
                    let expr = if field.is_boxed {
                        // Deref the Box<kreuzberg::T> before wrapping.
                        if is_enum {
                            format!("{wrapper}::from(*self.0.{name}.clone())")
                        } else {
                            format!("{wrapper}(*self.0.{name}.clone())")
                        }
                    } else if matches!(field.core_wrapper, CoreWrapper::Arc) {
                        // Deref the Arc<kreuzberg::T> before wrapping.
                        if is_enum {
                            format!("{wrapper}::from((*self.0.{name}).clone())")
                        } else {
                            format!("{wrapper}((*self.0.{name}).clone())")
                        }
                    } else if is_enum {
                        format!("{wrapper}::from(self.0.{name}.clone())")
                    } else {
                        format!("{wrapper}(self.0.{name}.clone())")
                    };
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> {wrapper} {{ {expr} }}\n"
                    ));
                }
            } else if let TypeRef::Vec(inner) = &field.ty {
                // Vec<Named> needs element-wise wrapping; others clone directly.
                if let TypeRef::Named(wrapper) = inner.as_ref() {
                    use alef_core::ir::CoreWrapper;
                    let is_enum = enum_names.contains(wrapper.as_str());
                    // When the source field is Vec<Arc<T>>, cloning an element
                    // yields Arc<kreuzberg::T>; we must deref before wrapping.
                    // The iterator is `.iter()` which yields `&T`, so we must call
                    // `.clone()` on each element before wrapping in the bridge newtype.
                    let elem_expr = match field.vec_inner_core_wrapper {
                        // elem is &Arc<T>; (*elem) is Arc<T>; (**elem) is T — deref twice.
                        CoreWrapper::Arc if !is_enum => format!("{wrapper}((**elem).clone())"),
                        CoreWrapper::Arc => format!("{wrapper}::from((**elem).clone())"),
                        _ if is_enum => format!("{wrapper}::from(elem.clone())"),
                        _ => format!("{wrapper}(elem.clone())"),
                    };
                    if field.optional {
                        // Optional<Vec<Named>> — map through Option then collect
                        out.push_str(&format!(
                            "    pub fn {name}(&self) -> Option<Vec<{wrapper}>> {{ self.0.{name}.as_ref().map(|v| v.iter().map(|elem| {elem_expr}).collect()) }}\n"
                        ));
                    } else {
                        out.push_str(&format!(
                            "    pub fn {name}(&self) -> Vec<{wrapper}> {{ self.0.{name}.iter().map(|elem| {elem_expr}).collect() }}\n"
                        ));
                    }
                } else if !matches!(inner.as_ref(), TypeRef::Primitive(_) | TypeRef::Bytes) {
                    // Vec<non-Primitive, non-Bytes> (e.g. Vec<String> in the IR that may
                    // actually be Vec<SomeStruct> in kreuzberg). When the struct has serde,
                    // use JSON round-trip so it compiles regardless of the actual field type.
                    // When the struct lacks serde, we cannot convert safely — emit unimplemented!().
                    if ty.has_serde {
                        if field.optional {
                            out.push_str(&format!(
                                "    pub fn {name}(&self) -> {bridge_ty_owned} {{ self.0.{name}.as_ref().and_then(|v| ::serde_json::to_value(v).ok().and_then(|j| ::serde_json::from_value(j).ok())) }}\n"
                            ));
                        } else {
                            out.push_str(&format!(
                                "    pub fn {name}(&self) -> {bridge_ty_owned} {{ ::serde_json::to_value(&self.0.{name}).ok().and_then(|j| ::serde_json::from_value(j).ok()).unwrap_or_default() }}\n"
                            ));
                        }
                    } else {
                        // Non-serde struct with Vec<non-primitive> field: actual type unknown.
                        out.push_str(&format!(
                            "    // alef: skipped — Vec field `{name}` may have different actual type in non-serde struct\n"
                        ));
                        out.push_str(&format!(
                            "    pub fn {name}(&self) -> {bridge_ty_owned} {{ ::std::unimplemented!(\"{name}: Vec field type mismatch in non-serde struct\") }}\n"
                        ));
                    }
                } else {
                    // Vec<Primitive> or Vec<Bytes>: the source field may actually be a tuple
                    // (e.g. (u32, u32)) that the IR mapped to Vec<u32>. Use serde round-trip
                    // in serde structs to coerce tuples → Vec automatically; fall back to
                    // clone() in non-serde structs where types should match exactly.
                    if ty.has_serde {
                        if field.optional {
                            out.push_str(&format!(
                                "    pub fn {name}(&self) -> {bridge_ty_owned} {{ self.0.{name}.as_ref().and_then(|v| ::serde_json::to_value(v).ok().and_then(|j| ::serde_json::from_value(j).ok())) }}\n"
                            ));
                        } else {
                            out.push_str(&format!(
                                "    pub fn {name}(&self) -> {bridge_ty_owned} {{ ::serde_json::to_value(&self.0.{name}).ok().and_then(|j| ::serde_json::from_value(j).ok()).unwrap_or_default() }}\n"
                            ));
                        }
                    } else {
                        out.push_str(&format!(
                            "    pub fn {name}(&self) -> {bridge_ty_owned} {{ self.0.{name}.clone() }}\n"
                        ));
                    }
                }
            } else if matches!(field.ty, TypeRef::String | TypeRef::Path | TypeRef::Char | TypeRef::Json) {
                // String-like fields might be JSON-bridged enums in the source struct;
                // serialize via serde_json so the result works for both `String` and
                // typed source fields.
                // Exception: when the struct itself lacks serde, the field might be a
                // non-serde type that was mapped to String by the IR. Use Debug format
                // as a safe fallback that always compiles.
                // NOTE: TypeRef::Bytes is NOT included here — it maps to Vec<u8> in the
                // bridge, not String, so it must fall through to the plain clone() branch.
                if !ty.has_serde {
                    if field.optional {
                        out.push_str(&format!(
                            "    pub fn {name}(&self) -> {bridge_ty_owned} {{ self.0.{name}.as_ref().map(|v| format!(\"{{v:?}}\")) }}\n"
                        ));
                    } else {
                        out.push_str(&format!(
                            "    pub fn {name}(&self) -> {bridge_ty_owned} {{ format!(\"{{:?}}\", &self.0.{name}) }}\n"
                        ));
                    }
                } else if field.optional {
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> {bridge_ty_owned} {{ self.0.{name}.as_ref().and_then(|v| serde_json::to_string(v).ok()) }}\n"
                    ));
                } else {
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> {bridge_ty_owned} {{ serde_json::to_string(&self.0.{name}).unwrap_or_default() }}\n"
                    ));
                }
            } else if matches!(field.ty, TypeRef::Bytes) {
                // bytes::Bytes bridges as Vec<u8>; convert with .to_vec() for the return.
                if field.optional {
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> {bridge_ty_owned} {{ self.0.{name}.as_ref().map(|b| b.to_vec()) }}\n"
                    ));
                } else {
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> {bridge_ty_owned} {{ self.0.{name}.to_vec() }}\n"
                    ));
                }
            } else if ty.has_serde && matches!(&field.ty, TypeRef::Vec(_) | TypeRef::Primitive(_)) {
                // Vec<T> or Primitive fields in serde structs: the IR may have mapped
                // Vec<Paragraph> to Vec<String> or a Primitive to NodeIndex. Use a
                // serde JSON round-trip WITHOUT type annotation so the return type is
                // inferred from the function signature. Falls back to Default on mismatch.
                if field.optional {
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> {bridge_ty_owned} {{ self.0.{name}.as_ref().and_then(|v| ::serde_json::to_value(v).ok().and_then(|j| ::serde_json::from_value(j).ok())) }}\n"
                    ));
                } else {
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> {bridge_ty_owned} {{ ::serde_json::to_value(&self.0.{name}).ok().and_then(|j| ::serde_json::from_value(j).ok()).unwrap_or_default() }}\n"
                    ));
                }
            } else {
                out.push_str(&format!(
                    "    pub fn {name}(&self) -> {bridge_ty_owned} {{ self.0.{name}.clone() }}\n"
                ));
            }
        }

        out.push_str("}\n");
    }

    out
}

fn emit_enum_wrapper(en: &EnumDef, source_crate: &str, type_paths: &HashMap<String, String>) -> String {
    let mut out = String::new();
    let source_path = resolve_type_path(&en.name, source_crate, type_paths);

    // Only emit unit variants. Variants with data fields (tuple or struct variants)
    // cannot be matched as unit patterns in the From impl below, so we expose only
    // the unit variants here. Data variants are bridged as JSON (String) by the
    // JSON-bridge fallback on containing types.
    let unit_variants: Vec<&alef_core::ir::EnumVariant> =
        en.variants.iter().filter(|v| v.fields.is_empty()).collect();

    // Bridge enum variant names: use the raw Rust identifier from the IR (which is
    // the actual identifier from the kreuzberg source, e.g. "EasyOCR", "RDFa").
    // Do NOT apply to_upper_camel_case() — heck transforms acronyms like "EasyOCR"
    // to "EasyOcr" and "RDFa" to "RdFa", creating names that don't match the source.
    // The bridge enum uses the same names as the kreuzberg source enum so the From impl
    // match arms are valid Rust identifiers on both sides.
    out.push_str(&format!("pub enum {} {{\n", en.name));
    for variant in &unit_variants {
        // Use the raw variant name from the IR — it is already a valid Rust identifier.
        out.push_str(&format!("    {},\n", variant.name));
    }
    // Add a catch-all variant to absorb any data variants from the source enum
    // that we don't model explicitly. This prevents exhaustiveness failures in the
    // From impl when the source enum has more variants than our bridge enum.
    let has_data_variants = en.variants.len() > unit_variants.len();
    if has_data_variants {
        out.push_str("    /// Data variants not directly bridgeable — represented as Unknown.\n");
        out.push_str("    Unknown,\n");
    }
    out.push_str("}\n\n");

    // From conversion: map unit variants; data variants fall through to Unknown.
    out.push_str(&format!("impl From<{source_path}> for {} {{\n", en.name));
    out.push_str(&format!("    fn from(val: {source_path}) -> Self {{\n"));
    out.push_str("        match val {\n");
    for variant in &unit_variants {
        // Use raw variant name on both sides — source variant name == bridge variant name.
        out.push_str(&format!(
            "            {source_path}::{} => Self::{},\n",
            variant.name, variant.name
        ));
    }
    if has_data_variants {
        out.push_str("            _ => Self::Unknown,\n");
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

// ── function shim emitters ────────────────────────────────────────────────────

/// Build the call-site expression for a function parameter, mirroring the
/// Dart backend's `dart_call_arg`: handle JSON-bridged types, Path conversion,
/// primitive casts, and reference borrows based on `is_ref`/`optional`.
///
/// Named types are wrapped as `pub struct T(pub kreuzberg::T)`, so accessing
/// the inner kreuzberg type requires `.0` indirection. Wrappers are passed by
/// value across the bridge but kreuzberg fns generally take a reference, so
/// we emit `&name.0` for `is_ref=true` Named params.
fn swift_call_arg(p: &alef_core::ir::ParamDef) -> String {
    let name = p.name.to_snake_case();
    let original = p.original_type.as_deref().unwrap_or("");
    let stripped_orig = original
        .trim()
        .trim_start_matches('&')
        .trim_start_matches("mut ")
        .trim();

    // Tuple parameters: same shape as the Dart codegen — IR flattens
    // `Vec<(A, B, ...)>` to `Vec<String>` and stores the original signature in
    // `original_type`. Reconstruct sensible defaults for known tuple shapes.
    if !stripped_orig.is_empty() && stripped_orig.starts_with("Vec(") && stripped_orig.contains("Named(\"(") {
        let tuple_inner = stripped_orig
            .find("Named(\"(")
            .and_then(|start| {
                let rest = &stripped_orig[start + 8..];
                rest.find(")\")").map(|end| rest[..end].trim_end_matches(')').to_string())
            })
            .unwrap_or_default();
        if tuple_inner.starts_with("PathBuf,") || tuple_inner.starts_with("PathBuf ,") {
            return format!(
                "{name}.into_iter().map(|p| (std::path::PathBuf::from(p), None)).collect::<Vec<_>>()"
            );
        }
        if tuple_inner.starts_with("Vec<u8>,") || tuple_inner.starts_with("Vec<u8> ,") {
            return format!("{{ let _ = {name}; ::std::unimplemented!(\"batch_extract_bytes from Swift not yet bridged\") }}");
        }
    }

    // JSON-bridged: deserialize from the bridged String.
    if needs_json_bridge(&p.ty) {
        let native_ty = swift_bridge_rust_type(&p.ty);
        let deser = format!("serde_json::from_str::<{native_ty}>(&{name}).expect(\"valid JSON for {name}\")");
        if p.is_ref {
            // When the kreuzberg function expects a reference (e.g. &[Vec<String>]),
            // we must borrow the deserialized value.
            return format!("&{deser}");
        }
        return deser;
    }

    // Path: bridged as String; convert to PathBuf or &Path.
    if matches!(p.ty, TypeRef::Path) {
        if p.optional {
            if p.is_ref {
                return format!("{name}.as_ref().map(std::path::Path::new)");
            }
            return format!("{name}.map(std::path::PathBuf::from)");
        }
        if p.is_ref {
            return format!("std::path::Path::new(&{name})");
        }
        return format!("std::path::PathBuf::from({name})");
    }

    // Named types: unwrap the swift-bridge wrapper newtype with `.0`.
    // Enum wrappers do not have a `.0` field — they are plain enums. When a
    // function parameter is a Named enum wrapper, we cannot reverse-convert
    // it to the underlying kreuzberg enum (no From<BridgeEnum> for kreuzberg::Enum).
    // The whole shim will be guarded at the emit_function_shim level; here we
    // still emit a `.0` access so the function body is structurally valid.
    if matches!(p.ty, TypeRef::Named(_)) {
        if p.optional {
            if p.is_ref {
                return format!("{name}.as_ref().map(|w| &w.0)");
            }
            return format!("{name}.map(|w| w.0)");
        }
        if p.is_ref {
            return format!("&{name}.0");
        }
        return format!("{name}.0");
    }

    // Vec<Named>: elements are bridge wrapper newtypes; unwrap each with `.0`.
    // Vec<Named> is NOT json-bridged (Named is a bridge leaf), so it falls here.
    if let TypeRef::Vec(inner) = &p.ty {
        if let TypeRef::Named(_) = inner.as_ref() {
            if p.optional {
                if p.is_ref {
                    // kreuzberg expects Option<&[T]>. We collect to a temporary Vec
                    // and call as_deref(). The temporary lives for the enclosing
                    // statement (function call) so the reference is valid.
                    return format!(
                        "{name}.as_ref().map(|v| v.iter().map(|w| w.0.clone()).collect::<Vec<_>>()).as_deref()"
                    );
                }
                return format!(
                    "{name}.map(|v| v.into_iter().map(|w| w.0).collect::<Vec<_>>())"
                );
            }
            if p.is_ref {
                // kreuzberg expects &[T]. Collect to a temporary Vec and slice it.
                return format!(
                    "{{ let __tmp = {name}.iter().map(|w| w.0.clone()).collect::<Vec<_>>(); __tmp.as_slice() }}"
                );
            }
            return format!("{name}.into_iter().map(|w| w.0).collect::<Vec<_>>()");
        }
    }

    // Primitive: swift-bridge maps integer widths well, but reference params
    // still need `&`.
    if let TypeRef::Primitive(_) = &p.ty {
        if p.is_ref {
            return format!("&{name}");
        }
        return name;
    }

    if !p.is_ref {
        return name;
    }
    match (&p.ty, p.optional) {
        (TypeRef::Bytes, false) => format!("&{name}"),
        (TypeRef::String | TypeRef::Char, false) => format!("&{name}"),
        (TypeRef::String | TypeRef::Char, true) => format!("{name}.as_deref()"),
        (TypeRef::Vec(_), true) => format!("{name}.as_deref()"),
        _ => format!("&{name}"),
    }
}

fn emit_function_shim(
    f: &FunctionDef,
    source_crate: &str,
    type_paths: &HashMap<String, String>,
    enum_names: &HashSet<&str>,
    no_serde_names: &HashSet<&str>,
) -> String {
    // Match the extern block's escaping so the wrapper fn matches the extern decl.
    let fn_name = swift_ident(&f.name.to_snake_case());
    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| {
            let bridge_ty = bridge_type(&p.ty);
            let bridge_ty = if p.optional {
                format!("Option<{bridge_ty}>")
            } else {
                bridge_ty
            };
            let name = swift_ident(&p.name.to_snake_case());
            format!("{name}: {bridge_ty}")
        })
        .collect();
    let params_str = params.join(", ");

    let return_ty = if f.error_type.is_some() {
        let ok_ty = bridge_type(&f.return_type);
        if matches!(f.return_type, TypeRef::Unit) {
            "Result<(), String>".to_string()
        } else {
            format!("Result<{ok_ty}, String>")
        }
    } else {
        bridge_type(&f.return_type)
    };

    // Build call args, deserializing JSON-bridged params before passing to the real fn
    let call_args: Vec<String> = f
        .params
        .iter()
        .map(|p| swift_call_arg(p))
        .collect();
    let call_args_str = call_args.join(", ");

    // Resolve the source call via the IR's full rust_path so module-prefixed
    // functions (e.g. `my_lib::utils::helper`) generate correct shim calls.
    // Falls back to the bare fn name if rust_path is empty.
    let resolved_path = if f.rust_path.is_empty() {
        format!("{source_crate}::{fn_name}")
    } else {
        f.rust_path.replace('-', "_")
    };
    let source_call = format!("{resolved_path}({call_args_str})");

    // If any parameter is a Named enum wrapper, we cannot pass it into kreuzberg
    // because the bridge enum only generates From<kreuzberg::T> for BridgeT (not the
    // reverse). Emit an unimplemented!() body — the function will panic at runtime.
    if f.params.iter().any(|p| matches!(&p.ty, TypeRef::Named(n) if enum_names.contains(n.as_str()))) {
        let problematic = f
            .params
            .iter()
            .filter(|p| matches!(&p.ty, TypeRef::Named(n) if enum_names.contains(n.as_str())))
            .map(|p| p.name.as_str())
            .collect::<Vec<_>>()
            .join(", ");
        return format!(
            "// alef: skipped — parameter(s) `{problematic}` are enum bridge wrappers; reverse From not generated\n\
             pub fn {fn_name}({params_str}) -> {return_ty} {{\n    \
             ::std::unimplemented!(\"{fn_name}: enum parameter(s) [{problematic}] cannot be converted back to kreuzberg types\")\n\
             }}\n"
        );
    }

    // Bug B: If the return type is a JSON-bridged Optional/Vec/Named whose inner
    // Named type is NOT in the visible type table (i.e., excluded from codegen —
    // such as EmbeddingPreset or InternalDocument which don't impl serde), we
    // cannot generate a working serde-based bridge. Emit an unimplemented!() body
    // so the crate at least compiles rather than failing with "trait not satisfied".
    // The function will panic at runtime, but that is preferable to compile errors.
    fn inner_named_type(ty: &TypeRef) -> Option<&str> {
        match ty {
            TypeRef::Named(n) => Some(n.as_str()),
            TypeRef::Optional(inner) | TypeRef::Vec(inner) => inner_named_type(inner),
            _ => None,
        }
    }
    if needs_json_bridge(&f.return_type) {
        if let Some(inner_name) = inner_named_type(&f.return_type) {
            if !type_paths.contains_key(inner_name) || no_serde_names.contains(inner_name) {
                // The inner Named type is not in the visible type table or lacks serde.
                // We cannot serde-bridge it — emit an unimplemented shim.
                let fn_name_snake = swift_ident(&f.name.to_snake_case());
                return format!(
                    "// alef: skipped — return type `{inner_name}` is excluded from codegen (no serde derive)\n\
                     pub fn {fn_name_snake}({params_str}) -> {return_ty} {{\n    \
                     ::std::unimplemented!(\"{fn_name_snake}: return type {inner_name} is not bridgeable\")\n\
                     }}\n"
                );
            }
        }
    }

    // Wrap return value with JSON serialization when the return type is not natively
    // supported by swift-bridge 0.1.59 (nested generics, HashMap). Named return
    // types must be wrapped in their swift-bridge newtype (`pub struct T(pub kreuzberg::T)`).
    // Async fns must `.await` before mapping; sync fns can chain directly.
    let json_wrap_ok = needs_json_bridge(&f.return_type);

    // Build a wrapper expression for a Named type `t`.
    // Enum wrappers implement From<kreuzberg::T> — use T::from(val) or val.map(T::from).
    // Struct newtypes use T(val) constructor directly.
    let wrap_named = |t: &str| -> String {
        if enum_names.contains(t) {
            format!("{t}::from")
        } else {
            t.to_string()
        }
    };
    let wrap_named_direct = |t: &str, source: &str| -> String {
        if enum_names.contains(t) {
            format!("{t}::from({source})")
        } else {
            format!("{t}({source})")
        }
    };

    // Determine the wrapper to apply for Named return types — the swift-bridge
    // wrappers are nominal newtypes, so we need to construct them from the source
    // value. Three cases:
    //   - Named(T) → wrap with `T(value)` or `T::from(value)`
    //   - Optional(Named(T)) → `.map(T)` or `.map(T::from)`
    //   - Vec(Named(T)) → `.into_iter().map(T).collect::<Vec<_>>()`
    enum WrapShape {
        Direct(String),    // T(value) or T::from(value)
        OptMap(String),    // value.map(T) or value.map(T::from)
        VecMap(String),    // value.into_iter().map(T).collect()
    }
    let wrap_shape = match &f.return_type {
        TypeRef::Named(n) => Some(WrapShape::Direct(n.clone())),
        TypeRef::Optional(inner) => match inner.as_ref() {
            TypeRef::Named(n) => Some(WrapShape::OptMap(n.clone())),
            _ => None,
        },
        TypeRef::Vec(inner) => match inner.as_ref() {
            TypeRef::Named(n) => Some(WrapShape::VecMap(n.clone())),
            _ => None,
        },
        _ => None,
    };
    let value_map_string: String = if json_wrap_ok {
        ".map(|v| serde_json::to_string(&v).expect(\"serializable return\"))".to_string()
    } else {
        match &wrap_shape {
            Some(WrapShape::Direct(t)) => format!(".map({})", wrap_named(t)),
            Some(WrapShape::OptMap(t)) => format!(".map(|v| v.map({}))", wrap_named(t)),
            Some(WrapShape::VecMap(t)) => format!(".map(|v| v.into_iter().map({}).collect::<Vec<_>>())", wrap_named(t)),
            None => {
                // Apply coercions for &str → String and Vec<&str> → Vec<String>
                // in Result-returning functions, same as for direct returns.
                match &f.return_type {
                    TypeRef::String | TypeRef::Path => ".map(|s| s.to_string())".to_string(),
                    TypeRef::Vec(inner) if matches!(inner.as_ref(), TypeRef::String | TypeRef::Path) => {
                        ".map(|v| v.into_iter().map(|s| s.to_string()).collect::<Vec<_>>())".to_string()
                    }
                    _ => String::new(),
                }
            }
        }
    };
    let value_map = value_map_string.as_str();
    // Direct (non-Result) wrap for the value.
    let direct_wrap = |source: String| -> String {
        if json_wrap_ok {
            return format!("serde_json::to_string(&({source})).expect(\"serializable return\")");
        }
        match &wrap_shape {
            Some(WrapShape::Direct(t)) => wrap_named_direct(t, &source),
            Some(WrapShape::OptMap(t)) => format!("({source}).map({})", wrap_named(t)),
            Some(WrapShape::VecMap(t)) => format!("({source}).into_iter().map({}).collect::<Vec<_>>()", wrap_named(t)),
            None => {
                // No wrapping needed — but the kreuzberg function might return `&str`
                // when the IR says `String`, or `Vec<&str>` when the IR says `Vec<String>`.
                // Apply coercions to match the declared return type.
                match &f.return_type {
                    TypeRef::String | TypeRef::Path => format!("{source}.to_string()"),
                    TypeRef::Vec(inner) if matches!(inner.as_ref(), TypeRef::String | TypeRef::Path) => {
                        format!("{source}.into_iter().map(|s| s.to_string()).collect::<Vec<_>>()")
                    }
                    _ => source,
                }
            }
        }
    };
    let body = if f.is_async {
        let mut chain = format!("{source_call}.await");
        if f.error_type.is_some() {
            chain = format!("{chain}.map_err(|e| e.to_string()){value_map}");
        } else {
            chain = direct_wrap(chain);
        }
        chain
    } else if f.error_type.is_some() {
        format!("{source_call}.map_err(|e| e.to_string()){value_map}")
    } else {
        direct_wrap(source_call)
    };

    // The wrapper is always sync — swift-bridge 0.1.59 doesn't support async
    // functions in extern blocks, so async source calls are blocked-on inside
    // a tokio runtime. The runtime is created lazily on first call.
    if f.is_async {
        format!(
            "pub fn {fn_name}({params_str}) -> {return_ty} {{\n    \
            ::tokio::runtime::Builder::new_current_thread()\n        \
                .enable_all()\n        \
                .build()\n        \
                .expect(\"build tokio runtime\")\n        \
                .block_on(async {{ {body} }})\n}}\n"
        )
    } else {
        format!("pub fn {fn_name}({params_str}) -> {return_ty} {{\n    {body}\n}}\n")
    }
}

// ── type mapping for swift-bridge Rust side ───────────────────────────────────

/// Returns true for types that swift-bridge 0.1.59 cannot handle inside `extern "Rust"` blocks.
///
/// Two distinct bugs in swift-bridge-ir-0.1.59 are covered:
///
/// 1. **Parser bug** (`bridged_type.rs:826`): `BridgedType::new_with_str` uses
///    `trim_end_matches(" >")` which strips ALL trailing ` >` occurrences. This corrupts
///    `Vec < Option < String > >` into `Vec < Option < String` causing `syn::parse2` to
///    fail with `Error("expected ','")`.
///
/// 2. **Codegen todo** (`bridged_type.rs:1986`): `BuiltInResult::is_custom_result_type()`
///    returns `true` when the ok type is a `StdLib` non-Vec type (e.g. `Option<T>`,
///    primitives). When true, the codegen calls `to_alpha_numeric_underscore_name` on the
///    ok type, but `StdLib::Option` and `StdLib::Vec` hit `_ => todo!()` there.
///
/// HashMap is completely unsupported by swift-bridge.
///
/// All affected types are serialized to JSON (`String`) at the bridge boundary.
fn needs_json_bridge(ty: &TypeRef) -> bool {
    match ty {
        // HashMap is unsupported by swift-bridge regardless of nesting.
        TypeRef::Map(_, _) => true,
        // Vec<T> is only safe when T is a "leaf" type (no angle brackets in its token form).
        // Primitives, String, char, Named opaques, and Vec<u8> (Bytes) are all safe.
        // Anything else (Vec<Option<..>>, Vec<Vec<..>>, Vec<Map<..>>) triggers the parser bug.
        TypeRef::Vec(inner) => !is_bridge_leaf(inner),
        // Option<T> as a Result ok-type causes is_custom_result_type()=true + todo!() in
        // to_alpha_numeric_underscore_name. JSON-bridge all Optional types to avoid this.
        TypeRef::Optional(_) => true,
        _ => false,
    }
}

/// Returns true when `ty` produces a token-stream representation with no angle brackets,
/// i.e. it is safe as the inner type of a `Vec<T>` in a swift-bridge extern block.
fn is_bridge_leaf(ty: &TypeRef) -> bool {
    match ty {
        TypeRef::Primitive(_)
        | TypeRef::String
        | TypeRef::Char
        | TypeRef::Path
        | TypeRef::Json
        | TypeRef::Unit
        | TypeRef::Duration => true,
        // Bytes = Vec<u8> — swift-bridge supports this directly.
        TypeRef::Bytes => true,
        // Named opaque types (wrapper newtypes) have no angle brackets.
        TypeRef::Named(_) => true,
        // Everything else (Vec, Optional, Map) produces angle brackets in the token stream.
        _ => false,
    }
}

/// Maps an IR `TypeRef` to the Rust type used in swift-bridge `extern "Rust"` block declarations.
///
/// Types that swift-bridge 0.1.59 cannot parse (nested generics, HashMap) are collapsed to
/// `String` (JSON-serialized at the shim boundary). All other types use their native Rust form.
fn bridge_type(ty: &TypeRef) -> String {
    if needs_json_bridge(ty) {
        return "String".to_string();
    }
    match ty {
        TypeRef::Optional(inner) => format!("Option<{}>", bridge_type(inner)),
        TypeRef::Vec(inner) => format!("Vec<{}>", bridge_type(inner)),
        _ => swift_bridge_rust_type(ty),
    }
}

/// Maps an IR `TypeRef` to the native Rust type string (used in wrapper impls and shim bodies).
///
/// This is the full native type including nested generics and HashMap — used on the Rust side
/// of the shim where swift-bridge is not involved.
fn swift_bridge_rust_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Primitive(p) => rust_primitive_str(p).to_string(),
        TypeRef::String => "String".to_string(),
        TypeRef::Char => "char".to_string(),
        TypeRef::Bytes => "Vec<u8>".to_string(),
        TypeRef::Path => "String".to_string(),
        TypeRef::Json => "String".to_string(),
        TypeRef::Unit => "()".to_string(),
        TypeRef::Duration => "u64".to_string(),
        TypeRef::Optional(inner) => format!("Option<{}>", swift_bridge_rust_type(inner)),
        TypeRef::Vec(inner) => format!("Vec<{}>", swift_bridge_rust_type(inner)),
        TypeRef::Map(k, v) => {
            format!(
                "std::collections::HashMap<{}, {}>",
                swift_bridge_rust_type(k),
                swift_bridge_rust_type(v)
            )
        }
        TypeRef::Named(name) => name.clone(),
    }
}

fn rust_primitive_str(p: &PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::Bool => "bool",
        PrimitiveType::U8 => "u8",
        PrimitiveType::I8 => "i8",
        PrimitiveType::U16 => "u16",
        PrimitiveType::I16 => "i16",
        PrimitiveType::U32 => "u32",
        PrimitiveType::I32 => "i32",
        PrimitiveType::U64 => "u64",
        PrimitiveType::I64 => "i64",
        PrimitiveType::Usize => "usize",
        PrimitiveType::Isize => "isize",
        PrimitiveType::F32 => "f32",
        PrimitiveType::F64 => "f64",
    }
}
