//! Emits the Rust-side swift-bridge crate for Phase 2C.
//!
//! Three files are generated into `packages/swift/rust/`:
//! - `Cargo.toml` — declares the `cdylib`/`staticlib` crate with swift-bridge dependencies
//! - `src/lib.rs` — `#[swift_bridge::bridge] mod ffi { … }` plus wrapper newtypes and shims
//! - `build.rs` — calls `swift_bridge_build::parse_bridges` to run codegen at build time

use alef_core::backend::GeneratedFile;
use alef_core::config::AlefConfig;
use alef_core::ir::{ApiSurface, EnumDef, FunctionDef, PrimitiveType, TypeDef, TypeRef};
use alef_core::template_versions;
use heck::{ToSnakeCase, ToUpperCamelCase};
use std::path::PathBuf;

/// Top-level entry point: emit all three files for the swift-bridge crate.
pub fn emit(api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
    let base = PathBuf::from("packages/swift/rust");
    let crate_name = &api.crate_name;
    let version = &api.version;

    let swift_bridge_ver = template_versions::cargo::SWIFT_BRIDGE;
    let swift_bridge_build_ver = template_versions::cargo::SWIFT_BRIDGE_BUILD;
    let core_crate_dir = config.core_crate_dir();
    let same_as_workspace = core_crate_dir == *crate_name && config.crate_config.workspace_root.is_none();
    let core_path = if same_as_workspace {
        "../../..".to_string()
    } else {
        format!("../../../crates/{core_crate_dir}")
    };

    let features = config.features_for_language(alef_core::config::extras::Language::Swift);
    let exclude_functions: std::collections::HashSet<String> = config
        .swift
        .as_ref()
        .map(|c| c.exclude_functions.iter().cloned().collect())
        .unwrap_or_default();
    let exclude_types: std::collections::HashSet<String> = config
        .swift
        .as_ref()
        .map(|c| c.exclude_types.iter().cloned().collect())
        .unwrap_or_default();
    let cargo_toml = emit_cargo_toml(crate_name, version, swift_bridge_ver, swift_bridge_build_ver, &core_path, features);
    let lib_rs = emit_lib_rs(api, crate_name, &exclude_functions, &exclude_types);
    let build_rs = emit_build_rs();

    Ok(vec![
        GeneratedFile {
            path: base.join("Cargo.toml"),
            content: cargo_toml,
            generated_header: false,
        },
        GeneratedFile {
            path: base.join("src/lib.rs"),
            content: lib_rs,
            generated_header: false,
        },
        GeneratedFile {
            path: base.join("build.rs"),
            content: build_rs,
            generated_header: false,
        },
    ])
}

// ── Cargo.toml ────────────────────────────────────────────────────────────────

fn emit_cargo_toml(
    crate_name: &str,
    version: &str,
    swift_bridge_ver: &str,
    swift_bridge_build_ver: &str,
    core_path: &str,
    features: &[String],
) -> String {
    let source_crate_name = crate_name.replace('-', "_");
    let features_block = if features.is_empty() {
        String::new()
    } else {
        let list = features
            .iter()
            .map(|f| format!("\"{f}\""))
            .collect::<Vec<_>>()
            .join(", ");
        format!(", features = [{list}]")
    };
    format!(
        r#"# Generated by alef. Do not edit by hand.
[package]
name = "{crate_name}-swift"
version = "{version}"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
{source_crate_name} = {{ path = "{core_path}"{features_block} }}
serde_json = "1"
tokio = {{ version = "1", features = ["rt", "macros"] }}
swift-bridge = "{swift_bridge_ver}"

[build-dependencies]
swift-bridge-build = "{swift_bridge_build_ver}"
"#
    )
}

// ── build.rs ──────────────────────────────────────────────────────────────────

fn emit_build_rs() -> String {
    r#"// Generated by alef. Do not edit by hand.
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR unset"));
    let crate_name = std::env::var("CARGO_PKG_NAME").expect("CARGO_PKG_NAME unset");
    let bridges = vec!["src/lib.rs"];
    swift_bridge_build::parse_bridges(bridges).write_all_concatenated(out_dir, &crate_name);
    println!("cargo:rerun-if-changed=src/lib.rs");
}
"#
    .to_string()
}

// ── lib.rs ────────────────────────────────────────────────────────────────────

fn emit_lib_rs(
    api: &ApiSurface,
    crate_name: &str,
    exclude_functions: &std::collections::HashSet<String>,
    exclude_types: &std::collections::HashSet<String>,
) -> String {
    let source_crate = crate_name.replace('-', "_");

    let mut out = String::new();
    out.push_str("// Generated by alef. Do not edit by hand.\n\n");

    let visible_types: Vec<&TypeDef> = api
        .types
        .iter()
        .filter(|t| !exclude_types.contains(&t.name) && !t.is_trait)
        .collect();
    let visible_enums: Vec<&EnumDef> = api
        .enums
        .iter()
        .filter(|e| !exclude_types.contains(&e.name))
        .collect();
    let visible_functions: Vec<&FunctionDef> = api
        .functions
        .iter()
        .filter(|f| !exclude_functions.contains(&f.name))
        .collect();

    // Collect extern "Rust" blocks for the ffi module
    let mut extern_blocks: Vec<String> = Vec::new();
    for ty in &visible_types {
        extern_blocks.push(emit_extern_block_for_type(ty));
    }
    for en in &visible_enums {
        extern_blocks.push(emit_extern_block_for_enum(en));
    }
    if !visible_functions.is_empty() {
        // Build a Vec<FunctionDef> so the existing emitter API is reused.
        let visible: Vec<FunctionDef> = visible_functions.iter().map(|f| (*f).clone()).collect();
        extern_blocks.push(emit_extern_block_for_functions(&visible));
    }

    out.push_str("#[swift_bridge::bridge]\nmod ffi {\n");
    for block in &extern_blocks {
        out.push_str(block);
    }
    out.push_str("}\n\n");

    for ty in &visible_types {
        out.push_str(&emit_type_wrapper(ty, &source_crate));
        out.push('\n');
    }
    for en in &visible_enums {
        out.push_str(&emit_enum_wrapper(en, &source_crate));
        out.push('\n');
    }
    for f in &visible_functions {
        out.push_str(&emit_function_shim(f, &source_crate));
        out.push('\n');
    }

    out
}

// ── extern block emitters ─────────────────────────────────────────────────────

fn emit_extern_block_for_type(ty: &TypeDef) -> String {
    let mut block = String::new();
    block.push_str("    extern \"Rust\" {\n");
    block.push_str(&format!("        type {};\n", ty.name));

    // Constructor — use bridge_type to avoid nested generics that swift-bridge 0.1.59
    // cannot parse (Vec<Vec<T>>, HashMap<K,V>); those become String (JSON).
    if !ty.fields.is_empty() {
        let params: Vec<String> = ty
            .fields
            .iter()
            .map(|f| {
                let bridge_ty = bridge_type(&f.ty);
                let bridge_ty = if f.optional && !needs_json_bridge(&f.ty) {
                    format!("Option<{bridge_ty}>")
                } else {
                    bridge_ty
                };
                let name = f.name.to_snake_case();
                format!("{name}: {bridge_ty}")
            })
            .collect();
        block.push_str("        #[swift_bridge(init)]\n");
        block.push_str(&format!(
            "        fn new({}) -> {};\n",
            params.join(", "),
            ty.name
        ));
    }

    // Getters
    for field in &ty.fields {
        let bridge_ty = bridge_type(&field.ty);
        let bridge_ty = if field.optional && !needs_json_bridge(&field.ty) {
            format!("Option<{bridge_ty}>")
        } else {
            bridge_ty
        };
        let name = field.name.to_snake_case();
        block.push_str(&format!("        fn {name}(&self) -> {bridge_ty};\n"));
    }

    block.push_str("    }\n\n");
    block
}

fn emit_extern_block_for_enum(en: &EnumDef) -> String {
    let mut block = String::new();
    block.push_str("    extern \"Rust\" {\n");
    block.push_str(&format!("        type {};\n", en.name));
    block.push_str("    }\n\n");
    block
}

fn emit_extern_block_for_functions(functions: &[FunctionDef]) -> String {
    let mut block = String::new();
    block.push_str("    extern \"Rust\" {\n");

    for f in functions {
        let fn_name = f.name.to_snake_case();
        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| {
                let bridge_ty = bridge_type(&p.ty);
                let bridge_ty = if p.optional {
                    format!("Option<{bridge_ty}>")
                } else {
                    bridge_ty
                };
                let name = p.name.to_snake_case();
                format!("{name}: {bridge_ty}")
            })
            .collect();
        let params_str = params.join(", ");

        let return_ty = if f.error_type.is_some() {
            // Result<ReturnType, String> for error-throwing functions
            let ok_ty = bridge_type(&f.return_type);
            if matches!(f.return_type, TypeRef::Unit) {
                "Result<(), String>".to_string()
            } else {
                format!("Result<{ok_ty}, String>")
            }
        } else {
            bridge_type(&f.return_type)
        };

        // swift-bridge 0.1.59 does not support the `#[swift_bridge(async)]`
        // attribute (the build script's parser rejects it). To bridge async
        // functions, we declare them as plain `fn` in the extern block — the
        // wrapper will block on the future at the bridge boundary.
        block.push_str(&format!(
            "        fn {fn_name}({params_str}) -> {return_ty};\n"
        ));
    }

    block.push_str("    }\n\n");
    block
}

// ── wrapper type emitters ─────────────────────────────────────────────────────

fn emit_type_wrapper(ty: &TypeDef, source_crate: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "pub struct {}(pub {}::{});\n\n",
        ty.name, source_crate, ty.name
    ));

    if !ty.fields.is_empty() {
        out.push_str(&format!("impl {} {{\n", ty.name));

        // Constructor — params use bridge types (String for JSON-bridged fields)
        // and Option<bridge_ty> when the field is optional.
        let params: Vec<String> = ty
            .fields
            .iter()
            .map(|f| {
                let bridge_ty = bridge_type(&f.ty);
                let bridge_ty = if f.optional && !needs_json_bridge(&f.ty) {
                    // Optional fields are JSON-bridged so this branch is rarely hit;
                    // when it is (a primitive Option), wrap in Option<>.
                    format!("Option<{bridge_ty}>")
                } else {
                    bridge_ty
                };
                let name = f.name.to_snake_case();
                format!("{name}: {bridge_ty}")
            })
            .collect();
        // Field initializers: JSON-deserialize, unwrap newtype wrappers, etc.
        let field_inits: Vec<String> = ty
            .fields
            .iter()
            .map(|f| {
                let name = f.name.to_snake_case();
                if needs_json_bridge(&f.ty) {
                    let native_ty = swift_bridge_rust_type(&f.ty);
                    let opt_ty = if f.optional { format!("Option<{native_ty}>") } else { native_ty };
                    format!(
                        "            {name}: serde_json::from_str::<{opt_ty}>(&{name}).expect(\"valid JSON for {name}\")"
                    )
                } else if matches!(f.ty, TypeRef::Named(_)) {
                    // Named field: wrapper newtype → unwrap with `.0` to get
                    // the source-crate type the inner struct expects.
                    if f.optional {
                        format!("            {name}: {name}.map(|w| w.0)")
                    } else {
                        format!("            {name}: {name}.0")
                    }
                } else {
                    format!("            {name}")
                }
            })
            .collect();
        out.push_str(&format!(
            "    pub fn new({}) -> {} {{\n",
            params.join(", "),
            ty.name
        ));
        // Wrap source struct construction in a closure that takes a mutable
        // default and populates each field by JSON-decoding the bridge string
        // into a `serde_json::Value` first; this side-steps Rust's static type
        // check when alef's IR has lost the precise field type. For fields
        // alef *did* extract precisely (primitives, collections of primitives),
        // we still set them directly. The output requires the source struct
        // to implement `Default`.
        let needs_default_construction = ty.fields.iter().any(|f| {
            // If the field has Optional<Named> where Named isn't in api.types
            // we don't know the exact type — fall back to Default + JSON.
            needs_json_bridge(&f.ty) || matches!(f.ty, TypeRef::Named(_))
        });
        if needs_default_construction && ty.has_default {
            out.push_str(&format!(
                "        let mut __target: {}::{} = ::std::default::Default::default();\n",
                source_crate, ty.name
            ));
            for f in &ty.fields {
                let name = f.name.to_snake_case();
                if needs_json_bridge(&f.ty) {
                    // JSON-decode into a serde_json::Value, then assign as JSON-deserialized
                    // typed value via reinterpret.
                    out.push_str(&format!(
                        "        if let Ok(v) = ::serde_json::from_str::<::serde_json::Value>(&{name}) {{\n"
                    ));
                    out.push_str(&format!(
                        "            if let Ok(t) = ::serde_json::from_value(v) {{ __target.{name} = t; }}\n"
                    ));
                    out.push_str("        }\n");
                } else if matches!(f.ty, TypeRef::Named(_)) {
                    if f.optional {
                        out.push_str(&format!(
                            "        if let Some(w) = {name} {{ __target.{name} = Some(w.0); }}\n"
                        ));
                    } else {
                        out.push_str(&format!("        __target.{name} = {name}.0;\n"));
                    }
                } else if matches!(f.ty, TypeRef::String | TypeRef::Path | TypeRef::Char | TypeRef::Json | TypeRef::Bytes) {
                    // String-like fields may map to enum/Named types in the source struct
                    // (alef's IR uses String as a fallback when the actual type can't be
                    // resolved). JSON-deserialize at runtime; on failure leave the default.
                    if f.optional {
                        out.push_str(&format!(
                            "        if let Some(s) = {name} {{\n"
                        ));
                        out.push_str(&format!(
                            "            if let Ok(v) = ::serde_json::from_str::<::serde_json::Value>(&s) {{\n"
                        ));
                        out.push_str(&format!(
                            "                if let Ok(t) = ::serde_json::from_value(v) {{ __target.{name} = Some(t); }}\n"
                        ));
                        out.push_str("            }\n        }\n");
                    } else {
                        out.push_str(&format!(
                            "        if let Ok(v) = ::serde_json::from_str::<::serde_json::Value>(&{name}) {{\n"
                        ));
                        out.push_str(&format!(
                            "            if let Ok(t) = ::serde_json::from_value(v) {{ __target.{name} = t; }}\n"
                        ));
                        out.push_str("        }\n");
                    }
                } else {
                    out.push_str(&format!("        __target.{name} = {name};\n"));
                }
            }
            out.push_str(&format!("        {}(__target)\n", ty.name));
        } else {
            out.push_str(&format!(
                "        {}({}::{} {{\n",
                ty.name, source_crate, ty.name
            ));
            for init in &field_inits {
                out.push_str(init);
                out.push_str(",\n");
            }
            out.push_str("        })\n");
        }
        out.push_str("    }\n");

        // Getters — return bridge types (String for JSON-bridged, wrappers for Named).
        for field in &ty.fields {
            let bridge_ty = bridge_type(&field.ty);
            let bridge_ty_owned = if field.optional && !needs_json_bridge(&field.ty) {
                format!("Option<{bridge_ty}>")
            } else {
                bridge_ty
            };
            let name = field.name.to_snake_case();
            if needs_json_bridge(&field.ty) {
                out.push_str(&format!(
                    "    pub fn {name}(&self) -> {bridge_ty_owned} {{ serde_json::to_string(&self.0.{name}).expect(\"serializable {name}\") }}\n"
                ));
            } else if matches!(field.ty, TypeRef::Named(ref _n) if true) {
                // Named field: wrap source value in our newtype so the Swift
                // side gets the bridge wrapper (preserves nominal identity).
                let wrapper = match &field.ty {
                    TypeRef::Named(n) => n.clone(),
                    _ => unreachable!(),
                };
                if field.optional {
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> Option<{wrapper}> {{ self.0.{name}.clone().map({wrapper}) }}\n"
                    ));
                } else {
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> {wrapper} {{ {wrapper}(self.0.{name}.clone()) }}\n"
                    ));
                }
            } else if matches!(field.ty, TypeRef::String | TypeRef::Path | TypeRef::Char | TypeRef::Json | TypeRef::Bytes) {
                // String-like fields might be JSON-bridged enums in the source struct;
                // serialize via serde_json so the result works for both `String` and
                // typed source fields.
                if field.optional {
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> {bridge_ty_owned} {{ self.0.{name}.as_ref().and_then(|v| serde_json::to_string(v).ok()) }}\n"
                    ));
                } else {
                    out.push_str(&format!(
                        "    pub fn {name}(&self) -> {bridge_ty_owned} {{ serde_json::to_string(&self.0.{name}).unwrap_or_default() }}\n"
                    ));
                }
            } else {
                out.push_str(&format!(
                    "    pub fn {name}(&self) -> {bridge_ty_owned} {{ self.0.{name}.clone() }}\n"
                ));
            }
        }

        out.push_str("}\n");
    }

    out
}

fn emit_enum_wrapper(en: &EnumDef, source_crate: &str) -> String {
    let mut out = String::new();
    out.push_str(&format!("pub enum {} {{\n", en.name));
    for variant in &en.variants {
        let variant_name = variant.name.to_upper_camel_case();
        out.push_str(&format!("    {variant_name},\n"));
    }
    out.push_str("}\n\n");

    // From conversion
    out.push_str(&format!(
        "impl From<{}::{}> for {} {{\n",
        source_crate, en.name, en.name
    ));
    out.push_str(&format!(
        "    fn from(val: {}::{}) -> Self {{\n",
        source_crate, en.name
    ));
    out.push_str("        match val {\n");
    for variant in &en.variants {
        let variant_name = variant.name.to_upper_camel_case();
        out.push_str(&format!(
            "            {}::{}::{} => Self::{},\n",
            source_crate, en.name, variant_name, variant_name
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

// ── function shim emitters ────────────────────────────────────────────────────

/// Build the call-site expression for a function parameter, mirroring the
/// Dart backend's `dart_call_arg`: handle JSON-bridged types, Path conversion,
/// primitive casts, and reference borrows based on `is_ref`/`optional`.
///
/// Named types are wrapped as `pub struct T(pub kreuzberg::T)`, so accessing
/// the inner kreuzberg type requires `.0` indirection. Wrappers are passed by
/// value across the bridge but kreuzberg fns generally take a reference, so
/// we emit `&name.0` for `is_ref=true` Named params.
fn swift_call_arg(p: &alef_core::ir::ParamDef) -> String {
    let name = p.name.to_snake_case();
    let original = p.original_type.as_deref().unwrap_or("");
    let stripped_orig = original
        .trim()
        .trim_start_matches('&')
        .trim_start_matches("mut ")
        .trim();

    // Tuple parameters: same shape as the Dart codegen — IR flattens
    // `Vec<(A, B, ...)>` to `Vec<String>` and stores the original signature in
    // `original_type`. Reconstruct sensible defaults for known tuple shapes.
    if !stripped_orig.is_empty() && stripped_orig.starts_with("Vec(") && stripped_orig.contains("Named(\"(") {
        let tuple_inner = stripped_orig
            .find("Named(\"(")
            .and_then(|start| {
                let rest = &stripped_orig[start + 8..];
                rest.find(")\")").map(|end| rest[..end].trim_end_matches(')').to_string())
            })
            .unwrap_or_default();
        if tuple_inner.starts_with("PathBuf,") || tuple_inner.starts_with("PathBuf ,") {
            return format!(
                "{name}.into_iter().map(|p| (std::path::PathBuf::from(p), None)).collect::<Vec<_>>()"
            );
        }
        if tuple_inner.starts_with("Vec<u8>,") || tuple_inner.starts_with("Vec<u8> ,") {
            return format!("{{ let _ = {name}; ::std::unimplemented!(\"batch_extract_bytes from Swift not yet bridged\") }}");
        }
    }

    // JSON-bridged: deserialize from the bridged String.
    if needs_json_bridge(&p.ty) {
        let native_ty = swift_bridge_rust_type(&p.ty);
        return format!("serde_json::from_str::<{native_ty}>(&{name}).expect(\"valid JSON for {name}\")");
    }

    // Path: bridged as String; convert to PathBuf or &Path.
    if matches!(p.ty, TypeRef::Path) {
        if p.optional {
            if p.is_ref {
                return format!("{name}.as_ref().map(std::path::Path::new)");
            }
            return format!("{name}.map(std::path::PathBuf::from)");
        }
        if p.is_ref {
            return format!("std::path::Path::new(&{name})");
        }
        return format!("std::path::PathBuf::from({name})");
    }

    // Named types: unwrap the swift-bridge wrapper newtype with `.0`.
    if matches!(p.ty, TypeRef::Named(_)) {
        if p.optional {
            if p.is_ref {
                return format!("{name}.as_ref().map(|w| &w.0)");
            }
            return format!("{name}.map(|w| w.0)");
        }
        if p.is_ref {
            return format!("&{name}.0");
        }
        return format!("{name}.0");
    }

    // Primitive: swift-bridge maps integer widths well, but reference params
    // still need `&`.
    if let TypeRef::Primitive(_) = &p.ty {
        if p.is_ref {
            return format!("&{name}");
        }
        return name;
    }

    if !p.is_ref {
        return name;
    }
    match (&p.ty, p.optional) {
        (TypeRef::Bytes, false) => format!("&{name}"),
        (TypeRef::String | TypeRef::Char, false) => format!("&{name}"),
        (TypeRef::String | TypeRef::Char, true) => format!("{name}.as_deref()"),
        (TypeRef::Vec(_), true) => format!("{name}.as_deref()"),
        _ => format!("&{name}"),
    }
}

fn emit_function_shim(f: &FunctionDef, source_crate: &str) -> String {
    let fn_name = f.name.to_snake_case();
    let params: Vec<String> = f
        .params
        .iter()
        .map(|p| {
            let bridge_ty = bridge_type(&p.ty);
            let bridge_ty = if p.optional {
                format!("Option<{bridge_ty}>")
            } else {
                bridge_ty
            };
            let name = p.name.to_snake_case();
            format!("{name}: {bridge_ty}")
        })
        .collect();
    let params_str = params.join(", ");

    let return_ty = if f.error_type.is_some() {
        let ok_ty = bridge_type(&f.return_type);
        if matches!(f.return_type, TypeRef::Unit) {
            "Result<(), String>".to_string()
        } else {
            format!("Result<{ok_ty}, String>")
        }
    } else {
        bridge_type(&f.return_type)
    };

    // Build call args, deserializing JSON-bridged params before passing to the real fn
    let call_args: Vec<String> = f
        .params
        .iter()
        .map(|p| swift_call_arg(p))
        .collect();
    let call_args_str = call_args.join(", ");

    // Resolve the source call via the IR's full rust_path so module-prefixed
    // functions (e.g. `my_lib::utils::helper`) generate correct shim calls.
    // Falls back to the bare fn name if rust_path is empty.
    let resolved_path = if f.rust_path.is_empty() {
        format!("{source_crate}::{fn_name}")
    } else {
        f.rust_path.replace('-', "_")
    };
    let source_call = format!("{resolved_path}({call_args_str})");

    // Wrap return value with JSON serialization when the return type is not natively
    // supported by swift-bridge 0.1.59 (nested generics, HashMap). Named return
    // types must be wrapped in their swift-bridge newtype (`pub struct T(pub kreuzberg::T)`).
    // Async fns must `.await` before mapping; sync fns can chain directly.
    let json_wrap_ok = needs_json_bridge(&f.return_type);
    // Determine the wrapper to apply for Named return types — the swift-bridge
    // wrappers are nominal newtypes, so we need to construct them from the source
    // value. Three cases:
    //   - Named(T) → wrap with `T(...)`
    //   - Optional(Named(T)) → `.map(T)`
    //   - Vec(Named(T)) → `.into_iter().map(T).collect::<Vec<_>>()`
    enum WrapShape {
        Direct(String),    // T(value)
        OptMap(String),    // value.map(T)
        VecMap(String),    // value.into_iter().map(T).collect()
    }
    let wrap_shape = match &f.return_type {
        TypeRef::Named(n) => Some(WrapShape::Direct(n.clone())),
        TypeRef::Optional(inner) => match inner.as_ref() {
            TypeRef::Named(n) => Some(WrapShape::OptMap(n.clone())),
            _ => None,
        },
        TypeRef::Vec(inner) => match inner.as_ref() {
            TypeRef::Named(n) => Some(WrapShape::VecMap(n.clone())),
            _ => None,
        },
        _ => None,
    };
    let value_map_string: String = if json_wrap_ok {
        ".map(|v| serde_json::to_string(&v).expect(\"serializable return\"))".to_string()
    } else {
        match &wrap_shape {
            Some(WrapShape::Direct(t)) => format!(".map({t})"),
            Some(WrapShape::OptMap(t)) => format!(".map(|v| v.map({t}))"),
            Some(WrapShape::VecMap(t)) => format!(".map(|v| v.into_iter().map({t}).collect::<Vec<_>>())"),
            None => String::new(),
        }
    };
    let value_map = value_map_string.as_str();
    // Direct (non-Result) wrap for the value.
    let direct_wrap = |source: String| -> String {
        if json_wrap_ok {
            return format!("serde_json::to_string(&({source})).expect(\"serializable return\")");
        }
        match &wrap_shape {
            Some(WrapShape::Direct(t)) => format!("{t}({source})"),
            Some(WrapShape::OptMap(t)) => format!("({source}).map({t})"),
            Some(WrapShape::VecMap(t)) => format!("({source}).into_iter().map({t}).collect::<Vec<_>>()"),
            None => source,
        }
    };
    let body = if f.is_async {
        let mut chain = format!("{source_call}.await");
        if f.error_type.is_some() {
            chain = format!("{chain}.map_err(|e| e.to_string()){value_map}");
        } else {
            chain = direct_wrap(chain);
        }
        chain
    } else if f.error_type.is_some() {
        format!("{source_call}.map_err(|e| e.to_string()){value_map}")
    } else {
        direct_wrap(source_call)
    };

    // The wrapper is always sync — swift-bridge 0.1.59 doesn't support async
    // functions in extern blocks, so async source calls are blocked-on inside
    // a tokio runtime. The runtime is created lazily on first call.
    if f.is_async {
        format!(
            "pub fn {fn_name}({params_str}) -> {return_ty} {{\n    \
            ::tokio::runtime::Builder::new_current_thread()\n        \
                .enable_all()\n        \
                .build()\n        \
                .expect(\"build tokio runtime\")\n        \
                .block_on(async {{ {body} }})\n}}\n"
        )
    } else {
        format!("pub fn {fn_name}({params_str}) -> {return_ty} {{\n    {body}\n}}\n")
    }
}

// ── type mapping for swift-bridge Rust side ───────────────────────────────────

/// Returns true for types that swift-bridge 0.1.59 cannot handle inside `extern "Rust"` blocks.
///
/// Two distinct bugs in swift-bridge-ir-0.1.59 are covered:
///
/// 1. **Parser bug** (`bridged_type.rs:826`): `BridgedType::new_with_str` uses
///    `trim_end_matches(" >")` which strips ALL trailing ` >` occurrences. This corrupts
///    `Vec < Option < String > >` into `Vec < Option < String` causing `syn::parse2` to
///    fail with `Error("expected ','")`.
///
/// 2. **Codegen todo** (`bridged_type.rs:1986`): `BuiltInResult::is_custom_result_type()`
///    returns `true` when the ok type is a `StdLib` non-Vec type (e.g. `Option<T>`,
///    primitives). When true, the codegen calls `to_alpha_numeric_underscore_name` on the
///    ok type, but `StdLib::Option` and `StdLib::Vec` hit `_ => todo!()` there.
///
/// HashMap is completely unsupported by swift-bridge.
///
/// All affected types are serialized to JSON (`String`) at the bridge boundary.
fn needs_json_bridge(ty: &TypeRef) -> bool {
    match ty {
        // HashMap is unsupported by swift-bridge regardless of nesting.
        TypeRef::Map(_, _) => true,
        // Vec<T> is only safe when T is a "leaf" type (no angle brackets in its token form).
        // Primitives, String, char, Named opaques, and Vec<u8> (Bytes) are all safe.
        // Anything else (Vec<Option<..>>, Vec<Vec<..>>, Vec<Map<..>>) triggers the parser bug.
        TypeRef::Vec(inner) => !is_bridge_leaf(inner),
        // Option<T> as a Result ok-type causes is_custom_result_type()=true + todo!() in
        // to_alpha_numeric_underscore_name. JSON-bridge all Optional types to avoid this.
        TypeRef::Optional(_) => true,
        _ => false,
    }
}

/// Returns true when `ty` produces a token-stream representation with no angle brackets,
/// i.e. it is safe as the inner type of a `Vec<T>` in a swift-bridge extern block.
fn is_bridge_leaf(ty: &TypeRef) -> bool {
    match ty {
        TypeRef::Primitive(_)
        | TypeRef::String
        | TypeRef::Char
        | TypeRef::Path
        | TypeRef::Json
        | TypeRef::Unit
        | TypeRef::Duration => true,
        // Bytes = Vec<u8> — swift-bridge supports this directly.
        TypeRef::Bytes => true,
        // Named opaque types (wrapper newtypes) have no angle brackets.
        TypeRef::Named(_) => true,
        // Everything else (Vec, Optional, Map) produces angle brackets in the token stream.
        _ => false,
    }
}

/// Maps an IR `TypeRef` to the Rust type used in swift-bridge `extern "Rust"` block declarations.
///
/// Types that swift-bridge 0.1.59 cannot parse (nested generics, HashMap) are collapsed to
/// `String` (JSON-serialized at the shim boundary). All other types use their native Rust form.
fn bridge_type(ty: &TypeRef) -> String {
    if needs_json_bridge(ty) {
        return "String".to_string();
    }
    match ty {
        TypeRef::Optional(inner) => format!("Option<{}>", bridge_type(inner)),
        TypeRef::Vec(inner) => format!("Vec<{}>", bridge_type(inner)),
        _ => swift_bridge_rust_type(ty),
    }
}

/// Maps an IR `TypeRef` to the native Rust type string (used in wrapper impls and shim bodies).
///
/// This is the full native type including nested generics and HashMap — used on the Rust side
/// of the shim where swift-bridge is not involved.
fn swift_bridge_rust_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Primitive(p) => rust_primitive_str(p).to_string(),
        TypeRef::String => "String".to_string(),
        TypeRef::Char => "char".to_string(),
        TypeRef::Bytes => "Vec<u8>".to_string(),
        TypeRef::Path => "String".to_string(),
        TypeRef::Json => "String".to_string(),
        TypeRef::Unit => "()".to_string(),
        TypeRef::Duration => "u64".to_string(),
        TypeRef::Optional(inner) => format!("Option<{}>", swift_bridge_rust_type(inner)),
        TypeRef::Vec(inner) => format!("Vec<{}>", swift_bridge_rust_type(inner)),
        TypeRef::Map(k, v) => {
            format!(
                "std::collections::HashMap<{}, {}>",
                swift_bridge_rust_type(k),
                swift_bridge_rust_type(v)
            )
        }
        TypeRef::Named(name) => name.clone(),
    }
}

fn rust_primitive_str(p: &PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::Bool => "bool",
        PrimitiveType::U8 => "u8",
        PrimitiveType::I8 => "i8",
        PrimitiveType::U16 => "u16",
        PrimitiveType::I16 => "i16",
        PrimitiveType::U32 => "u32",
        PrimitiveType::I32 => "i32",
        PrimitiveType::U64 => "u64",
        PrimitiveType::I64 => "i64",
        PrimitiveType::Usize => "usize",
        PrimitiveType::Isize => "isize",
        PrimitiveType::F32 => "f32",
        PrimitiveType::F64 => "f64",
    }
}
