use alef_core::backend::{Backend, BuildConfig, BuildDependency, Capabilities, GeneratedFile};
use alef_core::config::{AlefConfig, Language, resolve_output_dir};
use alef_core::ir::{ApiSurface, EnumDef, FunctionDef, ParamDef, PrimitiveType, TypeDef, TypeRef};
use std::path::PathBuf;

pub struct ZigBackend;

impl Backend for ZigBackend {
    fn name(&self) -> &str {
        "zig"
    }

    fn language(&self) -> Language {
        Language::Zig
    }

    fn capabilities(&self) -> Capabilities {
        Capabilities {
            supports_async: false,
            supports_classes: false,
            supports_enums: true,
            supports_option: true,
            supports_result: true,
            supports_callbacks: false,
            supports_streaming: false,
        }
    }

    fn generate_bindings(&self, api: &ApiSurface, config: &AlefConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let module_name = zig_module_name(&config.crate_config.name);
        let header = config.ffi_header_name();
        let prefix = config.ffi_prefix();

        let mut content = String::new();
        content.push_str("// Generated by alef. Do not edit by hand.\n\n");
        content.push_str("const std = @import(\"std\");\n");
        content.push_str(&format!("pub const c = @cImport(@cInclude(\"{header}\"));\n\n"));

        for ty in &api.types {
            emit_type(ty, &mut content);
            content.push('\n');
        }

        for en in &api.enums {
            emit_enum(en, &mut content);
            content.push('\n');
        }

        for f in &api.functions {
            emit_function(f, &prefix, &mut content);
            content.push('\n');
        }

        let dir = resolve_output_dir(None, &config.crate_config.name, "packages/zig/src");
        let path = PathBuf::from(dir).join(format!("{module_name}.zig"));

        Ok(vec![GeneratedFile {
            path,
            content,
            generated_header: false,
        }])
    }

    fn build_config(&self) -> Option<BuildConfig> {
        Some(BuildConfig {
            tool: "zig",
            crate_suffix: "",
            build_dep: BuildDependency::Ffi,
            post_build: vec![],
        })
    }
}

fn emit_type(ty: &TypeDef, out: &mut String) {
    if !ty.doc.is_empty() {
        for line in ty.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!("pub const {} = struct {{\n", ty.name));
    for field in &ty.fields {
        let ty_str = zig_field_type(&field.ty, field.optional);
        out.push_str(&format!("    {}: {},\n", field.name, ty_str));
    }
    out.push_str("};\n");
}

fn emit_enum(en: &EnumDef, out: &mut String) {
    if !en.doc.is_empty() {
        for line in en.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    let all_unit = en.variants.iter().all(|v| v.fields.is_empty());
    if all_unit {
        out.push_str(&format!("pub const {} = enum {{\n", en.name));
        for variant in &en.variants {
            out.push_str(&format!("    {},\n", to_snake_case(&variant.name)));
        }
        out.push_str("};\n");
    } else {
        out.push_str(&format!("pub const {} = union(enum) {{\n", en.name));
        for variant in &en.variants {
            let tag = to_snake_case(&variant.name);
            if variant.fields.is_empty() {
                out.push_str(&format!("    {tag}: void,\n"));
            } else if variant.fields.len() == 1 {
                let ty_str = zig_field_type(&variant.fields[0].ty, variant.fields[0].optional);
                out.push_str(&format!("    {tag}: {ty_str},\n"));
            } else {
                out.push_str(&format!("    {tag}: struct {{\n"));
                for f in &variant.fields {
                    let name = if f.name.is_empty() { "value".into() } else { f.name.clone() };
                    let ty_str = zig_field_type(&f.ty, f.optional);
                    out.push_str(&format!("        {name}: {ty_str},\n"));
                }
                out.push_str("    },\n");
            }
        }
        out.push_str("};\n");
    }
}

fn emit_function(f: &FunctionDef, prefix: &str, out: &mut String) {
    if !f.doc.is_empty() {
        for line in f.doc.lines() {
            out.push_str("/// ");
            out.push_str(line);
            out.push('\n');
        }
    }
    let params: Vec<String> = f.params.iter().map(format_param).collect();
    let return_ty = zig_field_type(&f.return_type, false);
    out.push_str(&format!(
        "pub fn {}({}) {} {{\n",
        f.name,
        params.join(", "),
        return_ty
    ));
    let arg_names: Vec<String> = f.params.iter().map(|p| p.name.clone()).collect();
    out.push_str(&format!(
        "    return c.{prefix}_{}({});\n",
        f.name,
        arg_names.join(", ")
    ));
    out.push_str("}\n");
}

fn format_param(p: &ParamDef) -> String {
    let ty_str = zig_field_type(&p.ty, p.optional);
    format!("{}: {}", p.name, ty_str)
}

fn zig_field_type(ty: &TypeRef, optional: bool) -> String {
    let inner = render_type_ref(ty);
    if optional { format!("?{inner}") } else { inner }
}

fn render_type_ref(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Primitive(p) => primitive(p).to_string(),
        TypeRef::String | TypeRef::Path | TypeRef::Json => "[:0]const u8".to_string(),
        TypeRef::Char => "u21".to_string(),
        TypeRef::Bytes => "[]const u8".to_string(),
        TypeRef::Optional(inner) => format!("?{}", render_type_ref(inner)),
        TypeRef::Vec(inner) => format!("[]const {}", render_type_ref(inner)),
        TypeRef::Map(_, v) => format!("std.StringHashMap({})", render_type_ref(v)),
        TypeRef::Named(name) => name.clone(),
        TypeRef::Unit => "void".to_string(),
        TypeRef::Duration => "i64".to_string(),
    }
}

fn primitive(p: &PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::Bool => "bool",
        PrimitiveType::U8 => "u8",
        PrimitiveType::U16 => "u16",
        PrimitiveType::U32 => "u32",
        PrimitiveType::U64 | PrimitiveType::Usize => "u64",
        PrimitiveType::I8 => "i8",
        PrimitiveType::I16 => "i16",
        PrimitiveType::I32 => "i32",
        PrimitiveType::I64 | PrimitiveType::Isize => "i64",
        PrimitiveType::F32 => "f32",
        PrimitiveType::F64 => "f64",
    }
}

fn zig_module_name(crate_name: &str) -> String {
    crate_name.replace('-', "_")
}

fn to_snake_case(name: &str) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}
